In [1]:
import os
import ast

import pandas as pd
import matplotlib.pyplot as plt
import scipy

from plotting_utils import (
    get_train_domain,
    get_test_domain,
    get_model_name,
    wanted_metrics
)

pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.multi_sparse', True)
PROJECT_DIR = os.environ["MDS"]

# Load and format results

In [2]:
results_df = pd.read_csv(
    f"{PROJECT_DIR}/results_mayarr_sample/experiments_mayarr/aggregated_results.csv",
    header=[0,1]
)
results_df.columns = pd.Index([
  f"{c[0]}_{c[1]}" if c[1]!="nan" else c[0] for c in results_df.columns
])

results_df["train_domain"] = results_df.apply(get_train_domain, axis="columns")
results_df["test_domain"] = results_df.dataset.map(get_test_domain)
results_df["model_type"] = results_df.model.map(get_model_name)

# Remove validation set
results_df = results_df[results_df.split=="test"]

new_columns = [
    "model_type",
    "train_domain",
    "test_domain",
] + wanted_metrics

# Add placeholders
for c in new_columns:
    if c not in results_df.columns:
        results_df[c] = pd.NA

results_df = results_df[new_columns]

def format_entry(entry: str):
    try:
        entry = ast.literal_eval(entry)
    except ValueError as err:
        print(f"Could not convert '{entry}' as literal")
        return pd.NA
    return entry.get("mean", pd.NA)

# Display only the mean
for metric in wanted_metrics:
    results_df[metric] = results_df[metric].map(format_entry)

# Change compression so that higher score = more compressed summary
# 1 - (# sentences in summary / # sentences in source docs)
for m in ["compression_sentence", "compression_token"]:
    results_df[m] = 1 - results_df[m]


# Hack
results_df = results_df.fillna(-1)

Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal

/tmp/ipykernel_3289354/2072983755.py:48: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  results_df = results_df.fillna(-1)

In [3]:
results_df

,model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
0,ground_truth,Convo,Convo,0.71,3.07,3.06,0.99,3.23,-1.00,-1.00,-1.00,0.89,3.30,0.73,3.39,0.90,0.85,2.57
1,PRIMERA,Science,Convo,0.80,1.43,1.49,0.41,1.77,0.19,0.11,-0.02,0.64,1.34,0.67,1.28,-4.46,-2.61,1.58
2,PRIMERA,Convo,Convo,0.81,1.41,1.52,0.40,1.77,0.19,0.11,-0.01,0.64,1.31,0.75,1.22,-5.10,-3.93,1.54
3,PRIMERA,News+,Convo,0.82,1.34,1.53,0.40,1.76,0.19,0.11,-0.01,0.67,1.36,0.72,1.26,-5.29,-3.17,1.52
4,SummN,Science,Convo,0.39,1.13,1.21,0.33,1.26,0.21,0.14,-0.04,0.63,1.37,0.33,1.25,-6.52,-4.14,1.26
5,SummN,Convo,Convo,0.66,2.39,2.50,0.72,2.71,0.33,0.21,0.09,0.91,2.88,0.71,2.78,-10.81,-8.11,2.18
6,SummN,News+,Convo,0.67,1.44,1.58,0.71,1.95,0.22,0.13,0.00,0.70,1.74,0.73,1.58,-3.45,-2.16,1.67
7,ConvoSumm,Science,Convo,0.44,1.22,1.26,0.26,1.34,0.22,0.15,-0.01,0.60,1.27,0.26,1.29,-9.32,-7.78,1.25
8,ConvoSumm,Convo,Convo,0.64,2.13,2.39,0.70,2.52,0.31,0.21,0.06,0.91,2.61,0.59,2.43,-12.40,-12.23,1.97
9,ConvoSumm,News+,Convo,0.68,1.59,1.78,0.75,1.97,0.23,0.13,0.01,0.70,1.72,0.78,1.74,-3.62,-2.51,1.77
10,Llama 3.1 (0-shot),zero-shot,Convo,0.83,3.12,3.31,0.94,3.44,0.22,0.15,0.05,0.93,4.01,0.96,3.87,-3.74,-1.40,2.79
11,Llama 3.1,Convo,Convo,0.81,3.09,3.26,0.95,3.47,0.21,0.15,0.05,0.93,3.94,0.96,3.97,-3.64,-1.35,2.95
12,Llama 3.1,Science,Convo,0.82,3.17,3.21,0.94,3.47,0.22,0.15,0.06,0.93,3.94,0.96,3.92,-4.00,-1.46,2.91
13,Llama 3.1,News+,Convo,0.82,3.01,3.23,0.94,3.43,0.22,0.15,0.05,0.94,3.99,0.96,3.92,-3.88,-1.36,2.96
14,ground_truth,Science,Science,0.55,1.82,1.86,0.99,2.78,-1.00,-1.00,-1.00,0.67,1.53,0.45,1.51,-6.32,-5.63,1.90
15,PRIMERA,Science,Science,0.84,1.96,1.98,0.62,2.39,0.22,0.12,0.05,0.77,1.75,0.74,1.80,-2.42,-1.67,2.00
16,PRIMERA,Convo,Science,0.84,1.96,1.95,0.61,2.38,0.23,0.12,0.06,0.79,1.82,0.73,1.79,-2.23,-1.59,1.94
17,PRIMERA,News+,Science,0.82,2.03,1.96,0.65,2.40,0.23,0.12,0.06,0.82,1.92,0.74,1.83,-2.40,-1.61,2.04
18,SummN,Science,Science,0.56,1.46,1.45,0.49,1.71,0.26,0.15,0.03,0.68,1.41,0.39,1.40,-3.99,-4.70,1.50
19,SummN,Convo,Science,0.77,2.51,2.36,0.72,2.48,0.21,0.13,0.01,0.92,2.61,0.88,2.27,-7.72,-11.28,1.99
20,SummN,News+,Science,0.64,1.57,1.54,0.67,2.15,0.21,0.12,0.03,0.77,1.63,0.68,1.68,-1.39,-1.26,1.83
21,ConvoSumm,Science,Science,0.65,1.61,1.49,0.49,1.84,0.27,0.16,0.03,0.68,1.60,0.35,1.51,-4.91,-6.82,1.53
22,ConvoSumm,Convo,Science,0.67,1.95,1.97,0.61,2.27,0.23,0.14,0.02,0.91,2.22,0.58,2.03,-5.17,-9.23,1.76
23,ConvoSumm,News+,Science,0.69,1.77,1.76,0.70,2.13,0.23,0.13,0.04,0.81,1.79,0.71,1.87,-2.31,-2.32,1.89
24,Llama 3.1 (0-shot),zero-shot,Science,0.87,3.42,3.52,0.93,3.47,0.24,0.16,0.08,0.93,4.06,0.98,3.96,-1.38,-1.30,3.29
25,Llama 3.1,Convo,Science,0.88,3.32,3.47,0.91,3.58,0.24,0.15,0.08,0.94,4.06,0.97,4.00,-1.39,-1.29,3.23
26,Llama 3.1,Science,Science,0.88,3.40,3.46,0.91,3.53,0.24,0.15,0.08,0.93,3.94,0.97,3.95,-1.38,-1.29,3.17
27,Llama 3.1,News+,Science,0.88,3.38,3.45,0.92,3.61,0.24,0.15,0.09,0.93,4.03,0.98,4.00,-1.30,-1.26,3.19
28,ground_truth,News+,News+,0.73,2.84,3.16,0.99,3.39,-1.00,-1.00,1.00,0.77,2.75,0.74,3.70,-1.17,-1.10,2.69
29,PRIMERA,Science,News+,0.78,1.96,2.07,0.44,2.33,0.38,0.18,0.13,0.62,1.95,0.68,1.94,-2.42,-1.51,1.99
30,PRIMERA,Convo,News+,0.83,1.97,2.08,0.41,2.38,0.38,0.18,0.13,0.63,2.04,0.71,1.94,-1.99,-1.28,2.01
31,PRIMERA,News+,News+,0.78,2.01,2.17,0.43,2.37,0.37,0.18,0.12,0.63,1.94,0.65,1.86,-2.33,-1.38,1.94
32,SummN,Science,News+,0.65,1.95,2.04,0.33,2.36,0.31,0.17,0.04,0.69,2.05,0.35,2.07,-3.14,-3.58,1.90
33,SummN,Convo,News+,0.90,2.71,2.64,0.64,2.75,0.23,0.14,0.01,0.89,2.92,0.82,2.74,-5.47,-8.28,2.18
34,SummN,News+,News+,0.72,2.22,2.28,0.78,2.58,0.46,0.23,0.19,0.74,2.48,0.80,2.76,-1.18,-1.23,2.16
35,ConvoSumm,Science,News+,0.66,1.81,1.87,0.26,2.10,0.30,0.16,0.04,0.64,1.65,0.30,1.70,-3.37,-3.99,1.69
36,ConvoSumm,Convo,News+,0.75,1.83,1.90,0.51,2.08,0.24,0.14,0.00,0.91,2.02,0.57,1.94,-4.31,-7.54,1.68
37,ConvoSumm,News+,News+,0.78,2.39,2.54,0.80,2.72,0.46,0.24,0.20,0.74,2.68,0.84,2.99,-1.31,-1.45,2.28
38,Llama 3.1 (0-shot),zero-shot,News+,0.88,3.26,3.41,0.93,3.57,0.41,0.22,0.16,0.94,4.04,0.94,4.00,-2.07,-1.64,3.02
39,Llama 3.1,Convo,News+,0.87,3.24,3.56,0.92,3.64,0.40,0.21,0.16,0.94,4.11,0.95,3.98,-2.31,-1.79,3.02
40,Llama 3.1,Science,News+,0.87,3.25,3.54,0.94,3.64,0.40,0.22,0.16,0.95,4.07,0.95,3.98,-2.15,-1.69,2.93
41,Llama 3.1,News+,News+,0.87,3.20,3.47,0.92,3.59,0.40,0.21,0.16,0.94,4.04,0.95,3.93,-2.23,-1.75,2.96

In [4]:
a = results_df.set_index(["model_type", "train_domain", "test_domain"]).sort_index()
print(a.to_csv(float_format='%.2f'))
a

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,Convo,0.64,2.13,2.39,0.70,2.52,0.31,0.21,0.06,0.91,2.61,0.59,2.43,-12.40,-12.23,1.97
ConvoSumm,Convo,News+,0.75,1.83,1.90,0.51,2.08,0.24,0.14,0.00,0.91,2.02,0.57,1.94,-4.31,-7.54,1.68
ConvoSumm,Convo,Science,0.67,1.95,1.97,0.61,2.27,0.23,0.14,0.02,0.91,2.22,0.58,2.03,-5.17,-9.23,1.76
ConvoSumm,News+,Convo,0.68,1.59,1.78,0.75,1.97,0.23,0.13,0.01,0.70,1.72,0.78,1.74,-3.62,-2.51,1.77
ConvoSumm,News+,News+,0.78,2.39,2.54,0.80,2.72,0.46,0.24,0.20,0.74,2.68,0.84,2.99,-1.31,-1.45,2.28
ConvoSumm,News+,Science,0.69,1.77,1.76,0.70,2.13,0.23,0.13,0.04,0.81,1.79,0.71,1.87,-2.31,-2.32,1.89
ConvoSumm,Science,Convo,0.44,1.22,1.26,0.26,1.34,0.22,0.15,-0.01,0.60,1.27,0.26,1.29,-9.32,-7.78,1.25
ConvoSumm,Science,News+,0.66,1.81,1.87,0.26,2.10,0.30,0.16,0.04,0.64,1.65,0.30,1.70,-3.37,-3.99,1.69
ConvoSumm,Science,Science,0.65,1.61,1.49,0.49,1.84,0.27,0.16,0.03,0.68,1.60,0.35,1.51,-4.91,-6.82,1.53
Llama 3.1,Convo,Convo,0.81,3.09,3.26,0.95,3.47,0.21,0.15,0.05,0.93,3.94,0.96,3.97,-3.64,-1.35,2.95
Llama 3.1,Convo,News+,0.87,3.24,3.56,0.92,3.64,0.40,0.21,0.16,0.94,4.11,0.95,3.98,-2.31,-1.79,3.02
Llama 3.1,Convo,Science,0.88,3.32,3.47,0.91,3.58,0.24,0.15,0.08,0.94,4.06,0.97,4.00,-1.39,-1.29,3.23
Llama 3.1,News+,Convo,0.82,3.01,3.23,0.94,3.43,0.22,0.15,0.05,0.94,3.99,0.96,3.92,-3.88,-1.36,2.96
Llama 3.1,News+,News+,0.87,3.20,3.47,0.92,3.59,0.40,0.21,0.16,0.94,4.04,0.95,3.93,-2.23,-1.75,2.96
Llama 3.1,News+,Science,0.88,3.38,3.45,0.92,3.61,0.24,0.15,0.09,0.93,4.03,0.98,4.00,-1.30,-1.26,3.19
Llama 3.1,Science,Convo,0.82,3.17,3.21,0.94,3.47,0.22,0.15,0.06,0.93,3.94,0.96,3.92,-4.00,-1.46,2.91
Llama 3.1,Science,News+,0.87,3.25,3.54,0.94,3.64,0.40,0.22,0.16,0.95,4.07,0.95,3.98,-2.15,-1.69,2.93
Llama 3.1,Science,Science,0.88,3.40,3.46,0.91,3.53,0.24,0.15,0.08,0.93,3.94,0.97,3.95,-1.38,-1.29,3.17
Llama 3.1 (0-shot),zero-shot,Convo,0.83,3.12,3.31,0.94,3.44,0.22,0.15,0.05,0.93,4.01,0.96,3.87,-3.74,-1.40,2.79
Llama 3.1 (0-shot),zero-shot,News+,0.88,3.26,3.41,0.93,3.57,0.41,0.22,0.16,0.94,4.04,0.94,4.00,-2.07,-1.64,3.02
Llama 3.1 (0-shot),zero-shot,Science,0.87,3.42,3.52,0.93,3.47,0.24,0.16,0.08,0.93,4.06,0.98,3.96,-1.38,-1.30,3.29
PRIMERA,Convo,Convo,0.81,1.41,1.52,0.40,1.77,0.19,0.11,-0.01,0.64,1.31,0.75,1.22,-5.10,-3.93,1.54
PRIMERA,Convo,News+,0.83,1.97,2.08,0.41,2.38,0.38,0.18,0.13,0.63,2.04,0.71,1.94,-1.99,-1.28,2.01
PRIMERA,Convo,Science,0.84,1.96,1.95,0.61,2.38,0.23,0.12,0.06,0.79,1.82,0.73,1.79,-2.23,-1.59,1.94
PRIMERA,News+,Convo,0.82,1.34,1.53,0.40,1.76,0.19,0.11,-0.01,0.67,1.36,0.72,1.26,-5.29,-3.17,1.52
PRIMERA,News+,News+,0.78,2.01,2.17,0.43,2.37,0.37,0.18,0.12,0.63,1.94,0.65,1.86,-2.33,-1.38,1.94
PRIMERA,News+,Science,0.82,2.03,1.96,0.65,2.40,0.23,0.12,0.06,0.82,1.92,0.74,1.83,-2.40,-1.61,2.04
PRIMERA,Science,Convo,0.80,1.43,1.49,0.41,1.77,0.19,0.11,-0.02,0.64,1.34,0.67,1.28,-4.46,-2.61,1.58
PRIMERA,Science,News+,0.78,1.96,2.07,0.44,2.33,0.38,0.18,0.13,0.62,1.95,0.68,1.94,-2.42,-1.51,1.99
PRIMERA,Science,Science,0.84,1.96,1.98,0.62,2.39,0.22,0.12,0.05,0.77,1.75,0.74,1.80,-2.42,-1.67,2.00
SummN,Convo,Convo,0.66,2.39,2.50,0.72,2.71,0.33,0.21,0.09,0.91,2.88,0.71,2.78,-10.81,-8.11,2.18
SummN,Convo,News+,0.90,2.71,2.64,0.64,2.75,0.23,0.14,0.01,0.89,2.92,0.82,2.74,-5.47,-8.28,2.18
SummN,Convo,Science,0.77,2.51,2.36,0.72,2.48,0.21,0.13,0.01,0.92,2.61,0.88,2.27,-7.72,-11.28,1.99
SummN,News+,Convo,0.67,1.44,1.58,0.71,1.95,0.22,0.13,0.00,0.70,1.74,0.73,1.58,-3.45,-2.16,1.67
SummN,News+,News+,0.72,2.22,2.28,0.78,2.58,0.46,0.23,0.19,0.74,2.48,0.80,2.76,-1.18,-1.23,2.16
SummN,News+,Science,0.64,1.57,1.54,0.67,2.15,0.21,0.12,0.03,0.77,1.63,0.68,1.68,-1.39,-1.26,1.83
SummN,Science,Convo,0.39,1.13,1.21,0.33,1.26,0.21,0.14,-0.04,0.63,1.37,0.33,1.25,-6.52,-4.14,1.26
SummN,Science,News+,0.65,1.95,2.04,0.33,2.36,0.31,0.17,0.04,0.69,2.05,0.35,2.07,-3.14,-3.58,1.90
SummN,Science,Science,0.56,1.46,1.45,0.49,1.71,0.26,0.15,0.03,0.68,1.41,0.39,1.40,-3.99,-4.70,1.50
ground_truth,Convo,Convo,0.71,3.07,3.06,0.99,3.23,-1.00,-1.00,-1.00,0.89,3.30,0.73,3.39,0.90,0.85,2.57
ground_truth,News+,News+,0.73,2.84,3.16,0.99,3.39,-1.00,-1.00,1.00,0.77,2.75,0.74,3.70,-1.17,-1.10,2.69
ground_truth,Science,Science,0.55,1.82,1.86,0.99,2.78,-1.00,-1.00,-1.00,0.67,1.53,0.45,1.51,-6.32,-5.63,1.90

                                             unieval_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                      0.64
                                News+                      0.75
                                Science                    0.67
                   News+        Convo                      0.68
                                News+                      0.78
                                Science                    0.69
                   Science      Convo                      0.44
                                News+                      0.66
                                Science                    0.65
Llama 3.1          Convo        Convo                      0.81
                                News+                      0.87
                                Science                    0.88
                   News+        Convo                      0.82
                                News+                      0.87
                                Science                    0.88
                   Science      Convo                      0.82
                                News+                      0.87
                                Science                    0.88
Llama 3.1 (0-shot) zero-shot    Convo                      0.83
                                News+                      0.88
                                Science                    0.87
PRIMERA            Convo        Convo                      0.81
                                News+                      0.83
                                Science                    0.84
                   News+        Convo                      0.82
                                News+                      0.78
                                Science                    0.82
                   Science      Convo                      0.80
                                News+                      0.78
                                Science                    0.84
SummN              Convo        Convo                      0.66
                                News+                      0.90
                                Science                    0.77
                   News+        Convo                      0.67
                                News+                      0.72
                                Science                    0.64
                   Science      Convo                      0.39
                                News+                      0.65
                                Science                    0.56
ground_truth       Convo        Convo                      0.71
                   News+        News+                      0.73
                   Science      Science                    0.55

                                             prometheus_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                         2.13
                                News+                         1.83
                                Science                       1.95
                   News+        Convo                         1.59
                                News+                         2.39
                                Science                       1.77
                   Science      Convo                         1.22
                                News+                         1.81
                                Science                       1.61
Llama 3.1          Convo        Convo                         3.09
                                News+                         3.24
                                Science                       3.32
                   News+        Convo                         3.01
                                News+                         3.20
                                Science                       3.38
                   Science      Convo                         3.17
                                News+                         3.25
                                Science                       3.40
Llama 3.1 (0-shot) zero-shot    Convo                         3.12
                                News+                         3.26
                                Science                       3.42
PRIMERA            Convo        Convo                         1.41
                                News+                         1.97
                                Science                       1.96
                   News+        Convo                         1.34
                                News+                         2.01
                                Science                       2.03
                   Science      Convo                         1.43
                                News+                         1.96
                                Science                       1.96
SummN              Convo        Convo                         2.39
                                News+                         2.71
                                Science                       2.51
                   News+        Convo                         1.44
                                News+                         2.22
                                Science                       1.57
                   Science      Convo                         1.13
                                News+                         1.95
                                Science                       1.46
ground_truth       Convo        Convo                         3.07
                   News+        News+                         2.84
                   Science      Science                       1.82

                                             prometheus_consistency  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                          2.39
                                News+                          1.90
                                Science                        1.97
                   News+        Convo                          1.78
                                News+                          2.54
                                Science                        1.76
                   Science      Convo                          1.26
                                News+                          1.87
                                Science                        1.49
Llama 3.1          Convo        Convo                          3.26
                                News+                          3.56
                                Science                        3.47
                   News+        Convo                          3.23
                                News+                          3.47
                                Science                        3.45
                   Science      Convo                          3.21
                                News+                          3.54
                                Science                        3.46
Llama 3.1 (0-shot) zero-shot    Convo                          3.31
                                News+                          3.41
                                Science                        3.52
PRIMERA            Convo        Convo                          1.52
                                News+                          2.08
                                Science                        1.95
                   News+        Convo                          1.53
                                News+                          2.17
                                Science                        1.96
                   Science      Convo                          1.49
                                News+                          2.07
                                Science                        1.98
SummN              Convo        Convo                          2.50
                                News+                          2.64
                                Science                        2.36
                   News+        Convo                          1.58
                                News+                          2.28
                                Science                        1.54
                   Science      Convo                          1.21
                                News+                          2.04
                                Science                        1.45
ground_truth       Convo        Convo                          3.06
                   News+        News+                          3.16
                   Science      Science                        1.86

                                             unieval_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                     0.70
                                News+                     0.51
                                Science                   0.61
                   News+        Convo                     0.75
                                News+                     0.80
                                Science                   0.70
                   Science      Convo                     0.26
                                News+                     0.26
                                Science                   0.49
Llama 3.1          Convo        Convo                     0.95
                                News+                     0.92
                                Science                   0.91
                   News+        Convo                     0.94
                                News+                     0.92
                                Science                   0.92
                   Science      Convo                     0.94
                                News+                     0.94
                                Science                   0.91
Llama 3.1 (0-shot) zero-shot    Convo                     0.94
                                News+                     0.93
                                Science                   0.93
PRIMERA            Convo        Convo                     0.40
                                News+                     0.41
                                Science                   0.61
                   News+        Convo                     0.40
                                News+                     0.43
                                Science                   0.65
                   Science      Convo                     0.41
                                News+                     0.44
                                Science                   0.62
SummN              Convo        Convo                     0.72
                                News+                     0.64
                                Science                   0.72
                   News+        Convo                     0.71
                                News+                     0.78
                                Science                   0.67
                   Science      Convo                     0.33
                                News+                     0.33
                                Science                   0.49
ground_truth       Convo        Convo                     0.99
                   News+        News+                     0.99
                   Science      Science                   0.99

                                             prometheus_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                        2.52
                                News+                        2.08
                                Science                      2.27
                   News+        Convo                        1.97
                                News+                        2.72
                                Science                      2.13
                   Science      Convo                        1.34
                                News+                        2.10
                                Science                      1.84
Llama 3.1          Convo        Convo                        3.47
                                News+                        3.64
                                Science                      3.58
                   News+        Convo                        3.43
                                News+                        3.59
                                Science                      3.61
                   Science      Convo                        3.47
                                News+                        3.64
                                Science                      3.53
Llama 3.1 (0-shot) zero-shot    Convo                        3.44
                                News+                        3.57
                                Science                      3.47
PRIMERA            Convo        Convo                        1.77
                                News+                        2.38
                                Science                      2.38
                   News+        Convo                        1.76
                                News+                        2.37
                                Science                      2.40
                   Science      Convo                        1.77
                                News+                        2.33
                                Science                      2.39
SummN              Convo        Convo                        2.71
                                News+                        2.75
                                Science                      2.48
                   News+        Convo                        1.95
                                News+                        2.58
                                Science                      2.15
                   Science      Convo                        1.26
                                News+                        2.36
                                Science                      1.71
ground_truth       Convo        Convo                        3.23
                   News+        News+                        3.39
                   Science      Science                      2.78

                                             rouge_rouge1  rouge_rougeLsum  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                0.31             0.21
                                News+                0.24             0.14
                                Science              0.23             0.14
                   News+        Convo                0.23             0.13
                                News+                0.46             0.24
                                Science              0.23             0.13
                   Science      Convo                0.22             0.15
                                News+                0.30             0.16
                                Science              0.27             0.16
Llama 3.1          Convo        Convo                0.21             0.15
                                News+                0.40             0.21
                                Science              0.24             0.15
                   News+        Convo                0.22             0.15
                                News+                0.40             0.21
                                Science              0.24             0.15
                   Science      Convo                0.22             0.15
                                News+                0.40             0.22
                                Science              0.24             0.15
Llama 3.1 (0-shot) zero-shot    Convo                0.22             0.15
                                News+                0.41             0.22
                                Science              0.24             0.16
PRIMERA            Convo        Convo                0.19             0.11
                                News+                0.38             0.18
                                Science              0.23             0.12
                   News+        Convo                0.19             0.11
                                News+                0.37             0.18
                                Science              0.23             0.12
                   Science      Convo                0.19             0.11
                                News+                0.38             0.18
                                Science              0.22             0.12
SummN              Convo        Convo                0.33             0.21
                                News+                0.23             0.14
                                Science              0.21             0.13
                   News+        Convo                0.22             0.13
                                News+                0.46             0.23
                                Science              0.21             0.12
                   Science      Convo                0.21             0.14
                                News+                0.31             0.17
                                Science              0.26             0.15
ground_truth       Convo        Convo               -1.00            -1.00
                   News+        News+               -1.00            -1.00
                   Science      Science             -1.00            -1.00

                                             moverscore  unieval_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo              0.06             0.91
                                News+              0.00             0.91
                                Science            0.02             0.91
                   News+        Convo              0.01             0.70
                                News+              0.20             0.74
                                Science            0.04             0.81
                   Science      Convo             -0.01             0.60
                                News+              0.04             0.64
                                Science            0.03             0.68
Llama 3.1          Convo        Convo              0.05             0.93
                                News+              0.16             0.94
                                Science            0.08             0.94
                   News+        Convo              0.05             0.94
                                News+              0.16             0.94
                                Science            0.09             0.93
                   Science      Convo              0.06             0.93
                                News+              0.16             0.95
                                Science            0.08             0.93
Llama 3.1 (0-shot) zero-shot    Convo              0.05             0.93
                                News+              0.16             0.94
                                Science            0.08             0.93
PRIMERA            Convo        Convo             -0.01             0.64
                                News+              0.13             0.63
                                Science            0.06             0.79
                   News+        Convo             -0.01             0.67
                                News+              0.12             0.63
                                Science            0.06             0.82
                   Science      Convo             -0.02             0.64
                                News+              0.13             0.62
                                Science            0.05             0.77
SummN              Convo        Convo              0.09             0.91

In [5]:
a = results_df[results_df.model_type=="PRIMERA"].set_index(["model_type", "train_domain", "test_domain"]).sort_index()
a.transpose()

model_type             PRIMERA                                            \
train_domain             Convo               News+               Science
test_domain              Convo News+ Science Convo News+ Science   Convo
unieval_factuality        0.81  0.83    0.84  0.82  0.78    0.82    0.80
prometheus_factuality     1.41  1.97    1.96  1.34  2.01    2.03    1.43
prometheus_consistency    1.52  2.08    1.95  1.53  2.17    1.96    1.49
unieval_relevance         0.40  0.41    0.61  0.40  0.43    0.65    0.41
prometheus_relevance      1.77  2.38    2.38  1.76  2.37    2.40    1.77
rouge_rouge1              0.19  0.38    0.23  0.19  0.37    0.23    0.19
rouge_rougeLsum           0.11  0.18    0.12  0.11  0.18    0.12    0.11
moverscore               -0.01  0.13    0.06 -0.01  0.12    0.06   -0.02
unieval_fluency           0.64  0.63    0.79  0.67  0.63    0.82    0.64
prometheus_fluency        1.31  2.04    1.82  1.36  1.94    1.92    1.34
unieval_coherence         0.75  0.71    0.73  0.72  0.65    0.74    0.67
prometheus_coherence      1.22  1.94    1.79  1.26  1.86    1.83    1.28
compression_sentence     -5.10 -1.99   -2.23 -5.29 -2.33   -2.40   -4.46
compression_token        -3.93 -1.28   -1.59 -3.17 -1.38   -1.61   -2.61
prometheus_coverage       1.54  2.01    1.94  1.52  1.94    2.04    1.58

model_type
train_domain
test_domain            News+ Science
unieval_factuality      0.78    0.84
prometheus_factuality   1.96    1.96
prometheus_consistency  2.07    1.98
unieval_relevance       0.44    0.62
prometheus_relevance    2.33    2.39
rouge_rouge1            0.38    0.22
rouge_rougeLsum         0.18    0.12
moverscore              0.13    0.05
unieval_fluency         0.62    0.77
prometheus_fluency      1.95    1.75
unieval_coherence       0.68    0.74
prometheus_coherence    1.94    1.80
compression_sentence   -2.42   -2.42
compression_token      -1.51   -1.67
prometheus_coverage     1.99    2.00

# Q: How well is each model trained _on its domain_?

In [6]:
# Limit to models where the model is trained and tested on the same domain
same_domain_analysis = results_df[
    results_df.apply(lambda x: x.train_domain==x.test_domain, axis="columns")
].sort_values(by=["train_domain", "test_domain"])
same_domain_analysis = same_domain_analysis.loc[:, ["train_domain", "test_domain", "model_type"]+wanted_metrics]

same_domain_performance_dict = same_domain_analysis.set_index(["train_domain", "model_type"])[wanted_metrics].to_dict(orient="index")
same_domain_performance_dict

{('Convo', 'ground_truth'): {'unieval_factuality': 0.7088183022881179,
  'prometheus_factuality': 3.07,
  'prometheus_consistency': 3.06,
  'unieval_relevance': 0.9873195765236236,
  'prometheus_relevance': 3.23,
  'rouge_rouge1': -1.0,
  'rouge_rougeLsum': -1.0,
  'moverscore': -1.0,
  'unieval_fluency': 0.8947679057879945,
  'prometheus_fluency': 3.3,
  'unieval_coherence': 0.7266774421924654,
  'prometheus_coherence': 3.39,
  'compression_sentence': 0.899399009312196,
  'compression_token': 0.8506645011781512,
  'prometheus_coverage': 2.57},
 ('Convo', 'PRIMERA'): {'unieval_factuality': 0.8115564810063642,
  'prometheus_factuality': 1.41,
  'prometheus_consistency': 1.52,
  'unieval_relevance': 0.40201506659159114,
  'prometheus_relevance': 1.77,
  'rouge_rouge1': 0.18966978955204078,
  'rouge_rougeLsum': 0.10710250375191789,
  'moverscore': -0.014320818879059666,
  'unieval_fluency': 0.6432680571368042,
  'prometheus_fluency': 1.31,
  'unieval_coherence': 0.7488849508238488,
  'prometheus_coherence': 1.22,
  'compression_sentence': -5.101456590794826,
  'compression_token': -3.9263227000173506,
  'prometheus_coverage': 1.54},
 ('Convo', 'SummN'): {'unieval_factuality': 0.6583536458644644,
  'prometheus_factuality': 2.39,
  'prometheus_consistency': 2.5,
  'unieval_relevance': 0.7171789571418291,
  'prometheus_relevance': 2.71,
  'rouge_rouge1': 0.326509629035275,
  'rouge_rougeLsum': 0.2112373835130571,
  'moverscore': 0.08996136339347935,
  'unieval_fluency': 0.9078997126380198,
  'prometheus_fluency': 2.88,
  'unieval_coherence': 0.7112302347276298,
  'prometheus_coherence': 2.78,
  'compression_sentence': -10.81166666666667,
  'compression_token': -8.112211529429162,
  'prometheus_coverage': 2.18},
 ('Convo', 'ConvoSumm'): {'unieval_factuality': 0.640659595215039,
  'prometheus_factuality': 2.13,
  'prometheus_consistency': 2.39,
  'unieval_relevance': 0.7038211621316407,
  'prometheus_relevance': 2.52,
  'rouge_rouge1': 0.3107453771812775,
  'rouge_rougeLsum': 0.212665444995344,
  'moverscore': 0.0602550780555246,
  'unieval_fluency': 0.9053736660495955,
  'prometheus_fluency': 2.61,
  'unieval_coherence': 0.5918988386538738,
  'prometheus_coherence': 2.43,
  'compression_sentence': -12.401666666666667,
  'compression_token': -12.227228951576869,
  'prometheus_coverage': 1.97},
 ('Convo', 'Llama 3.1'): {'unieval_factuality': 0.8131412105064956,
  'prometheus_factuality': 3.09,
  'prometheus_consistency': 3.26,
  'unieval_relevance': 0.9460393288197035,
  'prometheus_relevance': 3.47,
  'rouge_rouge1': 0.21165449419239304,
  'rouge_rougeLsum': 0.14878113879759622,
  'moverscore': 0.05449570841272161,
  'unieval_fluency': 0.9277210830215753,
  'prometheus_fluency': 3.94,
  'unieval_coherence': 0.9633828185994041,
  'prometheus_coherence': 3.97,
  'compression_sentence': -3.6364900325279583,
  'compression_token': -1.3513898439591934,
  'prometheus_coverage': 2.95},
 ('News+', 'ground_truth'): {'unieval_factuality': 0.7287848676970501,
  'prometheus_factuality': 2.84,
  'prometheus_consistency': 3.16,
  'unieval_relevance': 0.9890378595984929,
  'prometheus_relevance': 3.39,
  'rouge_rouge1': -1.0,
  'rouge_rougeLsum': -1.0,
  'moverscore': 0.9999999998005012,
  'unieval_fluency': 0.7700314126642427,
  'prometheus_fluency': 2.7474747474747474,
  'unieval_coherence': 0.7377015071355261,
  'prometheus_coherence': 3.7,
  'compression_sentence': -1.1709446870638822,
  'compression_token': -1.1035415745800359,
  'prometheus_coverage': 2.69},
 ('News+', 'PRIMERA'): {'unieval_factuality': 0.7813195490798331,
  'prometheus_factuality': 2.01,
  'prometheus_consistency': 2.17,
  'unieval_relevance': 0.429450048243652,
  'prometheus_relevance': 2.37,
  'rouge_rouge1': 0.3701020626884345,
  'rouge_rougeLsum': 0.17842266181580033,
  'moverscore': 0.12134274272876862,
  'unieval_fluency': 0.6310111768521522,
  'prometheus_fluency': 1.94,
  'unieval_coherence': 0.6520954238853282,
  'prometheus_coherence': 1.86,
  'compression_sentence': -2.329924779468897,
  'compression_token': -1.376831651724781,
  'prometheus_coverage': 1.94},
 ('News+', 'SummN'): {'unieval_factuality': 0.7223422527771342,
  'prometheus_factuality': 2.22,
  'prometheus_consistency': 2.28,
  'unieval_relevance': 0.7848189817386216,
  'prometheus_relevance': 2.58,
  'rouge_rouge1': 0.4560600410464897,
  'rouge_rougeLsum': 0.23353535457116023,
  'moverscore': 0.19217935806406397,
  'unieval_fluency': 0.741506175499525,
  'prometheus_fluency': 2.48,
  'unieval_coherence': 0.8015953673209705,
  'prometheus_coherence': 2.76,
  'compression_sentence': -1.1806061030472796,
  'compression_token': -1.2335068441026023,
  'prometheus_coverage': 2.16},
 ('News+', 'ConvoSumm'): {'unieval_factuality': 0.7783237624298042,
  'prometheus_factuality': 2.39,
  'prometheus_consistency': 2.54,
  'unieval_relevance': 0.8013146991897413,
  'prometheus_relevance': 2.72,
  'rouge_rouge1': 0.45739665892896947,
  'rouge_rougeLsum': 0.2353538463751893,
  'moverscore': 0.19886831916532757,
  'unieval_fluency': 0.7410538537314413,
  'prometheus_fluency': 2.68,
  'unieval_coherence': 0.8442774236204191,
  'prometheus_coherence': 2.99,
  'compression_sentence': -1.3133591988077282,
  'compression_token': -1.4453698077933264,
  'prometheus_coverage': 2.28},
 ('News+', 'Llama 3.1'): {'unieval_factuality': 0.8735893775910426,
  'prometheus_factuality': 3.2,
  'prometheus_consistency': 3.47,
  'unieval_relevance': 0.9191190535890625,
  'prometheus_relevance': 3.59,
  'rouge_rouge1': 0.40025617340309366,
  'rouge_rougeLsum': 0.20971255162267993,
  'moverscore': 0.15925066470423435,
  'unieval_fluency': 0.9368375896341539,
  'prometheus_fluency': 4.04,
  'unieval_coherence': 0.9467131456695671,
  'prometheus_coherence': 3.93,
  'compression_sentence': -2.226480158730159,
  'compression_token': -1.7473329934670114,
  'prometheus_coverage': 2.96},
 ('Science', 'ground_truth'): {'unieval_factuality': 0.5546460158445465,
  'prometheus_factuality': 1.82,
  'prometheus_consistency': 1.86,
  'unieval_relevance': 0.9888476006639038,
  'prometheus_relevance': 2.78,
  'rouge_rouge1': -1.0,
  'rouge_rougeLsum': -1.0,
  'moverscore': -1.0,
  'unieval_fluency': 0.669562504501733,
  'prometheus_fluency': 1.53,
  'unieval_coherence': 0.44595380786485395,
  'prometheus_coherence': 1.51,
  'compression_sentence': -6.32463888888889,
  'compression_token': -5.625458636589965,
  'prometheus_coverage': 1.9},
 ('Science', 'PRIMERA'): {'unieval_factuality': 0.8408908138427438,
  'prometheus_factuality': 1.96,
  'prometheus_consistency': 1.98,
  'unieval_relevance': 0.6249840896208133,
  'prometheus_relevance': 2.39,
  'rouge_rouge1': 0.22406094188468528,
  'rouge_rougeLsum': 0.1209949166557578,
  'moverscore': 0.05363894424519011,
  'unieval_fluency': 0.7746605472055191,
  'prometheus_fluency': 1.75,
  'unieval_coherence': 0.7416738416188465,
  'prometheus_coherence': 1.8,
  'compression_sentence': -2.421704274672696,
  'compression_token': -1.6690720715679088,
  'prometheus_coverage': 2.0},
 ('Science', 'SummN'): {'unieval_factuality': 0.55755592041986,
  'prometheus_factuality': 1.46,
  'prometheus_consistency': 1.45,
  'unieval_relevance': 0.4905485848113073,
  'prometheus_relevance': 1.71,
  'rouge_rouge1': 0.26447505599292076,
  'rouge_rougeLsum': 0.15428995250359004,
  'moverscore': 0.026751003084796512,
  'unieval_fluency': 0.6839843380656185,
  'prometheus_fluency': 1.41,
  'unieval_coherence': 0.3899186941340373,
  'prometheus_coherence': 1.4,
  'compression_sentence': -3.9881284826284826,
  'compression_token': -4.695405980875687,
  'prometheus_coverage': 1.5},
 ('Science', 'ConvoSumm'): {'unieval_factuality': 0.6474810323495521,
  'prometheus_factuality': 1.61,
  'prometheus_consistency': 1.49,
  'unieval_relevance': 0.4902085290006365,
  'prometheus_relevance': 1.84,
  'rouge_rouge1': 0.269789839482931,
  'rouge_rougeLsum': 0.15840737749212283,
  'moverscore': 0.034695989039083434,
  'unieval_fluency': 0.6787635389357702,
  'prometheus_fluency': 1.6,
  'unieval_coherence': 0.3504087520182354,
  'prometheus_coherence': 1.51,
  'compression_sentence': -4.905978021978022,
  'compression_token': -6.821297877632365,
  'prometheus_coverage': 1.53},
 ('Science', 'Llama 3.1'): {'unieval_factuality': 0.8760694859126186,
  'prometheus_factuality': 3.4,
  'prometheus_consistency': 3.46,
  'unieval_relevance': 0.9144757570653094,
  'prometheus_relevance': 3.53,
  'rouge_rouge1': 0.24047558602503735,
  'rouge_rougeLsum': 0.15343963497613797,
  'moverscore': 0.08409259360861557,
  'unieval_fluency': 0.9349588464626325,
  'prometheus_fluency': 3.94,
  'unieval_coherence': 0.9721574221868964,
  'prometheus_coherence': 3.95,
  'compression_sentence': -1.3764918938691317,
  'compression_token': -1.293327854307154,
  'prometheus_coverage': 3.17}}

In [7]:
a = same_domain_analysis.set_index(["model_type"]).sort_index()
print(a.to_csv())
a

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,Convo,0.640659595215039,2.13,2.39,0.7038211621316407,2.52,0.3107453771812775,0.212665444995344,0.0602550780555246,0.9053736660495955,2.61,0.5918988386538738,2.43,-12.401666666666667,-12.227228951576869,1.97
ConvoSumm,News+,News+,0.7783237624298042,2.39,2.54,0.8013146991897413,2.72,0.45739665892896947,0.2353538463751893,0.19886831916532757,0.7410538537314413,2.68,0.8442774236204191,2.99,-1.3133591988077282,-1.4453698077933264,2.28
ConvoSumm,Science,Science,0.6474810323495521,1.61,1.49,0.4902085290006365,1.84,0.269789839482931,0.15840737749212283,0.034695989039083434,0.6787635389357702,1.6,0.3504087520182354,1.51,-4.905978021978022,-6.821297877632365,1.53
Llama 3.1,Convo,Convo,0.8131412105064956,3.09,3.26,0.9460393288197035,3.47,0.21165449419239304,0.14878113879759622,0.05449570841272161,0.9277210830215753,3.94,0.9633828185994041,3.97,-3.6364900325279583,-1.3513898439591934,2.95
Llama 3.1,News+,News+,0.8735893775910426,3.2,3.47,0.9191190535890625,3.59,0.40025617340309366,0.20971255162267993,0.15925066470423435,0.9368375896341539,4.04,0.9467131456695671,3.93,-2.226480158730159,-1.7473329934670114,2.96
Llama 3.1,Science,Science,0.8760694859126186,3.4,3.46,0.9144757570653094,3.53,0.24047558602503735,0.15343963497613797,0.08409259360861557,0.9349588464626325,3.94,0.9721574221868964,3.95,-1.3764918938691317,-1.293327854307154,3.17
PRIMERA,Convo,Convo,0.8115564810063642,1.41,1.52,0.40201506659159114,1.77,0.18966978955204078,0.10710250375191789,-0.014320818879059666,0.6432680571368042,1.31,0.7488849508238488,1.22,-5.101456590794826,-3.9263227000173506,1.54
PRIMERA,News+,News+,0.7813195490798331,2.01,2.17,0.429450048243652,2.37,0.3701020626884345,0.17842266181580033,0.12134274272876862,0.6310111768521522,1.94,0.6520954238853282,1.86,-2.329924779468897,-1.376831651724781,1.94
PRIMERA,Science,Science,0.8408908138427438,1.96,1.98,0.6249840896208133,2.39,0.22406094188468528,0.1209949166557578,0.05363894424519011,0.7746605472055191,1.75,0.7416738416188465,1.8,-2.421704274672696,-1.6690720715679088,2.0
SummN,Convo,Convo,0.6583536458644644,2.39,2.5,0.7171789571418291,2.71,0.326509629035275,0.2112373835130571,0.08996136339347935,0.9078997126380198,2.88,0.7112302347276298,2.78,-10.81166666666667,-8.112211529429162,2.18
SummN,News+,News+,0.7223422527771342,2.22,2.28,0.7848189817386216,2.58,0.4560600410464897,0.23353535457116023,0.19217935806406397,0.741506175499525,2.48,0.8015953673209705,2.76,-1.1806061030472796,-1.2335068441026023,2.16
SummN,Science,Science,0.55755592041986,1.46,1.45,0.4905485848113073,1.71,0.26447505599292076,0.15428995250359004,0.026751003084796512,0.6839843380656185,1.41,0.3899186941340373,1.4,-3.9881284826284826,-4.695405980875687,1.5
ground_truth,Convo,Convo,0.7088183022881179,3.07,3.06,0.9873195765236236,3.23,-1.0,-1.0,-1.0,0.8947679057879945,3.3,0.7266774421924654,3.39,0.899399009312196,0.8506645011781512,2.57
ground_truth,News+,News+,0.7287848676970501,2.84,3.16,0.9890378595984929,3.39,-1.0,-1.0,0.9999999998005012,0.7700314126642427,2.7474747474747474,0.7377015071355261,3.7,-1.1709446870638822,-1.1035415745800359,2.69
ground_truth,Science,Science,0.5546460158445465,1.82,1.86,0.9888476006639038,2.78,-1.0,-1.0,-1.0,0.669562504501733,1.53,0.44595380786485395,1.51,-6.32463888888889,-5.625458636589965,1.9

,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
model_type,,,,,,,,,,,,,,,,,
ConvoSumm,Convo,Convo,0.64,2.13,2.39,0.70,2.52,0.31,0.21,0.06,0.91,2.61,0.59,2.43,-12.40,-12.23,1.97
ConvoSumm,News+,News+,0.78,2.39,2.54,0.80,2.72,0.46,0.24,0.20,0.74,2.68,0.84,2.99,-1.31,-1.45,2.28
ConvoSumm,Science,Science,0.65,1.61,1.49,0.49,1.84,0.27,0.16,0.03,0.68,1.60,0.35,1.51,-4.91,-6.82,1.53
Llama 3.1,Convo,Convo,0.81,3.09,3.26,0.95,3.47,0.21,0.15,0.05,0.93,3.94,0.96,3.97,-3.64,-1.35,2.95
Llama 3.1,News+,News+,0.87,3.20,3.47,0.92,3.59,0.40,0.21,0.16,0.94,4.04,0.95,3.93,-2.23,-1.75,2.96
Llama 3.1,Science,Science,0.88,3.40,3.46,0.91,3.53,0.24,0.15,0.08,0.93,3.94,0.97,3.95,-1.38,-1.29,3.17
PRIMERA,Convo,Convo,0.81,1.41,1.52,0.40,1.77,0.19,0.11,-0.01,0.64,1.31,0.75,1.22,-5.10,-3.93,1.54
PRIMERA,News+,News+,0.78,2.01,2.17,0.43,2.37,0.37,0.18,0.12,0.63,1.94,0.65,1.86,-2.33,-1.38,1.94
PRIMERA,Science,Science,0.84,1.96,1.98,0.62,2.39,0.22,0.12,0.05,0.77,1.75,0.74,1.80,-2.42,-1.67,2.00
SummN,Convo,Convo,0.66,2.39,2.50,0.72,2.71,0.33,0.21,0.09,0.91,2.88,0.71,2.78,-10.81,-8.11,2.18
SummN,News+,News+,0.72,2.22,2.28,0.78,2.58,0.46,0.23,0.19,0.74,2.48,0.80,2.76,-1.18,-1.23,2.16
SummN,Science,Science,0.56,1.46,1.45,0.49,1.71,0.26,0.15,0.03,0.68,1.41,0.39,1.40,-3.99,-4.70,1.50
ground_truth,Convo,Convo,0.71,3.07,3.06,0.99,3.23,-1.00,-1.00,-1.00,0.89,3.30,0.73,3.39,0.90,0.85,2.57
ground_truth,News+,News+,0.73,2.84,3.16,0.99,3.39,-1.00,-1.00,1.00,0.77,2.75,0.74,3.70,-1.17,-1.10,2.69
ground_truth,Science,Science,0.55,1.82,1.86,0.99,2.78,-1.00,-1.00,-1.00,0.67,1.53,0.45,1.51,-6.32,-5.63,1.90

In [8]:
a = same_domain_analysis.groupby(["model_type"]).mean(numeric_only=True).to_csv(float_format='%.2f')
print(a)

model_type,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,0.69,2.04,2.14,0.67,2.36,0.35,0.20,0.10,0.78,2.30,0.60,2.31,-6.21,-6.83,1.93
Llama 3.1,0.85,3.23,3.40,0.93,3.53,0.28,0.17,0.10,0.93,3.97,0.96,3.95,-2.41,-1.46,3.03
PRIMERA,0.81,1.79,1.89,0.49,2.18,0.26,0.14,0.05,0.68,1.67,0.71,1.63,-3.28,-2.32,1.83
SummN,0.65,2.02,2.08,0.66,2.33,0.35,0.20,0.10,0.78,2.26,0.63,2.31,-5.33,-4.68,1.95
ground_truth,0.66,2.58,2.69,0.99,3.13,-1.00,-1.00,-0.33,0.78,2.53,0.64,2.87,-2.20,-1.96,2.39

In [9]:
a = same_domain_analysis[same_domain_analysis.model_type!='ground_truth'].groupby(["train_domain"]).mean(numeric_only=True)
print(a.to_csv(float_format='%.2f'))
a

train_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,0.73,2.25,2.42,0.69,2.62,0.26,0.17,0.05,0.85,2.69,0.75,2.60,-7.99,-6.40,2.16
News+,0.79,2.46,2.62,0.73,2.81,0.42,0.21,0.17,0.76,2.79,0.81,2.89,-1.76,-1.45,2.33
Science,0.73,2.11,2.09,0.63,2.37,0.25,0.15,0.05,0.77,2.17,0.61,2.17,-3.17,-3.62,2.05

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
train_domain,,,,,,,,,,,,,,,
Convo,0.73,2.25,2.42,0.69,2.62,0.26,0.17,0.05,0.85,2.69,0.75,2.60,-7.99,-6.40,2.16
News+,0.79,2.46,2.62,0.73,2.81,0.42,0.21,0.17,0.76,2.79,0.81,2.89,-1.76,-1.45,2.33
Science,0.73,2.11,2.09,0.63,2.37,0.25,0.15,0.05,0.77,2.17,0.61,2.17,-3.17,-3.62,2.05

# Q: Which train domain transfers the best to other domains?

Limit to models that are trained and tested on _different_ domains. Also, focus on performance _loss_ versus absolute performance.

In [10]:
cross_performance = results_df[results_df.train_domain!=results_df.test_domain].groupby(["model_type", "train_domain", "test_domain"]).mean(numeric_only=True)
print(cross_performance.to_csv())
cross_performance

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,News+,0.7465658013353306,1.83,1.9,0.5056588471175113,2.08,0.23731259476435618,0.13813155329140192,0.00041119504713410526,0.9103890092792085,2.02,0.572873641507687,1.94,-4.307876984126983,-7.537310613458084,1.68
ConvoSumm,Convo,Science,0.673443167817001,1.95,1.97,0.6132739132713839,2.27,0.22975463311411906,0.1391126410290911,0.020910987602955688,0.9134477122673242,2.22,0.583611342426411,2.03,-5.167416666666667,-9.232939385777877,1.76
ConvoSumm,News+,Convo,0.680962832314046,1.59,1.78,0.7516980356333706,1.97,0.2279826399002288,0.13159840990020666,0.008295298076173978,0.6983868840575984,1.72,0.7796710883409483,1.74,-3.6184218583703878,-2.514540225447379,1.77
ConvoSumm,News+,Science,0.6893504529679428,1.77,1.76,0.6990364432635213,2.13,0.23332449107183925,0.1323775823229984,0.03534702368884793,0.8110280363359399,1.79,0.7091506657803963,1.87,-2.3072397186147184,-2.3152274034171296,1.89
ConvoSumm,Science,Convo,0.4429654249592991,1.22,1.26,0.2553478983500462,1.34,0.2223018748378942,0.14869600494450905,-0.00888279426005587,0.5977194750924377,1.27,0.2641887113444974,1.29,-9.320327628254098,-7.775001059250265,1.25
ConvoSumm,Science,News+,0.6577273407978487,1.81,1.87,0.25748063589908216,2.1,0.300171927870387,0.16154146390520277,0.0381330894246408,0.6427885757333687,1.65,0.29568013135391735,1.7,-3.3714724050459335,-3.9944912480964385,1.69
Llama 3.1,Convo,News+,0.8719929173397903,3.24,3.56,0.919863631393829,3.64,0.4033453311479864,0.21294830399070316,0.16311737883347138,0.9429098228973358,4.11,0.9469958640069224,3.98,-2.3119404761904763,-1.7895318174781578,3.02
Llama 3.1,Convo,Science,0.8815504719529145,3.32,3.47,0.9088698359265531,3.58,0.24424992484298802,0.15458723720120093,0.08490742175953421,0.9379827800584059,4.06,0.9672694434067556,4.0,-1.392640292310403,-1.2911753167043316,3.23
Llama 3.1,News+,Convo,0.824167875497006,3.01,3.23,0.9394790997459792,3.43,0.21965777163354594,0.1524962048064859,0.052276181694833584,0.9364201661803482,3.99,0.9627046308298701,3.92,-3.879412874162874,-1.3611998835007206,2.96
Llama 3.1,News+,Science,0.8815323922481761,3.38,3.45,0.9245229825044947,3.61,0.24046060138185357,0.154160408920743,0.08585795874385621,0.931680015597034,4.03,0.9811759831162806,4.0,-1.2970981564588375,-1.2613237380390134,3.19
Llama 3.1,Science,Convo,0.8155571180152846,3.17,3.21,0.9409051505010666,3.47,0.21618052028673024,0.14696427529093947,0.058114867999678216,0.9262702322636313,3.94,0.9583841458074059,3.92,-3.9976491772847034,-1.4565185959994822,2.91
Llama 3.1,Science,News+,0.8693838400070554,3.25,3.54,0.936716306919422,3.64,0.40009998095804145,0.2156716161721144,0.16379031431099925,0.9480128543743462,4.07,0.9481494886048887,3.98,-2.1536248196248193,-1.6875463324912854,2.93
Llama 3.1 (0-shot),zero-shot,Convo,0.8250142829523301,3.12,3.31,0.9394364497773977,3.44,0.22034381873817646,0.14973785724753752,0.05422778647512281,0.9267180338304345,4.01,0.9558842242918476,3.87,-3.7415490325034435,-1.3979605644709427,2.79
Llama 3.1 (0-shot),zero-shot,News+,0.8829222491886388,3.26,3.41,0.9257310587100824,3.57,0.40544334997414544,0.21570917511322596,0.1646476956375993,0.9435611538639962,4.04,0.9420197609167295,4.0,-2.074563492063492,-1.6354039279581456,3.02
Llama 3.1 (0-shot),zero-shot,Science,0.8745751852072919,3.42,3.515151515151515,0.9268242209393963,3.47,0.24485781987449962,0.15865999375632467,0.08450220360797761,0.9323130662283953,4.06,0.9766481752640443,3.96,-1.3845339398733363,-1.2971537950988932,3.29
PRIMERA,Convo,News+,0.8311949417261922,1.97,2.08,0.4091609139985816,2.38,0.37630373692149066,0.18498184488904681,0.12967598903511643,0.6290581704995314,2.04,0.7082097155927862,1.94,-1.9926221756399771,-1.2842937826622505,2.01
PRIMERA,Convo,Science,0.8444237611655514,1.96,1.95,0.6135893680403433,2.38,0.22743192727507414,0.12406581699611988,0.055759484481686356,0.7923355517573727,1.82,0.7322852838377394,1.79,-2.233668696804011,-1.5933610747155673,1.94
PRIMERA,News+,Convo,0.8239607377283168,1.34,1.53,0.3997455122074125,1.76,0.1904551184447702,0.10879716028621593,-0.013851534868470492,0.6690914716517772,1.36,0.7247650468757568,1.2626262626262625,-5.289399269504146,-3.167923052485298,1.52
PRIMERA,News+,Science,0.8191612045477661,2.03,1.96,0.6459761419128054,2.4,0.2271323986571124,0.12299516159337909,0.05553630332937768,0.8203282262179714,1.92,0.7385058005677777,1.83,-2.3994925590461498,-1.6087686753622945,2.04
PRIMERA,Science,Convo,0.8009853653591018,1.43,1.49,0.411451901276191,1.77,0.18509501017603827,0.10649054835504619,-0.01577802457811055,0.6420550965877705,1.34,0.6718008916888037,1.28,-4.458051600250855,-2.6070086149401313,1.58
PRIMERA,Science,News+,0.7844635993357713,1.96,2.07,0.43859641369139113,2.33,0.37933046860436875,0.18086148680407885,0.12803423686910492,0.6204918650979208,1.95,0.684925101323636,1.94,-2.4211462638238954,-1.5122533888491079,1.99
SummN,Convo,News+,0.8952955281812387,2.71,2.64,0.6373384405754013,2.75,0.22754913618689362,0.13989396831293374,0.00602953298358214,0.8879954320830145,2.92,0.8151406696798753,2.74,-5.468214285714287,-8.283106285407973,2.18
SummN,Convo,Science,0.7656264267357129,2.51,2.36,0.7150198750916534,2.48,0.20648578058413758,0.12962729202557324,0.013790525424905527,0.9233837308531134,2.61,0.8785325692914497,2.27,-7.7225,-11.27928394526358,1.99
SummN,News+,Convo,0.6665089225538875,1.44,1.58,0.7081035782483254,1.95,0.21508962744404297,0.12507391096381837,0.0019542274475522793,0.7025293347923232,1.74,0.7318385010766777,1.58,-3.4464917680358864,-2.1581308538764237,1.67
SummN,News+,Science,0.6390290958223914,1.57,1.54,0.6667653998798962,2.15,0.21338247280193762,0.12114900070848977,0.032083123525857134,0.7729335828869681,1.63,0.6757592338813629,1.68,-1.3890619094957328,-1.2647613560183597,1.83
SummN,Science,Convo,0.39459658147714327,1.13,1.21,0.3302783239609984,1.26,0.20571184912255835,0.1397251648994163,-0.03503168687718606,0.6278806172493255,1.37,0.33213716253547526,1.25,-6.517196608946611,-4.141931051912095,1.26
SummN,Science,News+,0.6528492329722675,1.95,2.04,0.33039889642598685,2.36,0.30542111598874755,0.16837784332441622,0.04045668117205634,0.6885207130179722,2.05,0.3488666092559714,2.07,-3.138320851534087,-3.5766910846134152,1.9

                                             unieval_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                      0.75
                                Science                    0.67
                   News+        Convo                      0.68
                                Science                    0.69
                   Science      Convo                      0.44
                                News+                      0.66
Llama 3.1          Convo        News+                      0.87
                                Science                    0.88
                   News+        Convo                      0.82
                                Science                    0.88
                   Science      Convo                      0.82
                                News+                      0.87
Llama 3.1 (0-shot) zero-shot    Convo                      0.83
                                News+                      0.88
                                Science                    0.87
PRIMERA            Convo        News+                      0.83
                                Science                    0.84
                   News+        Convo                      0.82
                                Science                    0.82
                   Science      Convo                      0.80
                                News+                      0.78
SummN              Convo        News+                      0.90
                                Science                    0.77
                   News+        Convo                      0.67
                                Science                    0.64
                   Science      Convo                      0.39
                                News+                      0.65

                                             prometheus_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                         1.83
                                Science                       1.95
                   News+        Convo                         1.59
                                Science                       1.77
                   Science      Convo                         1.22
                                News+                         1.81
Llama 3.1          Convo        News+                         3.24
                                Science                       3.32
                   News+        Convo                         3.01
                                Science                       3.38
                   Science      Convo                         3.17
                                News+                         3.25
Llama 3.1 (0-shot) zero-shot    Convo                         3.12
                                News+                         3.26
                                Science                       3.42
PRIMERA            Convo        News+                         1.97
                                Science                       1.96
                   News+        Convo                         1.34
                                Science                       2.03
                   Science      Convo                         1.43
                                News+                         1.96
SummN              Convo        News+                         2.71
                                Science                       2.51
                   News+        Convo                         1.44
                                Science                       1.57
                   Science      Convo                         1.13
                                News+                         1.95

                                             prometheus_consistency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                          1.90
                                Science                        1.97
                   News+        Convo                          1.78
                                Science                        1.76
                   Science      Convo                          1.26
                                News+                          1.87
Llama 3.1          Convo        News+                          3.56
                                Science                        3.47
                   News+        Convo                          3.23
                                Science                        3.45
                   Science      Convo                          3.21
                                News+                          3.54
Llama 3.1 (0-shot) zero-shot    Convo                          3.31
                                News+                          3.41
                                Science                        3.52
PRIMERA            Convo        News+                          2.08
                                Science                        1.95
                   News+        Convo                          1.53
                                Science                        1.96
                   Science      Convo                          1.49
                                News+                          2.07
SummN              Convo        News+                          2.64
                                Science                        2.36
                   News+        Convo                          1.58
                                Science                        1.54
                   Science      Convo                          1.21
                                News+                          2.04

                                             unieval_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     0.51
                                Science                   0.61
                   News+        Convo                     0.75
                                Science                   0.70
                   Science      Convo                     0.26
                                News+                     0.26
Llama 3.1          Convo        News+                     0.92
                                Science                   0.91
                   News+        Convo                     0.94
                                Science                   0.92
                   Science      Convo                     0.94
                                News+                     0.94
Llama 3.1 (0-shot) zero-shot    Convo                     0.94
                                News+                     0.93
                                Science                   0.93
PRIMERA            Convo        News+                     0.41
                                Science                   0.61
                   News+        Convo                     0.40
                                Science                   0.65
                   Science      Convo                     0.41
                                News+                     0.44
SummN              Convo        News+                     0.64
                                Science                   0.72
                   News+        Convo                     0.71
                                Science                   0.67
                   Science      Convo                     0.33
                                News+                     0.33

                                             prometheus_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                        2.08
                                Science                      2.27
                   News+        Convo                        1.97
                                Science                      2.13
                   Science      Convo                        1.34
                                News+                        2.10
Llama 3.1          Convo        News+                        3.64
                                Science                      3.58
                   News+        Convo                        3.43
                                Science                      3.61
                   Science      Convo                        3.47
                                News+                        3.64
Llama 3.1 (0-shot) zero-shot    Convo                        3.44
                                News+                        3.57
                                Science                      3.47
PRIMERA            Convo        News+                        2.38
                                Science                      2.38
                   News+        Convo                        1.76
                                Science                      2.40
                   Science      Convo                        1.77
                                News+                        2.33
SummN              Convo        News+                        2.75
                                Science                      2.48
                   News+        Convo                        1.95
                                Science                      2.15
                   Science      Convo                        1.26
                                News+                        2.36

                                             rouge_rouge1  rouge_rougeLsum  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                0.24             0.14
                                Science              0.23             0.14
                   News+        Convo                0.23             0.13
                                Science              0.23             0.13
                   Science      Convo                0.22             0.15
                                News+                0.30             0.16
Llama 3.1          Convo        News+                0.40             0.21
                                Science              0.24             0.15
                   News+        Convo                0.22             0.15
                                Science              0.24             0.15
                   Science      Convo                0.22             0.15
                                News+                0.40             0.22
Llama 3.1 (0-shot) zero-shot    Convo                0.22             0.15
                                News+                0.41             0.22
                                Science              0.24             0.16
PRIMERA            Convo        News+                0.38             0.18
                                Science              0.23             0.12
                   News+        Convo                0.19             0.11
                                Science              0.23             0.12
                   Science      Convo                0.19             0.11
                                News+                0.38             0.18
SummN              Convo        News+                0.23             0.14
                                Science              0.21             0.13
                   News+        Convo                0.22             0.13
                                Science              0.21             0.12
                   Science      Convo                0.21             0.14
                                News+                0.31             0.17

                                             moverscore  unieval_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+              0.00             0.91
                                Science            0.02             0.91
                   News+        Convo              0.01             0.70
                                Science            0.04             0.81
                   Science      Convo             -0.01             0.60
                                News+              0.04             0.64
Llama 3.1          Convo        News+              0.16             0.94
                                Science            0.08             0.94
                   News+        Convo              0.05             0.94
                                Science            0.09             0.93
                   Science      Convo              0.06             0.93
                                News+              0.16             0.95
Llama 3.1 (0-shot) zero-shot    Convo              0.05             0.93
                                News+              0.16             0.94
                                Science            0.08             0.93
PRIMERA            Convo        News+              0.13             0.63
                                Science            0.06             0.79
                   News+        Convo             -0.01             0.67
                                Science            0.06             0.82
                   Science      Convo             -0.02             0.64
                                News+              0.13             0.62
SummN              Convo        News+              0.01             0.89
                                Science            0.01             0.92
                   News+        Convo              0.00             0.70
                                Science            0.03             0.77
                   Science      Convo             -0.04             0.63
                                News+              0.04             0.69

                                             prometheus_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                      2.02
                                Science                    2.22
                   News+        Convo                      1.72
                                Science                    1.79
                   Science      Convo                      1.27
                                News+                      1.65
Llama 3.1          Convo        News+                      4.11
                                Science                    4.06
                   News+        Convo                      3.99
                                Science                    4.03
                   Science      Convo                      3.94
                                News+                      4.07
Llama 3.1 (0-shot) zero-shot    Convo                      4.01
                                News+                      4.04
                                Science                    4.06
PRIMERA            Convo        News+                      2.04
                                Science                    1.82
                   News+        Convo                      1.36
                                Science                    1.92
                   Science      Convo                      1.34
                                News+                      1.95
SummN              Convo        News+                      2.92
                                Science                    2.61
                   News+        Convo                      1.74
                                Science                    1.63
                   Science      Convo                      1.37
                                News+                      2.05

                                             unieval_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     0.57
                                Science                   0.58
                   News+        Convo                     0.78
                                Science                   0.71
                   Science      Convo                     0.26
                                News+                     0.30
Llama 3.1          Convo        News+                     0.95
                                Science                   0.97
                   News+        Convo                     0.96
                                Science                   0.98
                   Science      Convo                     0.96
                                News+                     0.95
Llama 3.1 (0-shot) zero-shot    Convo                     0.96
                                News+                     0.94
                                Science                   0.98
PRIMERA            Convo        News+                     0.71
                                Science                   0.73
                   News+        Convo                     0.72
                                Science                   0.74
                   Science      Convo                     0.67
                                News+                     0.68
SummN              Convo        News+                     0.82
                                Science                   0.88
                   News+        Convo                     0.73
                                Science                   0.68
                   Science      Convo                     0.33
                                News+                     0.35

                                             prometheus_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                        1.94
                                Science                      2.03
                   News+        Convo                        1.74
                                Science                      1.87
                   Science      Convo                        1.29
                                News+                        1.70
Llama 3.1          Convo        News+                        3.98
                                Science                      4.00
                   News+        Convo                        3.92
                                Science                      4.00
                   Science      Convo                        3.92
                                News+                        3.98
Llama 3.1 (0-shot) zero-shot    Convo                        3.87
                                News+                        4.00
                                Science                      3.96
PRIMERA            Convo        News+                        1.94
                                Science                      1.79
                   News+        Convo                        1.26
                                Science                      1.83
                   Science      Convo                        1.28
                                News+                        1.94
SummN              Convo        News+                        2.74
                                Science                      2.27
                   News+        Convo                        1.58
                                Science                      1.68
                   Science      Convo                        1.25
                                News+                        2.07

                                             compression_sentence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -4.31
                                Science                     -5.17
                   News+        Convo                       -3.62
                                Science                     -2.31
                   Science      Convo                       -9.32
                                News+                       -3.37
Llama 3.1          Convo        News+                       -2.31
                                Science                     -1.39
                   News+        Convo                       -3.88
                                Science                     -1.30

In [11]:
cross_performance.groupby(["train_domain", "test_domain"]).mean()

                          unieval_factuality  prometheus_factuality  \
train_domain test_domain
Convo        News+                      0.84                   2.44
             Science                    0.79                   2.44
News+        Convo                      0.75                   1.84
             Science                    0.76                   2.19
Science      Convo                      0.61                   1.74
             News+                      0.74                   2.24
zero-shot    Convo                      0.83                   3.12
             News+                      0.88                   3.26
             Science                    0.87                   3.42

                          prometheus_consistency  unieval_relevance  \
train_domain test_domain
Convo        News+                          2.54               0.62
             Science                        2.44               0.71
News+        Convo                          2.03               0.70
             Science                        2.18               0.73
Science      Convo                          1.79               0.48
             News+                          2.38               0.49
zero-shot    Convo                          3.31               0.94
             News+                          3.41               0.93
             Science                        3.52               0.93

                          prometheus_relevance  rouge_rouge1  rouge_rougeLsum  \
train_domain test_domain
Convo        News+                        2.71          0.31             0.17
             Science                      2.68          0.23             0.14
News+        Convo                        2.28          0.21             0.13
             Science                      2.57          0.23             0.13
Science      Convo                        1.96          0.21             0.14
             News+                        2.61          0.35             0.18
zero-shot    Convo                        3.44          0.22             0.15
             News+                        3.57          0.41             0.22
             Science                      3.47          0.24             0.16

                          moverscore  unieval_fluency  prometheus_fluency  \
train_domain test_domain
Convo        News+              0.07             0.84                2.77
             Science            0.04             0.89                2.68
News+        Convo              0.01             0.75                2.20
             Science            0.05             0.83                2.34
Science      Convo             -0.00             0.70                1.98
             News+              0.09             0.72                2.43
zero-shot    Convo              0.05             0.93                4.01
             News+              0.16             0.94                4.04
             Science            0.08             0.93                4.06

                          unieval_coherence  prometheus_coherence  \
train_domain test_domain
Convo        News+                     0.76                  2.65
             Science                   0.79                  2.52
News+        Convo                     0.80                  2.13
             Science                   0.78                  2.35
Science      Convo                     0.56                  1.94
             News+                     0.57                  2.42
zero-shot    Convo                     0.96                  3.87
             News+                     0.94                  4.00
             Science                   0.98                  3.96

                          compression_sentence  compression_token  \
train_domain test_domain
Convo        News+                       -3.52              -4.72
             Science                     -4.13              -5.85
News+        Convo                       -4.06              -2.30
             Science                     -1.85              -1.61
Science      Convo                       -6.07              -4.00
             News+                       -2.77              -2.69
zero-shot    Convo                       -3.74              -1.40
             News+                       -2.07              -1.64
             Science                     -1.38              -1.30

                          prometheus_coverage
train_domain test_domain
Convo        News+                       2.22
             Science                     2.23
News+        Convo                       1.98
             Science                     2.24
Science      Convo                       1.75
             News+                       2.13
zero-shot    Convo                       2.79
             News+                       3.02
             Science                     3.29

In [12]:
# Limit to models where the model is trained and tested on different domains
def safe_divide(num, denom):
    if denom == 0:
        return 0.0
    return num / denom

def get_relative_performance_loss(row):
    key = [row.train_domain, row.model_type]
    if row.train_domain == "zero-shot":
        key[0] = row.test_domain
        key[1] = "ICL"
    original_performance = same_domain_performance_dict.get(
        tuple(key),
        {}
    )
    rel_performance = {
        "train_domain": row.train_domain,
        "test_domain": row.test_domain,
        "model_type": row.model_type
    }
    rel_performance.update({
        m: safe_divide(
            row[m] - original_performance.get(m, 0.0), original_performance.get(m, 0.0)
        ) for m in wanted_metrics
    })
    return rel_performance

performance_diff = results_df[results_df.train_domain!=results_df.test_domain].apply(
    get_relative_performance_loss,
    axis="columns",
    result_type="expand"
)

In [13]:
diff = performance_diff.groupby(["model_type", "train_domain", "test_domain"]).mean(numeric_only=True)

print(diff.to_csv())

diff

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,News+,0.16530807766134192,-0.14084507042253513,-0.20502092050209214,-0.28155208407482596,-0.1746031746031746,-0.23631174527202478,-0.35047485831830316,-0.9931757611075502,0.0055395285037352976,-0.22605363984674326,-0.03214264989851111,-0.2016460905349795,-0.6526372543372948,-0.38356346778915557,-0.1472081218274112
ConvoSumm,Convo,Science,0.051171593849239194,-0.0845070422535211,-0.1757322175732218,-0.1286509325551099,-0.0992063492063492,-0.26063378577603546,-0.345861566592839,-0.6529589160321663,0.008917915906432487,-0.1494252873563217,-0.014001541625441727,-0.16460905349794253,-0.5833288536487031,-0.24488701222960554,-0.10659898477157359
ConvoSumm,News+,Convo,-0.12509052763828346,-0.33472803347280333,-0.2992125984251969,-0.06191907325117235,-0.27573529411764713,-0.5015647022125868,-0.4408486968578407,-0.9582874833407841,-0.05757607150816522,-0.35820895522388063,-0.07652263755013936,-0.4180602006688964,1.7550892868114092,0.7397210124974007,-0.2236842105263157
ConvoSumm,News+,Science,-0.11431400884395547,-0.2594142259414226,-0.30708661417322836,-0.12763806283553744,-0.21691176470588244,-0.4898858867526776,-0.43753805445793015,-0.8222591519996583,0.094425232730599,-0.332089552238806,-0.16005018499792883,-0.37458193979933113,0.7567469133419389,0.6018235547287593,-0.17105263157894735
ConvoSumm,Science,Convo,-0.3158634727076334,-0.24223602484472057,-0.15436241610738255,-0.4791035176996795,-0.2717391304347826,-0.17601835834904098,-0.06130631477752167,-1.2560179002261562,-0.11939955403379662,-0.20625000000000004,-0.2460556141281856,-0.1456953642384106,0.8997899270034381,0.13981256920991178,-0.18300653594771243
ConvoSumm,Science,News+,0.015824878160700974,0.12422360248447202,0.25503355704697994,-0.47475284360311926,0.14130434782608695,0.11261390883246436,0.01978497758562911,0.09906333500640742,-0.05300073020835285,0.03124999999999989,-0.15618508484476995,0.1258278145695364,-0.31278281518134426,-0.4144089116537886,0.10457516339869276
Llama 3.1,Convo,News+,0.07237575229600868,0.04854368932038847,0.0920245398773007,-0.0276687201350623,0.04899135446685877,0.9056780848761339,0.4312856166560251,1.9932151280263541,0.016372097340173624,0.043147208121827506,-0.017009805734656554,0.002518891687657377,-0.36423846744788196,0.3242158252686962,0.02372881355932198
Llama 3.1,Convo,Science,0.08412962049212537,0.0744336569579288,0.06441717791411056,-0.03928958528555443,0.031700288184438,0.15400301692136933,0.03902442507516632,0.5580570329775402,0.011061187704615207,0.030456852791878087,0.004034351383806039,0.0075566750629722425,-0.6170372309965362,-0.04455748096970307,0.09491525423728807
Llama 3.1,News+,Convo,-0.05657292014048794,-0.05937500000000012,-0.06916426512968306,0.022151696319875912,-0.044568245125348106,-0.45120703631888526,-0.27283224763360425,-0.6717364929564178,-0.00044556650845820175,-0.012376237623762332,0.01689158456650876,-0.0025445292620865727,0.742397235812531,-0.22098427226520562,0.0
Llama 3.1,News+,Science,0.009092389240167639,0.05624999999999991,-0.005763688760806921,0.005879465662615095,0.005571030640668529,-0.39923324770386914,-0.2648966038136226,-0.46086279198071495,-0.005505302193450638,-0.0024752475247524224,0.03640261847461675,0.017811704834605556,-0.4174220904808696,-0.27814346621113784,0.0777027027027027
Llama 3.1,Science,Convo,-0.06907256658334246,-0.06764705882352941,-0.07225433526011561,0.02890114169956035,-0.01699716713881009,-0.10102924018148607,-0.04220134964610353,-0.3089181162593592,-0.009293044535461809,0.0,-0.014167742862577807,-0.0075949367088608225,1.9042300903406373,0.12617894306447977,-0.08201892744479489
Llama 3.1,Science,News+,-0.007631410536572485,-0.044117647058823505,0.023121387283237014,0.024320546151475782,0.03116147308781879,0.6637862810588375,0.40557957013945173,0.9477376934443651,0.013962120323373472,0.032994923857868105,-0.024695520534113866,0.00759493670886071,0.5645750107334614,0.3048093929712179,-0.07570977917981066
Llama 3.1 (0-shot),zero-shot,Convo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Llama 3.1 (0-shot),zero-shot,News+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Llama 3.1 (0-shot),zero-shot,Science,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PRIMERA,Convo,News+,0.024198513818133125,0.39716312056737596,0.368421052631579,0.017775073624914605,0.34463276836158185,0.9839940657404592,0.7271477174569257,-10.055068018822064,-0.022090148079979704,0.5572519083969465,-0.05431439794098637,0.5901639344262295,-0.6094013268219305,-0.6729016230233508,0.305194805194805
PRIMERA,Convo,Science,0.040499066828263576,0.39007092198581567,0.2828947368421052,0.5262845077985382,0.34463276836158185,0.19909410883103418,0.15838390933879753,-4.893596096185503,0.23173464462710944,0.3893129770992366,-0.022165843989584877,0.46721311475409844,-0.5621507981005878,-0.5941848909391665,0.25974025974025966
PRIMERA,News+,Convo,0.05457586297271398,-0.3333333333333332,-0.2949308755760368,-0.06916878029871917,-0.25738396624472576,-0.48539838697115745,-0.3902279050262362,-1.114152149168345,0.060348051186020844,-0.2989690721649484,0.11144016708083467,-0.32116867600738574,1.2702017318816001,1.3008790134340575,-0.21649484536082472
PRIMERA,News+,Science,0.048433007355952365,0.009950248756218916,-0.09677419354838708,0.5041938976481509,0.012658227848101182,-0.3862979389868443,-0.3106528041804655,-0.5423187074853317,0.3000217053368877,-0.010309278350515474,0.1325118587209177,-0.01612903225806453,0.0298583800602827,0.16845706833290913,0.051546391752577365
PRIMERA,Science,Convo,-0.047456159380883364,-0.27040816326530615,-0.2474747474747475,-0.34166019886070265,-0.2594142259414226,-0.17390773858614383,-0.11987584851996665,-1.2941524073625925,-0.17117878417340923,-0.23428571428571424,-0.09420980761237523,-0.2888888888888889,0.8408736553324127,0.561950894362,-0.20999999999999996
PRIMERA,Science,News+,-0.06710409196778913,0.0,0.045454545454545386,-0.2982278733567541,-0.02510460251046027,0.6929789967570258,0.4947858290497212,1.3869641483591644,-0.19901450082070216,0.11428571428571425,-0.07651441524666071,0.07777777777777772,-0.00023042072256150215,-0.093955608862047,-0.0050000000000000044
SummN,Convo,News+,0.3599006154293457,0.13389121338912127,0.05600000000000005,-0.1113257936130975,0.014760147601476028,-0.30308598598079933,-0.3377404795194002,-0.932976416139785,-0.02192343524062907,0.013888888888888902,0.14609957490353132,-0.014388489208632947,-0.49423021867911654,0.02106635845956993,0.0
SummN,Convo,Science,0.16294096880164124,0.050209205020920356,-0.05600000000000005,-0.0030105206359933626,-0.08487084870848707,-0.3675966580396636,-0.3863430332748812,-0.846706131335654,0.01705476717257987,-0.09375000000000001,0.23522950290195332,-0.18345323741007188,-0.285725296747341,0.39040801689465787,-0.08715596330275237
SummN,News+,Convo,-0.07729484189605206,-0.3513513513513514,-0.307017543859649,-0.09774916926747547,-0.24418604651162795,-0.5283743189811333,-0.46443265006495077,-0.9898312312662589,-0.052564418200488516,-0.29838709677419356,-0.08702254165643289,-0.4275362318840579,1.9192562694196618,0.7495896874787926,-0.22685185185185194
SummN,News+,Science,-0.1153375102099247,-0.2927927927927928,-0.3245614035087719,-0.1504214151360094,-0.1666666666666667,-0.5321175862890695,-0.48123914286573416,-0.8330563498127512,0.04238320384354402,-0.342741935483871,-0.15698211163590833,-0.3913043478260869,0.17656677016187267,0.025337931496031266,-0.1527777777777778
SummN,Science,Convo,-0.2922744301952751,-0.22602739726027402,-0.16551724137931034,-0.3267163861291291,-0.2631578947368421,-0.22218808745402185,-0.09439880800945116,-2.3095466650779812,-0.08202486181914688,-0.028368794326241006,-0.14818866719608786,-0.10714285714285708,0.6341491096222853,-0.11787584102799357,-0.16
SummN,Science,News+,0.17091256511212027,0.3356164383561644,0.406896551724138,-0.3264705950521151,0.38011695906432746,0.15482012034028192,0.09130789524676519,0.5123425855776311,0.006632278986362558,0.4539007092198581,-0.10528370528434819,0.47857142857142854,-0.21308431631427963,-0.23825733085036307,0.2666666666666666

                                             unieval_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                      0.17
                                Science                    0.05
                   News+        Convo                     -0.13
                                Science                   -0.11
                   Science      Convo                     -0.32
                                News+                      0.02
Llama 3.1          Convo        News+                      0.07
                                Science                    0.08
                   News+        Convo                     -0.06
                                Science                    0.01
                   Science      Convo                     -0.07
                                News+                     -0.01
Llama 3.1 (0-shot) zero-shot    Convo                      0.00
                                News+                      0.00
                                Science                    0.00
PRIMERA            Convo        News+                      0.02
                                Science                    0.04
                   News+        Convo                      0.05
                                Science                    0.05
                   Science      Convo                     -0.05
                                News+                     -0.07
SummN              Convo        News+                      0.36
                                Science                    0.16
                   News+        Convo                     -0.08
                                Science                   -0.12
                   Science      Convo                     -0.29
                                News+                      0.17

                                             prometheus_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                        -0.14
                                Science                      -0.08
                   News+        Convo                        -0.33
                                Science                      -0.26
                   Science      Convo                        -0.24
                                News+                         0.12
Llama 3.1          Convo        News+                         0.05
                                Science                       0.07
                   News+        Convo                        -0.06
                                Science                       0.06
                   Science      Convo                        -0.07
                                News+                        -0.04
Llama 3.1 (0-shot) zero-shot    Convo                         0.00
                                News+                         0.00
                                Science                       0.00
PRIMERA            Convo        News+                         0.40
                                Science                       0.39
                   News+        Convo                        -0.33
                                Science                       0.01
                   Science      Convo                        -0.27
                                News+                         0.00
SummN              Convo        News+                         0.13
                                Science                       0.05
                   News+        Convo                        -0.35
                                Science                      -0.29
                   Science      Convo                        -0.23
                                News+                         0.34

                                             prometheus_consistency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                         -0.21
                                Science                       -0.18
                   News+        Convo                         -0.30
                                Science                       -0.31
                   Science      Convo                         -0.15
                                News+                          0.26
Llama 3.1          Convo        News+                          0.09
                                Science                        0.06
                   News+        Convo                         -0.07
                                Science                       -0.01
                   Science      Convo                         -0.07
                                News+                          0.02
Llama 3.1 (0-shot) zero-shot    Convo                          0.00
                                News+                          0.00
                                Science                        0.00
PRIMERA            Convo        News+                          0.37
                                Science                        0.28
                   News+        Convo                         -0.29
                                Science                       -0.10
                   Science      Convo                         -0.25
                                News+                          0.05
SummN              Convo        News+                          0.06
                                Science                       -0.06
                   News+        Convo                         -0.31
                                Science                       -0.32
                   Science      Convo                         -0.17
                                News+                          0.41

                                             unieval_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                    -0.28
                                Science                  -0.13
                   News+        Convo                    -0.06
                                Science                  -0.13
                   Science      Convo                    -0.48
                                News+                    -0.47
Llama 3.1          Convo        News+                    -0.03
                                Science                  -0.04
                   News+        Convo                     0.02
                                Science                   0.01
                   Science      Convo                     0.03
                                News+                     0.02
Llama 3.1 (0-shot) zero-shot    Convo                     0.00
                                News+                     0.00
                                Science                   0.00
PRIMERA            Convo        News+                     0.02
                                Science                   0.53
                   News+        Convo                    -0.07
                                Science                   0.50
                   Science      Convo                    -0.34
                                News+                    -0.30
SummN              Convo        News+                    -0.11
                                Science                  -0.00
                   News+        Convo                    -0.10
                                Science                  -0.15
                   Science      Convo                    -0.33
                                News+                    -0.33

                                             prometheus_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -0.17
                                Science                     -0.10
                   News+        Convo                       -0.28
                                Science                     -0.22
                   Science      Convo                       -0.27
                                News+                        0.14
Llama 3.1          Convo        News+                        0.05
                                Science                      0.03
                   News+        Convo                       -0.04
                                Science                      0.01
                   Science      Convo                       -0.02
                                News+                        0.03
Llama 3.1 (0-shot) zero-shot    Convo                        0.00
                                News+                        0.00
                                Science                      0.00
PRIMERA            Convo        News+                        0.34
                                Science                      0.34
                   News+        Convo                       -0.26
                                Science                      0.01
                   Science      Convo                       -0.26
                                News+                       -0.03
SummN              Convo        News+                        0.01
                                Science                     -0.08
                   News+        Convo                       -0.24
                                Science                     -0.17
                   Science      Convo                       -0.26
                                News+                        0.38

                                             rouge_rouge1  rouge_rougeLsum  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+               -0.24            -0.35
                                Science             -0.26            -0.35
                   News+        Convo               -0.50            -0.44
                                Science             -0.49            -0.44
                   Science      Convo               -0.18            -0.06
                                News+                0.11             0.02
Llama 3.1          Convo        News+                0.91             0.43
                                Science              0.15             0.04
                   News+        Convo               -0.45            -0.27
                                Science             -0.40            -0.26
                   Science      Convo               -0.10            -0.04
                                News+                0.66             0.41
Llama 3.1 (0-shot) zero-shot    Convo                0.00             0.00
                                News+                0.00             0.00
                                Science              0.00             0.00
PRIMERA            Convo        News+                0.98             0.73
                                Science              0.20             0.16
                   News+        Convo               -0.49            -0.39
                                Science             -0.39            -0.31
                   Science      Convo               -0.17            -0.12
                                News+                0.69             0.49
SummN              Convo        News+               -0.30            -0.34
                                Science             -0.37            -0.39
                   News+        Convo               -0.53            -0.46
                                Science             -0.53            -0.48
                   Science      Convo               -0.22            -0.09
                                News+                0.15             0.09

                                             moverscore  unieval_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+             -0.99             0.01
                                Science           -0.65             0.01
                   News+        Convo             -0.96            -0.06
                                Science           -0.82             0.09
                   Science      Convo             -1.26            -0.12
                                News+              0.10            -0.05
Llama 3.1          Convo        News+              1.99             0.02
                                Science            0.56             0.01
                   News+        Convo             -0.67            -0.00
                                Science           -0.46            -0.01
                   Science      Convo             -0.31            -0.01
                                News+              0.95             0.01
Llama 3.1 (0-shot) zero-shot    Convo              0.00             0.00
                                News+              0.00             0.00
                                Science            0.00             0.00
PRIMERA            Convo        News+            -10.06            -0.02
                                Science           -4.89             0.23
                   News+        Convo             -1.11             0.06
                                Science           -0.54             0.30
                   Science      Convo             -1.29            -0.17
                                News+              1.39            -0.20
SummN              Convo        News+             -0.93            -0.02
                                Science           -0.85             0.02
                   News+        Convo             -0.99            -0.05
                                Science           -0.83             0.04
                   Science      Convo             -2.31            -0.08
                                News+              0.51             0.01

                                             prometheus_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     -0.23
                                Science                   -0.15
                   News+        Convo                     -0.36
                                Science                   -0.33
                   Science      Convo                     -0.21
                                News+                      0.03
Llama 3.1          Convo        News+                      0.04
                                Science                    0.03
                   News+        Convo                     -0.01
                                Science                   -0.00
                   Science      Convo                      0.00
                                News+                      0.03
Llama 3.1 (0-shot) zero-shot    Convo                      0.00
                                News+                      0.00
                                Science                    0.00
PRIMERA            Convo        News+                      0.56
                                Science                    0.39
                   News+        Convo                     -0.30
                                Science                   -0.01
                   Science      Convo                     -0.23
                                News+                      0.11
SummN              Convo        News+                      0.01
                                Science                   -0.09
                   News+        Convo                     -0.30
                                Science                   -0.34
                   Science      Convo                     -0.03
                                News+                      0.45

                                             unieval_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                    -0.03
                                Science                  -0.01
                   News+        Convo                    -0.08
                                Science                  -0.16
                   Science      Convo                    -0.25
                                News+                    -0.16
Llama 3.1          Convo        News+                    -0.02
                                Science                   0.00
                   News+        Convo                     0.02
                                Science                   0.04
                   Science      Convo                    -0.01
                                News+                    -0.02
Llama 3.1 (0-shot) zero-shot    Convo                     0.00
                                News+                     0.00
                                Science                   0.00
PRIMERA            Convo        News+                    -0.05
                                Science                  -0.02
                   News+        Convo                     0.11
                                Science                   0.13
                   Science      Convo                    -0.09
                                News+                    -0.08
SummN              Convo        News+                     0.15
                                Science                   0.24
                   News+        Convo                    -0.09
                                Science                  -0.16
                   Science      Convo                    -0.15
                                News+                    -0.11

                                             prometheus_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -0.20
                                Science                     -0.16
                   News+        Convo                       -0.42
                                Science                     -0.37
                   Science      Convo                       -0.15
                                News+                        0.13
Llama 3.1          Convo        News+                        0.00
                                Science                      0.01
                   News+        Convo                       -0.00
                                Science                      0.02
                   Science      Convo                       -0.01
                                News+                        0.01
Llama 3.1 (0-shot) zero-shot    Convo                        0.00
                                News+                        0.00
                                Science                      0.00
PRIMERA            Convo        News+                        0.59
                                Science                      0.47
                   News+        Convo                       -0.32
                                Science                     -0.02
                   Science      Convo                       -0.29
                                News+                        0.08
SummN              Convo        News+                       -0.01
                                Science                     -0.18
                   News+        Convo                       -0.43
                                Science                     -0.39
                   Science      Convo                       -0.11
                                News+                        0.48

                                             compression_sentence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -0.65
                                Science                     -0.58
                   News+        Convo                        1.76
                                Science                      0.76
                   Science      Convo                        0.90
                                News+                       -0.31
Llama 3.1          Convo        News+                       -0.36
                                Science                     -0.62
                   News+        Convo                        0.74
                                Science                     -0.42

In [14]:
model_display_order = [
    "ConvoSumm",
    "PRIMERA",
    "SummN",
    "Llama 3.1",
    "Llama 3.1 (0-shot)"
]
diff_data = performance_diff.groupby(["model_type"]).mean(numeric_only=True).reindex(model_display_order)
print(diff_data.to_csv())
diff_data

model_type,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,-0.053827243253098365,-0.15625113240842178,-0.14773020162235695,-0.2589360856699074,-0.14948189420695818,-0.25863342825498353,-0.26937408556980097,-0.7639393129499846,-0.020182279768257986,-0.20679623911095865,-0.11415961884082942,-0.19646080569500393,0.3104795339982407,0.07308295746058702,-0.12116255354221124
PRIMERA,0.008857699937731759,0.032240465785128535,0.009598419721509691,0.05653277109257129,0.02667016164577604,0.1384105177973956,0.09326014968646268,-2.7520538717774454,0.03330349467932115,0.08621442249678656,-0.0005420731646424704,0.08482803830062774,0.16152520360486927,0.11170747555073374,0.030831101887802897
SummN,0.03480789450697589,-0.0584091141063687,-0.06503327283726554,-0.16928231330563667,-0.06066739165963672,-0.2997570860674009,-0.2788077030812754,-0.8999623680091332,-0.01507374420962967,-0.04924303807925976,-0.019357991327882105,-0.10754228915004636,0.2894887195771804,0.13837813707511584,-0.060019821044285916
Llama 3.1,0.0053868107946498005,0.001347940065994025,0.005396802654007114,0.0023824240688184017,0.009309789019270981,0.12866630977535004,0.049326568462885446,0.3429154088752946,0.004358582021798609,0.01529124993717649,0.00024258088226388787,0.004223790387191415,0.30208409132689035,0.03525315697639122,0.006436343979117867
Llama 3.1 (0-shot),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
model_type,,,,,,,,,,,,,,,
ConvoSumm,-0.05,-0.16,-0.15,-0.26,-0.15,-0.26,-0.27,-0.76,-0.02,-0.21,-0.11,-0.20,0.31,0.07,-0.12
PRIMERA,0.01,0.03,0.01,0.06,0.03,0.14,0.09,-2.75,0.03,0.09,-0.00,0.08,0.16,0.11,0.03
SummN,0.03,-0.06,-0.07,-0.17,-0.06,-0.30,-0.28,-0.90,-0.02,-0.05,-0.02,-0.11,0.29,0.14,-0.06
Llama 3.1,0.01,0.00,0.01,0.00,0.01,0.13,0.05,0.34,0.00,0.02,0.00,0.00,0.30,0.04,0.01
Llama 3.1 (0-shot),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [15]:
performance_diff.groupby(["train_domain"]).mean(numeric_only=True)

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
train_domain,,,,,,,,,,,,,,,
Convo,0.12,0.11,0.05,-0.01,0.05,0.13,-0.01,-1.98,0.03,0.07,0.03,0.06,-0.52,-0.15,0.04
News+,-0.05,-0.20,-0.21,0.00,-0.15,-0.47,-0.38,-0.80,0.05,-0.21,-0.02,-0.24,0.78,0.39,-0.11
Science,-0.08,-0.05,0.01,-0.27,-0.04,0.12,0.09,-0.28,-0.08,0.02,-0.11,0.02,0.54,0.03,-0.04
zero-shot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [16]:
diff_data = performance_diff.groupby(["train_domain", "test_domain"]).mean(numeric_only=True)
print(diff_data.to_csv(float_format='%.2f'))
diff_data

train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,News+,0.16,0.11,0.08,-0.10,0.06,0.34,0.12,-2.50,-0.01,0.10,0.01,0.09,-0.53,-0.18,0.05
Convo,Science,0.08,0.11,0.03,0.09,0.05,-0.07,-0.13,-1.46,0.07,0.04,0.05,0.03,-0.51,-0.12,0.04
News+,Convo,-0.05,-0.27,-0.24,-0.05,-0.21,-0.49,-0.39,-0.93,-0.01,-0.24,-0.01,-0.29,1.42,0.64,-0.17
News+,Science,-0.04,-0.12,-0.18,0.06,-0.09,-0.45,-0.37,-0.66,0.11,-0.17,-0.04,-0.19,0.14,0.13,-0.05
Science,Convo,-0.18,-0.20,-0.16,-0.28,-0.20,-0.17,-0.08,-1.29,-0.10,-0.12,-0.13,-0.14,1.07,0.18,-0.16
Science,News+,0.03,0.10,0.18,-0.27,0.13,0.41,0.25,0.74,-0.06,0.16,-0.09,0.17,0.01,-0.11,0.07
zero-shot,Convo,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
zero-shot,News+,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
zero-shot,Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

                          unieval_factuality  prometheus_factuality  \
train_domain test_domain
Convo        News+                      0.16                   0.11
             Science                    0.08                   0.11
News+        Convo                     -0.05                  -0.27
             Science                   -0.04                  -0.12
Science      Convo                     -0.18                  -0.20
             News+                      0.03                   0.10
zero-shot    Convo                      0.00                   0.00
             News+                      0.00                   0.00
             Science                    0.00                   0.00

                          prometheus_consistency  unieval_relevance  \
train_domain test_domain
Convo        News+                          0.08              -0.10
             Science                        0.03               0.09
News+        Convo                         -0.24              -0.05
             Science                       -0.18               0.06
Science      Convo                         -0.16              -0.28
             News+                          0.18              -0.27
zero-shot    Convo                          0.00               0.00
             News+                          0.00               0.00
             Science                        0.00               0.00

                          prometheus_relevance  rouge_rouge1  rouge_rougeLsum  \
train_domain test_domain
Convo        News+                        0.06          0.34             0.12
             Science                      0.05         -0.07            -0.13
News+        Convo                       -0.21         -0.49            -0.39
             Science                     -0.09         -0.45            -0.37
Science      Convo                       -0.20         -0.17            -0.08
             News+                        0.13          0.41             0.25
zero-shot    Convo                        0.00          0.00             0.00
             News+                        0.00          0.00             0.00
             Science                      0.00          0.00             0.00

                          moverscore  unieval_fluency  prometheus_fluency  \
train_domain test_domain
Convo        News+             -2.50            -0.01                0.10
             Science           -1.46             0.07                0.04
News+        Convo             -0.93            -0.01               -0.24
             Science           -0.66             0.11               -0.17
Science      Convo             -1.29            -0.10               -0.12
             News+              0.74            -0.06                0.16
zero-shot    Convo              0.00             0.00                0.00
             News+              0.00             0.00                0.00
             Science            0.00             0.00                0.00

                          unieval_coherence  prometheus_coherence  \
train_domain test_domain
Convo        News+                     0.01                  0.09
             Science                   0.05                  0.03
News+        Convo                    -0.01                 -0.29
             Science                  -0.04                 -0.19
Science      Convo                    -0.13                 -0.14
             News+                    -0.09                  0.17
zero-shot    Convo                     0.00                  0.00
             News+                     0.00                  0.00
             Science                   0.00                  0.00

                          compression_sentence  compression_token  \
train_domain test_domain
Convo        News+                       -0.53              -0.18
             Science                     -0.51              -0.12
News+        Convo                        1.42               0.64
             Science                      0.14               0.13
Science      Convo                        1.07               0.18
             News+                        0.01              -0.11
zero-shot    Convo                        0.00               0.00
             News+                        0.00               0.00
             Science                      0.00               0.00

                          prometheus_coverage
train_domain test_domain
Convo        News+                       0.05
             Science                     0.04
News+        Convo                      -0.17
             Science                    -0.05
Science      Convo                      -0.16
             News+                       0.07
zero-shot    Convo                       0.00
             News+                       0.00
             Science                     0.00

In [17]:
a = performance_diff.groupby(["train_domain"]).mean(numeric_only=True)
print(a.to_csv(float_format='%.2f'))
a

train_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,0.12,0.11,0.05,-0.01,0.05,0.13,-0.01,-1.98,0.03,0.07,0.03,0.06,-0.52,-0.15,0.04
News+,-0.05,-0.20,-0.21,0.00,-0.15,-0.47,-0.38,-0.80,0.05,-0.21,-0.02,-0.24,0.78,0.39,-0.11
Science,-0.08,-0.05,0.01,-0.27,-0.04,0.12,0.09,-0.28,-0.08,0.02,-0.11,0.02,0.54,0.03,-0.04
zero-shot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
train_domain,,,,,,,,,,,,,,,
Convo,0.12,0.11,0.05,-0.01,0.05,0.13,-0.01,-1.98,0.03,0.07,0.03,0.06,-0.52,-0.15,0.04
News+,-0.05,-0.20,-0.21,0.00,-0.15,-0.47,-0.38,-0.80,0.05,-0.21,-0.02,-0.24,0.78,0.39,-0.11
Science,-0.08,-0.05,0.01,-0.27,-0.04,0.12,0.09,-0.28,-0.08,0.02,-0.11,0.02,0.54,0.03,-0.04
zero-shot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [18]:
a = performance_diff.groupby(["test_domain"]).mean(numeric_only=True)
print(a.to_csv(float_format='%.2f'))
a

test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,-0.10,-0.21,-0.18,-0.15,-0.18,-0.29,-0.21,-0.99,-0.05,-0.16,-0.06,-0.19,1.11,0.36,-0.14
News+,0.08,0.09,0.12,-0.16,0.08,0.33,0.16,-0.78,-0.03,0.11,-0.04,0.12,-0.23,-0.13,0.05
Science,0.02,-0.01,-0.07,0.07,-0.02,-0.23,-0.23,-0.94,0.08,-0.06,0.01,-0.07,-0.17,0.00,-0.00

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
test_domain,,,,,,,,,,,,,,,
Convo,-0.10,-0.21,-0.18,-0.15,-0.18,-0.29,-0.21,-0.99,-0.05,-0.16,-0.06,-0.19,1.11,0.36,-0.14
News+,0.08,0.09,0.12,-0.16,0.08,0.33,0.16,-0.78,-0.03,0.11,-0.04,0.12,-0.23,-0.13,0.05
Science,0.02,-0.01,-0.07,0.07,-0.02,-0.23,-0.23,-0.94,0.08,-0.06,0.01,-0.07,-0.17,0.00,-0.00

# Q: Evaluating the metrics

Theoretically, the metrics should all be very high on the ground truth datasets. Is that the case?

In [19]:
a = results_df[results_df.model_type=="ground_truth"]

print(a.to_csv(float_format='%.2f'))
a

,model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
0,ground_truth,Convo,Convo,0.71,3.07,3.06,0.99,3.23,-1.00,-1.00,-1.00,0.89,3.30,0.73,3.39,0.90,0.85,2.57
14,ground_truth,Science,Science,0.55,1.82,1.86,0.99,2.78,-1.00,-1.00,-1.00,0.67,1.53,0.45,1.51,-6.32,-5.63,1.90
28,ground_truth,News+,News+,0.73,2.84,3.16,0.99,3.39,-1.00,-1.00,1.00,0.77,2.75,0.74,3.70,-1.17,-1.10,2.69

,model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
0,ground_truth,Convo,Convo,0.71,3.07,3.06,0.99,3.23,-1.00,-1.00,-1.00,0.89,3.30,0.73,3.39,0.90,0.85,2.57
14,ground_truth,Science,Science,0.55,1.82,1.86,0.99,2.78,-1.00,-1.00,-1.00,0.67,1.53,0.45,1.51,-6.32,-5.63,1.90
28,ground_truth,News+,News+,0.73,2.84,3.16,0.99,3.39,-1.00,-1.00,1.00,0.77,2.75,0.74,3.70,-1.17,-1.10,2.69