In [1]:
import os
import ast

import pandas as pd
import matplotlib.pyplot as plt
import scipy

from plotting_utils import (
    get_train_domain,
    get_test_domain,
    get_model_name,
    wanted_metrics
)

pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.multi_sparse', True)
PROJECT_DIR = os.environ["MDS"]

# Load and format results

In [2]:
results_df = pd.read_csv(
    #f"{PROJECT_DIR}/results_mayarr_sample/experiments_mayarr/aggregated_results.csv",
    f"{PROJECT_DIR}/results_mayarr/experiments_mayarr/aggregated_results.csv",
    header=[0,1]
)

results_df.columns = pd.Index([
  f"{c[0]}_{c[1]}" if c[1]!="nan" else c[0] for c in results_df.columns
])

results_df["train_domain"] = results_df.apply(get_train_domain, axis="columns")
results_df["test_domain"] = results_df.dataset.map(get_test_domain)
results_df["model_type"] = results_df.model.map(get_model_name)

# Remove validation set
results_df = results_df[results_df.split=="test"]

new_columns = [
    "model_type",
    "train_domain",
    "test_domain",
] + wanted_metrics

# Add placeholders
for c in new_columns:
    if c not in results_df.columns:
        results_df[c] = pd.NA

results_df = results_df[new_columns]

def format_entry(entry: str):
    try:
        entry = ast.literal_eval(entry)
    except ValueError as err:
        print(f"Could not convert '{entry}' as literal")
        return pd.NA
    return entry.get("mean", pd.NA)

# Display only the mean
for metric in wanted_metrics:
    results_df[metric] = results_df[metric].map(format_entry)

# Change compression so that higher score = more compressed summary
# 1 - (# sentences in summary / # sentences in source docs)
for m in ["compression_sentence", "compression_token"]:
    results_df[m] = 1 - results_df[m]


# Hack
results_df = results_df.fillna(-1)

Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert '{'mean': 1.0, 'std': 0.0, 'ci': (nan, nan), 'ci_std': 0.0}' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert 'nan' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal
Could not convert '<NA>' as literal

/tmp/ipykernel_2515689/1805173534.py:50: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  results_df = results_df.fillna(-1)

In [3]:
a = results_df.set_index("model_type").loc["PRIMERA"].set_index(["train_domain", "test_domain"]).sort_index()
a[["prometheus_factuality", "prometheus_consistency", "rouge_rouge1"]]

                          prometheus_factuality  prometheus_consistency  \
train_domain test_domain
Convo        Convo                         1.45                    1.58
             News+                        -1.00                   -1.00
             Science                       1.92                    1.98
News+        Convo                         1.45                    1.52
             News+                        -1.00                   -1.00
             Science                       1.93                    1.96
Science      Convo                         1.38                    1.53
             News+                        -1.00                   -1.00
             Science                       1.93                    1.97

                          rouge_rouge1
train_domain test_domain
Convo        Convo                0.19
             News+                0.38
             Science              0.24
News+        Convo                0.19
             News+                0.38
             Science              0.24
Science      Convo                0.19
             News+                0.38
             Science              0.24

In [4]:
results_df.columns

Index(['model_type', 'train_domain', 'test_domain', 'unieval_factuality',
       'prometheus_factuality', 'prometheus_consistency', 'unieval_relevance',
       'prometheus_relevance', 'rouge_rouge1', 'rouge_rougeLsum', 'moverscore',
       'unieval_fluency', 'prometheus_fluency', 'unieval_coherence',
       'prometheus_coherence', 'compression_sentence', 'compression_token',
       'prometheus_coverage'],
      dtype='object')

In [5]:
results_df.groupby("model_type").agg({
    "compression_sentence": ["mean", "std"],
    "compression_token": ["mean", "std"]
})

                   compression_sentence      compression_token
                                   mean  std              mean  std
model_type
ConvoSumm                          0.72 0.14              0.74 0.14
Llama 3.1                          0.64 0.11              0.55 0.05
Llama 3.1 (0-shot)                 0.64 0.12              0.55 0.06
PRIMERA                            0.66 0.06              0.56 0.05
SummN                              0.71 0.17              0.70 0.18
ground_truth                       0.68 0.25              0.67 0.23

In [6]:
a = results_df.set_index(["model_type", "train_domain", "test_domain"]).sort_index()
print(a.to_csv(float_format='%.2f'))
a

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,Convo,0.64,2.21,2.25,0.70,2.44,0.31,0.21,0.06,0.91,2.67,0.60,2.49,0.91,0.91,-1
ConvoSumm,Convo,News+,0.76,-1.00,-1.00,0.51,-1.00,0.24,0.14,0.00,0.90,-1.00,0.58,-1.00,0.77,0.84,-1
ConvoSumm,Convo,Science,0.68,1.94,1.92,0.63,2.21,0.23,0.14,0.02,0.91,2.17,0.61,2.05,0.76,0.85,-1
ConvoSumm,News+,Convo,0.70,1.62,1.67,0.76,2.08,0.23,0.13,0.01,0.70,1.79,0.78,1.80,0.71,0.62,-1
ConvoSumm,News+,News+,0.78,-1.00,-1.00,0.79,-1.00,0.45,0.23,0.20,0.75,-1.00,0.82,-1.00,0.48,0.54,-1
ConvoSumm,News+,Science,0.71,1.82,-1.00,0.69,2.18,0.24,0.14,0.04,0.82,-1.00,0.69,-1.00,0.55,0.55,-1
ConvoSumm,Science,Convo,0.46,1.23,1.33,0.23,1.42,0.22,0.15,-0.02,0.58,1.32,0.25,1.24,0.87,0.85,-1
ConvoSumm,Science,News+,0.64,-1.00,-1.00,0.24,-1.00,0.27,0.15,0.03,0.60,-1.00,0.28,-1.00,0.69,0.75,-1
ConvoSumm,Science,Science,0.60,1.57,1.57,0.49,1.84,0.28,0.16,0.04,0.69,1.47,0.38,1.47,0.72,0.79,-1
Llama 3.1,Convo,Convo,0.83,3.06,3.21,0.93,3.35,0.22,0.15,0.05,0.93,4.00,0.95,3.98,0.75,0.52,-1
Llama 3.1,Convo,News+,0.88,-1.00,-1.00,0.92,-1.00,0.40,0.21,0.17,0.95,-1.00,0.94,-1.00,0.66,0.62,-1
Llama 3.1,Convo,Science,0.88,-1.00,-1.00,0.91,-1.00,0.25,0.16,0.09,0.93,-1.00,0.97,-1.00,0.51,0.51,-1
Llama 3.1,News+,Convo,0.82,3.06,3.26,0.93,3.41,0.22,0.15,0.05,0.93,4.06,0.95,3.96,0.76,0.53,-1
Llama 3.1,News+,News+,0.88,-1.00,-1.00,0.92,-1.00,0.40,0.21,0.17,0.95,-1.00,0.94,-1.00,0.66,0.62,-1
Llama 3.1,News+,Science,0.87,-1.00,-1.00,0.91,-1.00,0.25,0.16,0.09,0.93,-1.00,0.97,-1.00,0.51,0.51,-1
Llama 3.1,Science,Convo,0.83,3.18,3.34,0.94,3.46,0.22,0.15,0.05,0.93,4.00,0.96,3.98,0.76,0.53,-1
Llama 3.1,Science,News+,0.88,-1.00,-1.00,0.93,-1.00,0.40,0.21,0.17,0.95,-1.00,0.94,-1.00,0.66,0.62,-1
Llama 3.1,Science,Science,0.88,-1.00,-1.00,0.91,-1.00,0.25,0.16,0.09,0.93,-1.00,0.97,-1.00,0.52,0.51,-1
Llama 3.1 (0-shot),zero-shot,Convo,0.82,3.00,3.26,0.94,3.43,0.22,0.15,0.05,0.92,4.04,0.96,3.95,0.75,0.53,-1
Llama 3.1 (0-shot),zero-shot,News+,0.88,-1.00,-1.00,0.92,-1.00,0.40,0.21,0.17,0.95,-1.00,0.94,-1.00,0.66,0.61,-1
Llama 3.1 (0-shot),zero-shot,Science,0.88,-1.00,-1.00,0.91,-1.00,0.25,0.16,0.08,0.93,-1.00,0.97,-1.00,0.51,0.51,-1
PRIMERA,Convo,Convo,0.81,1.45,1.58,0.40,1.93,0.19,0.11,-0.01,0.65,1.34,0.68,1.30,0.73,0.59,-1
PRIMERA,Convo,News+,0.81,-1.00,-1.00,0.42,-1.00,0.38,0.18,0.13,0.61,-1.00,0.69,-1.00,0.61,0.52,-1
PRIMERA,Convo,Science,0.83,1.92,1.98,0.62,2.38,0.24,0.13,0.06,0.80,1.83,0.73,1.80,0.62,0.53,-1
PRIMERA,News+,Convo,0.81,1.45,1.52,0.41,1.98,0.19,0.11,-0.01,0.66,1.29,0.72,1.27,0.75,0.63,-1
PRIMERA,News+,News+,0.81,-1.00,-1.00,0.42,-1.00,0.38,0.18,0.13,0.62,-1.00,0.69,-1.00,0.62,0.52,-1
PRIMERA,News+,Science,0.82,1.93,1.96,0.62,2.36,0.24,0.13,0.06,0.79,1.83,0.74,1.80,0.63,0.53,-1
PRIMERA,Science,Convo,0.82,1.38,1.53,0.41,1.92,0.19,0.11,-0.01,0.65,1.32,0.71,1.27,0.74,0.62,-1
PRIMERA,Science,News+,0.81,-1.00,-1.00,0.42,-1.00,0.38,0.18,0.13,0.61,-1.00,0.70,-1.00,0.62,0.52,-1
PRIMERA,Science,Science,0.84,1.93,1.97,0.62,2.36,0.24,0.13,0.06,0.80,1.82,0.74,1.79,0.62,0.53,-1
SummN,Convo,Convo,0.67,2.45,2.49,0.72,2.78,0.33,0.21,0.09,0.90,2.90,0.71,2.79,0.90,0.86,-1
SummN,Convo,News+,0.90,-1.00,-1.00,0.61,-1.00,0.22,0.14,0.01,0.89,-1.00,0.82,-1.00,0.83,0.88,-1
SummN,Convo,Science,0.80,2.48,2.40,0.67,2.57,0.22,0.14,0.02,0.91,2.60,0.86,2.40,0.84,0.88,-1
SummN,News+,Convo,0.67,1.50,1.52,0.73,2.00,0.22,0.12,0.01,0.69,1.72,0.75,1.72,0.70,0.56,-1
SummN,News+,News+,0.72,-1.00,-1.00,0.77,-1.00,0.45,0.23,0.19,0.73,-1.00,0.80,-1.00,0.45,0.50,-1
SummN,News+,Science,0.64,1.59,1.59,0.64,2.15,0.22,0.12,0.03,0.77,1.68,0.68,1.72,0.43,0.39,-1
SummN,Science,Convo,0.40,1.13,1.24,0.31,1.24,0.21,0.14,-0.03,0.62,1.30,0.30,1.24,0.84,0.75,-1
SummN,Science,News+,0.64,-1.00,-1.00,0.34,-1.00,0.30,0.16,0.04,0.70,-1.00,0.35,-1.00,0.68,0.73,-1
SummN,Science,Science,0.56,1.46,1.46,0.49,1.65,0.27,0.16,0.03,0.66,1.41,0.39,1.40,0.71,0.74,-1
ground_truth,Convo,Convo,0.71,3.03,3.13,0.99,3.26,-1.00,-1.00,1.00,0.90,3.28,0.73,3.48,0.90,0.85,-1
ground_truth,News+,News+,0.70,-1.00,-1.00,0.98,-1.00,-1.00,-1.00,1.00,0.76,-1.00,0.75,-1.00,0.41,0.41,-1
ground_truth,Science,Science,0.55,1.82,1.82,0.99,2.76,-1.00,-1.00,1.00,0.66,1.56,0.43,1.49,0.74,0.75,-1

                                             unieval_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                      0.64
                                News+                      0.76
                                Science                    0.68
                   News+        Convo                      0.70
                                News+                      0.78
                                Science                    0.71
                   Science      Convo                      0.46
                                News+                      0.64
                                Science                    0.60
Llama 3.1          Convo        Convo                      0.83
                                News+                      0.88
                                Science                    0.88
                   News+        Convo                      0.82
                                News+                      0.88
                                Science                    0.87
                   Science      Convo                      0.83
                                News+                      0.88
                                Science                    0.88
Llama 3.1 (0-shot) zero-shot    Convo                      0.82
                                News+                      0.88
                                Science                    0.88
PRIMERA            Convo        Convo                      0.81
                                News+                      0.81
                                Science                    0.83
                   News+        Convo                      0.81
                                News+                      0.81
                                Science                    0.82
                   Science      Convo                      0.82
                                News+                      0.81
                                Science                    0.84
SummN              Convo        Convo                      0.67
                                News+                      0.90
                                Science                    0.80
                   News+        Convo                      0.67
                                News+                      0.72
                                Science                    0.64
                   Science      Convo                      0.40
                                News+                      0.64
                                Science                    0.56
ground_truth       Convo        Convo                      0.71
                   News+        News+                      0.70
                   Science      Science                    0.55

                                             prometheus_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                         2.21
                                News+                        -1.00
                                Science                       1.94
                   News+        Convo                         1.62
                                News+                        -1.00
                                Science                       1.82
                   Science      Convo                         1.23
                                News+                        -1.00
                                Science                       1.57
Llama 3.1          Convo        Convo                         3.06
                                News+                        -1.00
                                Science                      -1.00
                   News+        Convo                         3.06
                                News+                        -1.00
                                Science                      -1.00
                   Science      Convo                         3.18
                                News+                        -1.00
                                Science                      -1.00
Llama 3.1 (0-shot) zero-shot    Convo                         3.00
                                News+                        -1.00
                                Science                      -1.00
PRIMERA            Convo        Convo                         1.45
                                News+                        -1.00
                                Science                       1.92
                   News+        Convo                         1.45
                                News+                        -1.00
                                Science                       1.93
                   Science      Convo                         1.38
                                News+                        -1.00
                                Science                       1.93
SummN              Convo        Convo                         2.45
                                News+                        -1.00
                                Science                       2.48
                   News+        Convo                         1.50
                                News+                        -1.00
                                Science                       1.59
                   Science      Convo                         1.13
                                News+                        -1.00
                                Science                       1.46
ground_truth       Convo        Convo                         3.03
                   News+        News+                        -1.00
                   Science      Science                       1.82

                                             prometheus_consistency  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                          2.25
                                News+                         -1.00
                                Science                        1.92
                   News+        Convo                          1.67
                                News+                         -1.00
                                Science                       -1.00
                   Science      Convo                          1.33
                                News+                         -1.00
                                Science                        1.57
Llama 3.1          Convo        Convo                          3.21
                                News+                         -1.00
                                Science                       -1.00
                   News+        Convo                          3.26
                                News+                         -1.00
                                Science                       -1.00
                   Science      Convo                          3.34
                                News+                         -1.00
                                Science                       -1.00
Llama 3.1 (0-shot) zero-shot    Convo                          3.26
                                News+                         -1.00
                                Science                       -1.00
PRIMERA            Convo        Convo                          1.58
                                News+                         -1.00
                                Science                        1.98
                   News+        Convo                          1.52
                                News+                         -1.00
                                Science                        1.96
                   Science      Convo                          1.53
                                News+                         -1.00
                                Science                        1.97
SummN              Convo        Convo                          2.49
                                News+                         -1.00
                                Science                        2.40
                   News+        Convo                          1.52
                                News+                         -1.00
                                Science                        1.59
                   Science      Convo                          1.24
                                News+                         -1.00
                                Science                        1.46
ground_truth       Convo        Convo                          3.13
                   News+        News+                         -1.00
                   Science      Science                        1.82

                                             unieval_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                     0.70
                                News+                     0.51
                                Science                   0.63
                   News+        Convo                     0.76
                                News+                     0.79
                                Science                   0.69
                   Science      Convo                     0.23
                                News+                     0.24
                                Science                   0.49
Llama 3.1          Convo        Convo                     0.93
                                News+                     0.92
                                Science                   0.91
                   News+        Convo                     0.93
                                News+                     0.92
                                Science                   0.91
                   Science      Convo                     0.94
                                News+                     0.93
                                Science                   0.91
Llama 3.1 (0-shot) zero-shot    Convo                     0.94
                                News+                     0.92
                                Science                   0.91
PRIMERA            Convo        Convo                     0.40
                                News+                     0.42
                                Science                   0.62
                   News+        Convo                     0.41
                                News+                     0.42
                                Science                   0.62
                   Science      Convo                     0.41
                                News+                     0.42
                                Science                   0.62
SummN              Convo        Convo                     0.72
                                News+                     0.61
                                Science                   0.67
                   News+        Convo                     0.73
                                News+                     0.77
                                Science                   0.64
                   Science      Convo                     0.31
                                News+                     0.34
                                Science                   0.49
ground_truth       Convo        Convo                     0.99
                   News+        News+                     0.98
                   Science      Science                   0.99

                                             prometheus_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                        2.44
                                News+                       -1.00
                                Science                      2.21
                   News+        Convo                        2.08
                                News+                       -1.00
                                Science                      2.18
                   Science      Convo                        1.42
                                News+                       -1.00
                                Science                      1.84
Llama 3.1          Convo        Convo                        3.35
                                News+                       -1.00
                                Science                     -1.00
                   News+        Convo                        3.41
                                News+                       -1.00
                                Science                     -1.00
                   Science      Convo                        3.46
                                News+                       -1.00
                                Science                     -1.00
Llama 3.1 (0-shot) zero-shot    Convo                        3.43
                                News+                       -1.00
                                Science                     -1.00
PRIMERA            Convo        Convo                        1.93
                                News+                       -1.00
                                Science                      2.38
                   News+        Convo                        1.98
                                News+                       -1.00
                                Science                      2.36
                   Science      Convo                        1.92
                                News+                       -1.00
                                Science                      2.36
SummN              Convo        Convo                        2.78
                                News+                       -1.00
                                Science                      2.57
                   News+        Convo                        2.00
                                News+                       -1.00
                                Science                      2.15
                   Science      Convo                        1.24
                                News+                       -1.00
                                Science                      1.65
ground_truth       Convo        Convo                        3.26
                   News+        News+                       -1.00
                   Science      Science                      2.76

                                             rouge_rouge1  rouge_rougeLsum  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo                0.31             0.21
                                News+                0.24             0.14
                                Science              0.23             0.14
                   News+        Convo                0.23             0.13
                                News+                0.45             0.23
                                Science              0.24             0.14
                   Science      Convo                0.22             0.15
                                News+                0.27             0.15
                                Science              0.28             0.16
Llama 3.1          Convo        Convo                0.22             0.15
                                News+                0.40             0.21
                                Science              0.25             0.16
                   News+        Convo                0.22             0.15
                                News+                0.40             0.21
                                Science              0.25             0.16
                   Science      Convo                0.22             0.15
                                News+                0.40             0.21
                                Science              0.25             0.16
Llama 3.1 (0-shot) zero-shot    Convo                0.22             0.15
                                News+                0.40             0.21
                                Science              0.25             0.16
PRIMERA            Convo        Convo                0.19             0.11
                                News+                0.38             0.18
                                Science              0.24             0.13
                   News+        Convo                0.19             0.11
                                News+                0.38             0.18
                                Science              0.24             0.13
                   Science      Convo                0.19             0.11
                                News+                0.38             0.18
                                Science              0.24             0.13
SummN              Convo        Convo                0.33             0.21
                                News+                0.22             0.14
                                Science              0.22             0.14
                   News+        Convo                0.22             0.12
                                News+                0.45             0.23
                                Science              0.22             0.12
                   Science      Convo                0.21             0.14
                                News+                0.30             0.16
                                Science              0.27             0.16
ground_truth       Convo        Convo               -1.00            -1.00
                   News+        News+               -1.00            -1.00
                   Science      Science             -1.00            -1.00

                                             moverscore  unieval_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        Convo              0.06             0.91
                                News+              0.00             0.90
                                Science            0.02             0.91
                   News+        Convo              0.01             0.70
                                News+              0.20             0.75
                                Science            0.04             0.82
                   Science      Convo             -0.02             0.58
                                News+              0.03             0.60
                                Science            0.04             0.69
Llama 3.1          Convo        Convo              0.05             0.93
                                News+              0.17             0.95
                                Science            0.09             0.93
                   News+        Convo              0.05             0.93
                                News+              0.17             0.95
                                Science            0.09             0.93
                   Science      Convo              0.05             0.93
                                News+              0.17             0.95
                                Science            0.09             0.93
Llama 3.1 (0-shot) zero-shot    Convo              0.05             0.92
                                News+              0.17             0.95
                                Science            0.08             0.93
PRIMERA            Convo        Convo             -0.01             0.65
                                News+              0.13             0.61
                                Science            0.06             0.80
                   News+        Convo             -0.01             0.66
                                News+              0.13             0.62
                                Science            0.06             0.79
                   Science      Convo             -0.01             0.65
                                News+              0.13             0.61
                                Science            0.06             0.80
SummN              Convo        Convo              0.09             0.90

In [7]:
a = results_df[results_df.model_type=="PRIMERA"].set_index(["model_type", "train_domain", "test_domain"]).sort_index()
a.transpose()

model_type             PRIMERA                                            \
train_domain             Convo               News+               Science
test_domain              Convo News+ Science Convo News+ Science   Convo
unieval_factuality        0.81  0.81    0.83  0.81  0.81    0.82    0.82
prometheus_factuality     1.45 -1.00    1.92  1.45 -1.00    1.93    1.38
prometheus_consistency    1.58 -1.00    1.98  1.52 -1.00    1.96    1.53
unieval_relevance         0.40  0.42    0.62  0.41  0.42    0.62    0.41
prometheus_relevance      1.93 -1.00    2.38  1.98 -1.00    2.36    1.92
rouge_rouge1              0.19  0.38    0.24  0.19  0.38    0.24    0.19
rouge_rougeLsum           0.11  0.18    0.13  0.11  0.18    0.13    0.11
moverscore               -0.01  0.13    0.06 -0.01  0.13    0.06   -0.01
unieval_fluency           0.65  0.61    0.80  0.66  0.62    0.79    0.65
prometheus_fluency        1.34 -1.00    1.83  1.29 -1.00    1.83    1.32
unieval_coherence         0.68  0.69    0.73  0.72  0.69    0.74    0.71
prometheus_coherence      1.30 -1.00    1.80  1.27 -1.00    1.80    1.27
compression_sentence      0.73  0.61    0.62  0.75  0.62    0.63    0.74
compression_token         0.59  0.52    0.53  0.63  0.52    0.53    0.62
prometheus_coverage      -1.00 -1.00   -1.00 -1.00 -1.00   -1.00   -1.00

model_type
train_domain
test_domain            News+ Science
unieval_factuality      0.81    0.84
prometheus_factuality  -1.00    1.93
prometheus_consistency -1.00    1.97
unieval_relevance       0.42    0.62
prometheus_relevance   -1.00    2.36
rouge_rouge1            0.38    0.24
rouge_rougeLsum         0.18    0.13
moverscore              0.13    0.06
unieval_fluency         0.61    0.80
prometheus_fluency     -1.00    1.82
unieval_coherence       0.70    0.74
prometheus_coherence   -1.00    1.79
compression_sentence    0.62    0.62
compression_token       0.52    0.53
prometheus_coverage    -1.00   -1.00

# Q: How well is each model trained _on its domain_?

In [8]:
# Limit to models where the model is trained and tested on the same domain
same_domain_analysis = results_df[
    results_df.apply(lambda x: x.train_domain==x.test_domain, axis="columns")
].sort_values(by=["train_domain", "test_domain"])
same_domain_analysis = same_domain_analysis.loc[:, ["train_domain", "test_domain", "model_type"]+wanted_metrics]

same_domain_performance_dict = same_domain_analysis.set_index(["train_domain", "model_type"])[wanted_metrics].to_dict(orient="index")
same_domain_performance_dict

{('Convo', 'ground_truth'): {'unieval_factuality': 0.7127423688060528,
  'prometheus_factuality': 3.032,
  'prometheus_consistency': 3.128,
  'unieval_relevance': 0.9855425109640278,
  'prometheus_relevance': 3.256,
  'rouge_rouge1': -1.0,
  'rouge_rougeLsum': -1.0,
  'moverscore': 0.9999999998240994,
  'unieval_fluency': 0.8962882354893531,
  'prometheus_fluency': 3.276,
  'unieval_coherence': 0.729176020702826,
  'prometheus_coherence': 3.484,
  'compression_sentence': 0.8975773848277229,
  'compression_token': 0.8507181864684161,
  'prometheus_coverage': -1},
 ('Convo', 'PRIMERA'): {'unieval_factuality': 0.8141133978258701,
  'prometheus_factuality': 1.448,
  'prometheus_consistency': 1.58,
  'unieval_relevance': 0.4026709201737799,
  'prometheus_relevance': 1.932,
  'rouge_rouge1': 0.19090370176435598,
  'rouge_rougeLsum': 0.10950630435403477,
  'moverscore': -0.011266764867552136,
  'unieval_fluency': 0.653483834363345,
  'prometheus_fluency': 1.344,
  'unieval_coherence': 0.6785566981288893,
  'prometheus_coherence': 1.3,
  'compression_sentence': 0.7287997128620931,
  'compression_token': 0.5931245837807413,
  'prometheus_coverage': -1},
 ('Convo', 'SummN'): {'unieval_factuality': 0.6687359019524167,
  'prometheus_factuality': 2.452,
  'prometheus_consistency': 2.488,
  'unieval_relevance': 0.721239959036231,
  'prometheus_relevance': 2.78,
  'rouge_rouge1': 0.3283046202063834,
  'rouge_rougeLsum': 0.2115447509592777,
  'moverscore': 0.0881386757123108,
  'unieval_fluency': 0.9002777298290198,
  'prometheus_fluency': 2.9,
  'unieval_coherence': 0.7051515199178011,
  'prometheus_coherence': 2.792,
  'compression_sentence': 0.9039834313814925,
  'compression_token': 0.8646015878685502,
  'prometheus_coverage': -1},
 ('Convo', 'ConvoSumm'): {'unieval_factuality': 0.6448624135535097,
  'prometheus_factuality': 2.208,
  'prometheus_consistency': 2.248,
  'unieval_relevance': 0.6982185812416573,
  'prometheus_relevance': 2.44,
  'rouge_rouge1': 0.3087363026153122,
  'rouge_rougeLsum': 0.21095126798276165,
  'moverscore': 0.0556925312999886,
  'unieval_fluency': 0.9145819456531356,
  'prometheus_fluency': 2.672,
  'unieval_coherence': 0.5996400811017836,
  'prometheus_coherence': 2.488,
  'compression_sentence': 0.9137200475966535,
  'compression_token': 0.9062447934029834,
  'prometheus_coverage': -1},
 ('Convo', 'Llama 3.1'): {'unieval_factuality': 0.8293128602376093,
  'prometheus_factuality': 3.056,
  'prometheus_consistency': 3.208,
  'unieval_relevance': 0.934634138643386,
  'prometheus_relevance': 3.352,
  'rouge_rouge1': 0.21726066097783,
  'rouge_rougeLsum': 0.1485878001528681,
  'moverscore': 0.05415170136549754,
  'unieval_fluency': 0.9301205566803956,
  'prometheus_fluency': 3.996,
  'unieval_coherence': 0.9465057487323737,
  'prometheus_coherence': 3.984,
  'compression_sentence': 0.7546778332444135,
  'compression_token': 0.5219121290141513,
  'prometheus_coverage': -1},
 ('News+', 'ground_truth'): {'unieval_factuality': 0.7021388165720657,
  'prometheus_factuality': -1.0,
  'prometheus_consistency': -1.0,
  'unieval_relevance': 0.9838956641985479,
  'prometheus_relevance': -1.0,
  'rouge_rouge1': -1.0,
  'rouge_rougeLsum': -1.0,
  'moverscore': 0.9999999995582165,
  'unieval_fluency': 0.7629286777042384,
  'prometheus_fluency': -1.0,
  'unieval_coherence': 0.7504257127268541,
  'prometheus_coherence': -1.0,
  'compression_sentence': 0.4071464503226384,
  'compression_token': 0.4102168245725881,
  'prometheus_coverage': -1},
 ('News+', 'PRIMERA'): {'unieval_factuality': 0.8108116383445838,
  'prometheus_factuality': -1.0,
  'prometheus_consistency': -1.0,
  'unieval_relevance': 0.42364773902920466,
  'prometheus_relevance': -1.0,
  'rouge_rouge1': 0.37573769754256947,
  'rouge_rougeLsum': 0.18279577594057803,
  'moverscore': 0.12849270914460972,
  'unieval_fluency': 0.6160409789129923,
  'prometheus_fluency': -1.0,
  'unieval_coherence': 0.6927002286501525,
  'prometheus_coherence': -1.0,
  'compression_sentence': 0.6176065952020873,
  'compression_token': 0.5239991367487066,
  'prometheus_coverage': -1},
 ('News+', 'SummN'): {'unieval_factuality': 0.7249645377410711,
  'prometheus_factuality': -1.0,
  'prometheus_consistency': -1.0,
  'unieval_relevance': 0.7729062743057776,
  'prometheus_relevance': -1.0,
  'rouge_rouge1': 0.44886880582847893,
  'rouge_rougeLsum': 0.22687451095831926,
  'moverscore': 0.18972497082777856,
  'unieval_fluency': 0.7297443219624584,
  'prometheus_fluency': -1.0,
  'unieval_coherence': 0.7963017179368185,
  'prometheus_coherence': -1.0,
  'compression_sentence': 0.4454726282848448,
  'compression_token': 0.49529309338285776,
  'prometheus_coverage': -1},
 ('News+', 'ConvoSumm'): {'unieval_factuality': 0.7753847037887037,
  'prometheus_factuality': -1.0,
  'prometheus_consistency': -1.0,
  'unieval_relevance': 0.794853197114234,
  'prometheus_relevance': -1.0,
  'rouge_rouge1': 0.4533680919961548,
  'rouge_rougeLsum': 0.22964031636124188,
  'moverscore': 0.19757044789092731,
  'unieval_fluency': 0.7497246372593714,
  'prometheus_fluency': -1.0,
  'unieval_coherence': 0.8247894365782651,
  'prometheus_coherence': -1.0,
  'compression_sentence': 0.48125052299165694,
  'compression_token': 0.5405493341023895,
  'prometheus_coverage': -1},
 ('News+', 'Llama 3.1'): {'unieval_factuality': 0.8757863148992501,
  'prometheus_factuality': -1.0,
  'prometheus_consistency': -1.0,
  'unieval_relevance': 0.9226427390499994,
  'prometheus_relevance': -1.0,
  'rouge_rouge1': 0.39915204823535766,
  'rouge_rougeLsum': 0.2084806805030425,
  'moverscore': 0.17027895316360347,
  'unieval_fluency': 0.9455837404878712,
  'prometheus_fluency': -1.0,
  'unieval_coherence': 0.9407279283903512,
  'prometheus_coherence': -1.0,
  'compression_sentence': 0.6637467141170417,
  'compression_token': 0.6164416914837836,
  'prometheus_coverage': -1},
 ('Science', 'ground_truth'): {'unieval_factuality': 0.55045862527962,
  'prometheus_factuality': 1.8211467648605997,
  'prometheus_consistency': 1.8164124145186744,
  'unieval_relevance': 0.9882119079711595,
  'prometheus_relevance': 2.756443976854287,
  'rouge_rouge1': -1.0,
  'rouge_rougeLsum': -1.0,
  'moverscore': 0.9999999997891768,
  'unieval_fluency': 0.6562540899402792,
  'prometheus_fluency': 1.555263157894737,
  'unieval_coherence': 0.4282043861720864,
  'prometheus_coherence': 1.4913203577064702,
  'compression_sentence': 0.7440322347438837,
  'compression_token': 0.7505390293184523,
  'prometheus_coverage': -1},
 ('Science', 'PRIMERA'): {'unieval_factuality': 0.8366287492796465,
  'prometheus_factuality': 1.926880589163598,
  'prometheus_consistency': 1.9726459758022095,
  'unieval_relevance': 0.6241064763071182,
  'prometheus_relevance': 2.3566543924250394,
  'rouge_rouge1': 0.23688497365432626,
  'rouge_rougeLsum': 0.12837742040531852,
  'moverscore': 0.056508674120430376,
  'unieval_fluency': 0.7976249544182612,
  'prometheus_fluency': 1.822198842714361,
  'unieval_coherence': 0.7425832964559569,
  'prometheus_coherence': 1.79,
  'compression_sentence': 0.6248871313395181,
  'compression_token': 0.5295176766417264,
  'prometheus_coverage': -1},
 ('Science', 'SummN'): {'unieval_factuality': 0.5607964451540886,
  'prometheus_factuality': 1.460810099947396,
  'prometheus_consistency': 1.4587059442398738,
  'unieval_relevance': 0.4891150263822156,
  'prometheus_relevance': 1.6538663861125724,
  'rouge_rouge1': 0.2704868462859804,
  'rouge_rougeLsum': 0.1586456830855186,
  'moverscore': 0.0314418141590443,
  'unieval_fluency': 0.6614301551765296,
  'prometheus_fluency': 1.4050499736980537,
  'unieval_coherence': 0.38809930470529586,
  'prometheus_coherence': 1.4013677012098895,
  'compression_sentence': 0.7139938403453768,
  'compression_token': 0.7430644663393476,
  'prometheus_coverage': -1},
 ('Science', 'ConvoSumm'): {'unieval_factuality': 0.6019692657086441,
  'prometheus_factuality': 1.5718043135192004,
  'prometheus_consistency': 1.5728563913729616,
  'unieval_relevance': 0.4949875539961723,
  'prometheus_relevance': 1.842714360862704,
  'rouge_rouge1': 0.276839807129176,
  'rouge_rougeLsum': 0.1628495558898957,
  'moverscore': 0.03755076071382911,
  'unieval_fluency': 0.6915942894546336,
  'prometheus_fluency': 1.4726315789473685,
  'unieval_coherence': 0.3776514048580986,
  'prometheus_coherence': 1.4676486059968437,
  'compression_sentence': 0.7243905232188972,
  'compression_token': 0.7879207070605768,
  'prometheus_coverage': -1},
 ('Science', 'Llama 3.1'): {'unieval_factuality': 0.8792726316352584,
  'prometheus_factuality': -1.0,
  'prometheus_consistency': -1.0,
  'unieval_relevance': 0.9066348814632683,
  'prometheus_relevance': -1.0,
  'rouge_rouge1': 0.25232526442097347,
  'rouge_rougeLsum': 0.1607985538679003,
  'moverscore': 0.08562996568435156,
  'unieval_fluency': 0.9327652744111913,
  'prometheus_fluency': -1.0,
  'unieval_coherence': 0.9743348514048105,
  'prometheus_coherence': -1.0,
  'compression_sentence': 0.5151095767006247,
  'compression_token': 0.5060347532903011,
  'prometheus_coverage': -1}}

In [9]:
a = same_domain_analysis.set_index(["model_type"]).sort_index()
print(a.to_csv())
a

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,Convo,0.6448624135535097,2.208,2.248,0.6982185812416573,2.44,0.3087363026153122,0.21095126798276165,0.0556925312999886,0.9145819456531356,2.672,0.5996400811017836,2.488,0.9137200475966535,0.9062447934029834,-1
ConvoSumm,News+,News+,0.7753847037887037,-1.0,-1.0,0.794853197114234,-1.0,0.4533680919961548,0.22964031636124188,0.19757044789092731,0.7497246372593714,-1.0,0.8247894365782651,-1.0,0.48125052299165694,0.5405493341023895,-1
ConvoSumm,Science,Science,0.6019692657086441,1.5718043135192004,1.5728563913729616,0.4949875539961723,1.842714360862704,0.276839807129176,0.1628495558898957,0.03755076071382911,0.6915942894546336,1.4726315789473685,0.3776514048580986,1.4676486059968437,0.7243905232188972,0.7879207070605768,-1
Llama 3.1,Convo,Convo,0.8293128602376093,3.056,3.208,0.934634138643386,3.352,0.21726066097783,0.1485878001528681,0.05415170136549754,0.9301205566803956,3.996,0.9465057487323737,3.984,0.7546778332444135,0.5219121290141513,-1
Llama 3.1,News+,News+,0.8757863148992501,-1.0,-1.0,0.9226427390499994,-1.0,0.39915204823535766,0.2084806805030425,0.17027895316360347,0.9455837404878712,-1.0,0.9407279283903512,-1.0,0.6637467141170417,0.6164416914837836,-1
Llama 3.1,Science,Science,0.8792726316352584,-1.0,-1.0,0.9066348814632683,-1.0,0.25232526442097347,0.1607985538679003,0.08562996568435156,0.9327652744111913,-1.0,0.9743348514048105,-1.0,0.5151095767006247,0.5060347532903011,-1
PRIMERA,Convo,Convo,0.8141133978258701,1.448,1.58,0.4026709201737799,1.932,0.19090370176435598,0.10950630435403477,-0.011266764867552136,0.653483834363345,1.344,0.6785566981288893,1.3,0.7287997128620931,0.5931245837807413,-1
PRIMERA,News+,News+,0.8108116383445838,-1.0,-1.0,0.42364773902920466,-1.0,0.37573769754256947,0.18279577594057803,0.12849270914460972,0.6160409789129923,-1.0,0.6927002286501525,-1.0,0.6176065952020873,0.5239991367487066,-1
PRIMERA,Science,Science,0.8366287492796465,1.926880589163598,1.9726459758022095,0.6241064763071182,2.3566543924250394,0.23688497365432626,0.12837742040531852,0.056508674120430376,0.7976249544182612,1.822198842714361,0.7425832964559569,1.79,0.6248871313395181,0.5295176766417264,-1
SummN,Convo,Convo,0.6687359019524167,2.452,2.488,0.721239959036231,2.78,0.3283046202063834,0.2115447509592777,0.0881386757123108,0.9002777298290198,2.9,0.7051515199178011,2.792,0.9039834313814925,0.8646015878685502,-1
SummN,News+,News+,0.7249645377410711,-1.0,-1.0,0.7729062743057776,-1.0,0.44886880582847893,0.22687451095831926,0.18972497082777856,0.7297443219624584,-1.0,0.7963017179368185,-1.0,0.4454726282848448,0.49529309338285776,-1
SummN,Science,Science,0.5607964451540886,1.460810099947396,1.4587059442398738,0.4891150263822156,1.6538663861125724,0.2704868462859804,0.1586456830855186,0.0314418141590443,0.6614301551765296,1.4050499736980537,0.38809930470529586,1.4013677012098895,0.7139938403453768,0.7430644663393476,-1
ground_truth,Convo,Convo,0.7127423688060528,3.032,3.128,0.9855425109640278,3.256,-1.0,-1.0,0.9999999998240994,0.8962882354893531,3.276,0.729176020702826,3.484,0.8975773848277229,0.8507181864684161,-1
ground_truth,News+,News+,0.7021388165720657,-1.0,-1.0,0.9838956641985479,-1.0,-1.0,-1.0,0.9999999995582165,0.7629286777042384,-1.0,0.7504257127268541,-1.0,0.4071464503226384,0.4102168245725881,-1
ground_truth,Science,Science,0.55045862527962,1.8211467648605997,1.8164124145186744,0.9882119079711595,2.756443976854287,-1.0,-1.0,0.9999999997891768,0.6562540899402792,1.555263157894737,0.4282043861720864,1.4913203577064702,0.7440322347438837,0.7505390293184523,-1

,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
model_type,,,,,,,,,,,,,,,,,
ConvoSumm,Convo,Convo,0.64,2.21,2.25,0.70,2.44,0.31,0.21,0.06,0.91,2.67,0.60,2.49,0.91,0.91,-1
ConvoSumm,News+,News+,0.78,-1.00,-1.00,0.79,-1.00,0.45,0.23,0.20,0.75,-1.00,0.82,-1.00,0.48,0.54,-1
ConvoSumm,Science,Science,0.60,1.57,1.57,0.49,1.84,0.28,0.16,0.04,0.69,1.47,0.38,1.47,0.72,0.79,-1
Llama 3.1,Convo,Convo,0.83,3.06,3.21,0.93,3.35,0.22,0.15,0.05,0.93,4.00,0.95,3.98,0.75,0.52,-1
Llama 3.1,News+,News+,0.88,-1.00,-1.00,0.92,-1.00,0.40,0.21,0.17,0.95,-1.00,0.94,-1.00,0.66,0.62,-1
Llama 3.1,Science,Science,0.88,-1.00,-1.00,0.91,-1.00,0.25,0.16,0.09,0.93,-1.00,0.97,-1.00,0.52,0.51,-1
PRIMERA,Convo,Convo,0.81,1.45,1.58,0.40,1.93,0.19,0.11,-0.01,0.65,1.34,0.68,1.30,0.73,0.59,-1
PRIMERA,News+,News+,0.81,-1.00,-1.00,0.42,-1.00,0.38,0.18,0.13,0.62,-1.00,0.69,-1.00,0.62,0.52,-1
PRIMERA,Science,Science,0.84,1.93,1.97,0.62,2.36,0.24,0.13,0.06,0.80,1.82,0.74,1.79,0.62,0.53,-1
SummN,Convo,Convo,0.67,2.45,2.49,0.72,2.78,0.33,0.21,0.09,0.90,2.90,0.71,2.79,0.90,0.86,-1
SummN,News+,News+,0.72,-1.00,-1.00,0.77,-1.00,0.45,0.23,0.19,0.73,-1.00,0.80,-1.00,0.45,0.50,-1
SummN,Science,Science,0.56,1.46,1.46,0.49,1.65,0.27,0.16,0.03,0.66,1.41,0.39,1.40,0.71,0.74,-1
ground_truth,Convo,Convo,0.71,3.03,3.13,0.99,3.26,-1.00,-1.00,1.00,0.90,3.28,0.73,3.48,0.90,0.85,-1
ground_truth,News+,News+,0.70,-1.00,-1.00,0.98,-1.00,-1.00,-1.00,1.00,0.76,-1.00,0.75,-1.00,0.41,0.41,-1
ground_truth,Science,Science,0.55,1.82,1.82,0.99,2.76,-1.00,-1.00,1.00,0.66,1.56,0.43,1.49,0.74,0.75,-1

In [10]:
a = same_domain_analysis.groupby(["model_type"]).mean(numeric_only=True).to_csv(float_format='%.2f')
print(a)

model_type,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,0.67,0.93,0.94,0.66,1.09,0.35,0.20,0.10,0.79,1.05,0.60,0.99,0.71,0.74,-1.00
Llama 3.1,0.86,0.35,0.40,0.92,0.45,0.29,0.17,0.10,0.94,0.67,0.95,0.66,0.64,0.55,-1.00
PRIMERA,0.82,0.79,0.85,0.48,1.10,0.27,0.14,0.06,0.69,0.72,0.70,0.70,0.66,0.55,-1.00
SummN,0.65,0.97,0.98,0.66,1.14,0.35,0.20,0.10,0.76,1.10,0.63,1.06,0.69,0.70,-1.00
ground_truth,0.66,1.28,1.31,0.99,1.67,-1.00,-1.00,1.00,0.77,1.28,0.64,1.33,0.68,0.67,-1.00

In [11]:
a = same_domain_analysis[same_domain_analysis.model_type!='ground_truth'].groupby(["train_domain"]).mean(numeric_only=True)
print(a.to_csv(float_format='%.2f'))
a

train_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,0.74,2.29,2.38,0.69,2.63,0.26,0.17,0.05,0.85,2.73,0.73,2.64,0.83,0.72,-1.00
News+,0.80,-1.00,-1.00,0.73,-1.00,0.42,0.21,0.17,0.76,-1.00,0.81,-1.00,0.55,0.54,-1.00
Science,0.72,0.99,1.00,0.63,1.21,0.26,0.15,0.05,0.77,0.92,0.62,0.91,0.64,0.64,-1.00

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
train_domain,,,,,,,,,,,,,,,
Convo,0.74,2.29,2.38,0.69,2.63,0.26,0.17,0.05,0.85,2.73,0.73,2.64,0.83,0.72,-1.00
News+,0.80,-1.00,-1.00,0.73,-1.00,0.42,0.21,0.17,0.76,-1.00,0.81,-1.00,0.55,0.54,-1.00
Science,0.72,0.99,1.00,0.63,1.21,0.26,0.15,0.05,0.77,0.92,0.62,0.91,0.64,0.64,-1.00

# Q: Which train domain transfers the best to other domains?

Limit to models that are trained and tested on _different_ domains. Also, focus on performance _loss_ versus absolute performance.

In [12]:
cross_performance = results_df[results_df.train_domain!=results_df.test_domain].groupby(["model_type", "train_domain", "test_domain"]).mean(numeric_only=True)
print(cross_performance.to_csv())
cross_performance

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,News+,0.7591189466775365,-1.0,-1.0,0.5070198568057779,-1.0,0.2362862336067719,0.13624412376100595,0.004544066298236168,0.904482613918518,-1.0,0.578362022112479,-1.0,0.7661639042019806,0.8441804327242147,-1.0
ConvoSumm,Convo,Science,0.6820770616738082,1.9426617569700158,1.9200420831141505,0.634548276780649,2.2051551814834296,0.23137961259831868,0.14082646645653718,0.015661103842486895,0.9081399542147147,2.17,0.6100838214473558,2.054708048395581,0.7586574122367228,0.8454746007797356,-1.0
ConvoSumm,News+,Convo,0.6969226520006567,1.62,1.672,0.7576750387866421,2.084,0.22889761798768465,0.13203723709223633,0.007668224319735004,0.6989360899262449,1.788,0.7797604320135647,1.804,0.7079845309360377,0.6203451575350976,-1.0
ConvoSumm,News+,Science,0.7063910350503003,1.8185165702261967,-1.0,0.6870642432492403,2.183061546554445,0.24330394389189694,0.13518735384187006,0.03695954493053294,0.8198442285005005,-1.0,0.6946589832272637,-1.0,0.5514950696109786,0.549483094225437,-1.0
ConvoSumm,Science,Convo,0.4617297742821378,1.228,1.332,0.23271219252501094,1.416,0.2235655306350553,0.1486729403462277,-0.016819702861070204,0.5827484736665433,1.316,0.2481154905642099,1.244,0.8724367507391996,0.8461182867710596,-1.0
ConvoSumm,Science,News+,0.6426782550307031,-1.0,-1.0,0.24302195732095674,-1.0,0.27494963663668565,0.15086251300733383,0.026115497854861728,0.5980993408557658,-1.0,0.27686873779432425,-1.0,0.6945803435166078,0.7543613537061177,-1.0
Llama 3.1,Convo,News+,0.8772738215718944,-1.0,-1.0,0.9239128568875826,-1.0,0.3991654936227255,0.2079853221547263,0.16985727220340305,0.9457021710047753,-1.0,0.9413737675997482,-1.0,0.6632432254105483,0.6160505174485185,-1.0
Llama 3.1,Convo,Science,0.8767284858274194,-1.0,-1.0,0.9091577071305708,-1.0,0.25169365003438293,0.16035779814224074,0.0852727013682428,0.9323176404327689,-1.0,0.9748777957110383,-1.0,0.5105315133123904,0.5059392347267114,-1.0
Llama 3.1,News+,Convo,0.819466075657547,3.064,3.26,0.9260614043490659,3.408,0.21774335218872248,0.15078452592023836,0.05288234813291655,0.9259264612256323,4.056,0.9465020476069789,3.956,0.7597607844094705,0.5340832916926685,-1.0
Llama 3.1,News+,Science,0.8737927356863194,-1.0,-1.0,0.9068721659354867,-1.0,0.25211526560454406,0.1610419324787793,0.08512078649101783,0.9312781575366971,-1.0,0.9746455200689392,-1.0,0.5129197098541656,0.5081362740177942,-1.0
Llama 3.1,Science,Convo,0.8321209220314464,3.184,3.344,0.936102994130565,3.456,0.2183295164532743,0.1522917935009776,0.051655278530188406,0.9292361575339999,4.004,0.9565184340769218,3.98,0.7551900660307197,0.5299973794103133,-1.0
Llama 3.1,Science,News+,0.8760518716349264,-1.0,-1.0,0.92607655783454,-1.0,0.40000608867435755,0.20864419370195225,0.17031794028515232,0.9454708330626617,-1.0,0.9430708285925352,-1.0,0.6637625199171601,0.6160091130445629,-1.0
Llama 3.1 (0-shot),zero-shot,Convo,0.8235807328053706,3.0,3.264,0.938935429717467,3.432,0.21762819392411628,0.15136805147565885,0.05226800525909331,0.9228467945266261,4.044,0.9558145040645584,3.9477911646586343,0.7538778181857138,0.5269606982650294,-1.0
Llama 3.1 (0-shot),zero-shot,News+,0.8761273402937058,-1.0,-1.0,0.9230360725692248,-1.0,0.40028052172794915,0.20851112847127204,0.17013120581633248,0.945503627261112,-1.0,0.9430338471465219,-1.0,0.66210247150434,0.6145266249086963,-1.0
Llama 3.1 (0-shot),zero-shot,Science,0.8764178336159618,-1.0,-1.0,0.9096595897836528,-1.0,0.25154956513408294,0.1601850700986622,0.08455961033200289,0.9310134633220987,-1.0,0.974102419969262,-1.0,0.5118945403382675,0.5054961935855675,-1.0
PRIMERA,Convo,News+,0.8115263062414987,-1.0,-1.0,0.41770475502522497,-1.0,0.3753441903457188,0.18166928507188262,0.1288319665754916,0.6141843397615123,-1.0,0.6902997082473988,-1.0,0.6133956738487125,0.5206358779033206,-1.0
PRIMERA,Convo,Science,0.8279150619180969,1.9189900052603892,1.9810625986322987,0.6159065825737439,2.3819042609153076,0.23680766971630415,0.12852011307148295,0.05632228577116426,0.7982658418366751,1.8290373487638085,0.7320596817116752,1.8037874802735403,0.6219192025417015,0.5262088307352697,-1.0
PRIMERA,News+,Convo,0.8147320976475728,1.448,1.524,0.4138055885413465,1.976,0.19086589465822362,0.10797682122957636,-0.008816298656657522,0.6590897341009271,1.292,0.7218283377940676,1.268,0.7472310205931197,0.63310007453348,-1.0
PRIMERA,News+,Science,0.8221627187076286,1.926880589163598,1.958968963703314,0.6178632595654353,2.3550762756443975,0.23738774866027443,0.12933725998944662,0.05747148531144757,0.7949410102925166,1.8274592319831668,0.7370393901369133,1.804313519200421,0.6262231476965358,0.5271053613585057,-1.0
PRIMERA,Science,Convo,0.8163320307482079,1.38,1.532,0.41159340954326773,1.924,0.18973044222654079,0.10692430429929005,-0.010071704667393162,0.6546385996429588,1.324,0.7093129559967128,1.268,0.7381540561143534,0.6189295831397095,-1.0
PRIMERA,Science,News+,0.8149519316779871,-1.0,-1.0,0.422179366085479,-1.0,0.37533599972867143,0.18209110893226418,0.12966868423997788,0.614054042805059,-1.0,0.6977969009957463,-1.0,0.6150244923764756,0.5243682962700023,-1.0
SummN,Convo,News+,0.8979949316981427,-1.0,-1.0,0.6127181726316369,-1.0,0.2211795840498392,0.13561883122373067,0.006419333561151065,0.8935660314297892,-1.0,0.81998778476022,-1.0,0.8335354487019777,0.8814731980083208,-1.0
SummN,Convo,Science,0.8011175502696011,2.482903734876381,2.40189374013677,0.6654785874150559,2.5707522356654393,0.22093033767192236,0.13756916440018638,0.021630450384621885,0.9136190021693738,2.6042105263157893,0.8643821702455704,2.396633350867964,0.8367287345586436,0.8803171929668842,-1.0
SummN,News+,Convo,0.6686588312620276,1.496,1.524,0.7333456167075528,2.0,0.21813663004959075,0.12472487255249123,0.005998167585050731,0.6948843133952471,1.72,0.7543788159230769,1.72,0.7031625481147903,0.5605720915272108,-1.0
SummN,News+,Science,0.6360290685994071,1.5854813256180957,1.592845870594424,0.6449768073112823,2.1467648605996845,0.2182136215252666,0.1237182966929663,0.030926395288957183,0.7698698036215211,1.6754339821146764,0.6814674553814292,1.7243556023145712,0.4264667048776194,0.394350621021509,-1.0
SummN,Science,Convo,0.39735188601941535,1.128,1.24,0.30707204503361996,1.244,0.20785781162731312,0.14022431166695445,-0.03411900121682135,0.6179043142961055,1.3,0.3049961284978852,1.244,0.8430036078120141,0.7540810253578845,-1.0
SummN,Science,News+,0.6373750117124984,-1.0,-1.0,0.3365213750729129,-1.0,0.2975840998841973,0.16275760495940098,0.04033832604298621,0.6992860724006253,-1.0,0.3535934210365862,-1.0,0.684334246052862,0.7344428932103636,-1.0

                                             unieval_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                      0.76
                                Science                    0.68
                   News+        Convo                      0.70
                                Science                    0.71
                   Science      Convo                      0.46
                                News+                      0.64
Llama 3.1          Convo        News+                      0.88
                                Science                    0.88
                   News+        Convo                      0.82
                                Science                    0.87
                   Science      Convo                      0.83
                                News+                      0.88
Llama 3.1 (0-shot) zero-shot    Convo                      0.82
                                News+                      0.88
                                Science                    0.88
PRIMERA            Convo        News+                      0.81
                                Science                    0.83
                   News+        Convo                      0.81
                                Science                    0.82
                   Science      Convo                      0.82
                                News+                      0.81
SummN              Convo        News+                      0.90
                                Science                    0.80
                   News+        Convo                      0.67
                                Science                    0.64
                   Science      Convo                      0.40
                                News+                      0.64

                                             prometheus_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                        -1.00
                                Science                       1.94
                   News+        Convo                         1.62
                                Science                       1.82
                   Science      Convo                         1.23
                                News+                        -1.00
Llama 3.1          Convo        News+                        -1.00
                                Science                      -1.00
                   News+        Convo                         3.06
                                Science                      -1.00
                   Science      Convo                         3.18
                                News+                        -1.00
Llama 3.1 (0-shot) zero-shot    Convo                         3.00
                                News+                        -1.00
                                Science                      -1.00
PRIMERA            Convo        News+                        -1.00
                                Science                       1.92
                   News+        Convo                         1.45
                                Science                       1.93
                   Science      Convo                         1.38
                                News+                        -1.00
SummN              Convo        News+                        -1.00
                                Science                       2.48
                   News+        Convo                         1.50
                                Science                       1.59
                   Science      Convo                         1.13
                                News+                        -1.00

                                             prometheus_consistency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                         -1.00
                                Science                        1.92
                   News+        Convo                          1.67
                                Science                       -1.00
                   Science      Convo                          1.33
                                News+                         -1.00
Llama 3.1          Convo        News+                         -1.00
                                Science                       -1.00
                   News+        Convo                          3.26
                                Science                       -1.00
                   Science      Convo                          3.34
                                News+                         -1.00
Llama 3.1 (0-shot) zero-shot    Convo                          3.26
                                News+                         -1.00
                                Science                       -1.00
PRIMERA            Convo        News+                         -1.00
                                Science                        1.98
                   News+        Convo                          1.52
                                Science                        1.96
                   Science      Convo                          1.53
                                News+                         -1.00
SummN              Convo        News+                         -1.00
                                Science                        2.40
                   News+        Convo                          1.52
                                Science                        1.59
                   Science      Convo                          1.24
                                News+                         -1.00

                                             unieval_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     0.51
                                Science                   0.63
                   News+        Convo                     0.76
                                Science                   0.69
                   Science      Convo                     0.23
                                News+                     0.24
Llama 3.1          Convo        News+                     0.92
                                Science                   0.91
                   News+        Convo                     0.93
                                Science                   0.91
                   Science      Convo                     0.94
                                News+                     0.93
Llama 3.1 (0-shot) zero-shot    Convo                     0.94
                                News+                     0.92
                                Science                   0.91
PRIMERA            Convo        News+                     0.42
                                Science                   0.62
                   News+        Convo                     0.41
                                Science                   0.62
                   Science      Convo                     0.41
                                News+                     0.42
SummN              Convo        News+                     0.61
                                Science                   0.67
                   News+        Convo                     0.73
                                Science                   0.64
                   Science      Convo                     0.31
                                News+                     0.34

                                             prometheus_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -1.00
                                Science                      2.21
                   News+        Convo                        2.08
                                Science                      2.18
                   Science      Convo                        1.42
                                News+                       -1.00
Llama 3.1          Convo        News+                       -1.00
                                Science                     -1.00
                   News+        Convo                        3.41
                                Science                     -1.00
                   Science      Convo                        3.46
                                News+                       -1.00
Llama 3.1 (0-shot) zero-shot    Convo                        3.43
                                News+                       -1.00
                                Science                     -1.00
PRIMERA            Convo        News+                       -1.00
                                Science                      2.38
                   News+        Convo                        1.98
                                Science                      2.36
                   Science      Convo                        1.92
                                News+                       -1.00
SummN              Convo        News+                       -1.00
                                Science                      2.57
                   News+        Convo                        2.00
                                Science                      2.15
                   Science      Convo                        1.24
                                News+                       -1.00

                                             rouge_rouge1  rouge_rougeLsum  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                0.24             0.14
                                Science              0.23             0.14
                   News+        Convo                0.23             0.13
                                Science              0.24             0.14
                   Science      Convo                0.22             0.15
                                News+                0.27             0.15
Llama 3.1          Convo        News+                0.40             0.21
                                Science              0.25             0.16
                   News+        Convo                0.22             0.15
                                Science              0.25             0.16
                   Science      Convo                0.22             0.15
                                News+                0.40             0.21
Llama 3.1 (0-shot) zero-shot    Convo                0.22             0.15
                                News+                0.40             0.21
                                Science              0.25             0.16
PRIMERA            Convo        News+                0.38             0.18
                                Science              0.24             0.13
                   News+        Convo                0.19             0.11
                                Science              0.24             0.13
                   Science      Convo                0.19             0.11
                                News+                0.38             0.18
SummN              Convo        News+                0.22             0.14
                                Science              0.22             0.14
                   News+        Convo                0.22             0.12
                                Science              0.22             0.12
                   Science      Convo                0.21             0.14
                                News+                0.30             0.16

                                             moverscore  unieval_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+              0.00             0.90
                                Science            0.02             0.91
                   News+        Convo              0.01             0.70
                                Science            0.04             0.82
                   Science      Convo             -0.02             0.58
                                News+              0.03             0.60
Llama 3.1          Convo        News+              0.17             0.95
                                Science            0.09             0.93
                   News+        Convo              0.05             0.93
                                Science            0.09             0.93
                   Science      Convo              0.05             0.93
                                News+              0.17             0.95
Llama 3.1 (0-shot) zero-shot    Convo              0.05             0.92
                                News+              0.17             0.95
                                Science            0.08             0.93
PRIMERA            Convo        News+              0.13             0.61
                                Science            0.06             0.80
                   News+        Convo             -0.01             0.66
                                Science            0.06             0.79
                   Science      Convo             -0.01             0.65
                                News+              0.13             0.61
SummN              Convo        News+              0.01             0.89
                                Science            0.02             0.91
                   News+        Convo              0.01             0.69
                                Science            0.03             0.77
                   Science      Convo             -0.03             0.62
                                News+              0.04             0.70

                                             prometheus_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     -1.00
                                Science                    2.17
                   News+        Convo                      1.79
                                Science                   -1.00
                   Science      Convo                      1.32
                                News+                     -1.00
Llama 3.1          Convo        News+                     -1.00
                                Science                   -1.00
                   News+        Convo                      4.06
                                Science                   -1.00
                   Science      Convo                      4.00
                                News+                     -1.00
Llama 3.1 (0-shot) zero-shot    Convo                      4.04
                                News+                     -1.00
                                Science                   -1.00
PRIMERA            Convo        News+                     -1.00
                                Science                    1.83
                   News+        Convo                      1.29
                                Science                    1.83
                   Science      Convo                      1.32
                                News+                     -1.00
SummN              Convo        News+                     -1.00
                                Science                    2.60
                   News+        Convo                      1.72
                                Science                    1.68
                   Science      Convo                      1.30
                                News+                     -1.00

                                             unieval_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     0.58
                                Science                   0.61
                   News+        Convo                     0.78
                                Science                   0.69
                   Science      Convo                     0.25
                                News+                     0.28
Llama 3.1          Convo        News+                     0.94
                                Science                   0.97
                   News+        Convo                     0.95
                                Science                   0.97
                   Science      Convo                     0.96
                                News+                     0.94
Llama 3.1 (0-shot) zero-shot    Convo                     0.96
                                News+                     0.94
                                Science                   0.97
PRIMERA            Convo        News+                     0.69
                                Science                   0.73
                   News+        Convo                     0.72
                                Science                   0.74
                   Science      Convo                     0.71
                                News+                     0.70
SummN              Convo        News+                     0.82
                                Science                   0.86
                   News+        Convo                     0.75
                                Science                   0.68
                   Science      Convo                     0.30
                                News+                     0.35

                                             prometheus_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -1.00
                                Science                      2.05
                   News+        Convo                        1.80
                                Science                     -1.00
                   Science      Convo                        1.24
                                News+                       -1.00
Llama 3.1          Convo        News+                       -1.00
                                Science                     -1.00
                   News+        Convo                        3.96
                                Science                     -1.00
                   Science      Convo                        3.98
                                News+                       -1.00
Llama 3.1 (0-shot) zero-shot    Convo                        3.95
                                News+                       -1.00
                                Science                     -1.00
PRIMERA            Convo        News+                       -1.00
                                Science                      1.80
                   News+        Convo                        1.27
                                Science                      1.80
                   Science      Convo                        1.27
                                News+                       -1.00
SummN              Convo        News+                       -1.00
                                Science                      2.40
                   News+        Convo                        1.72
                                Science                      1.72
                   Science      Convo                        1.24
                                News+                       -1.00

                                             compression_sentence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                        0.77
                                Science                      0.76
                   News+        Convo                        0.71
                                Science                      0.55
                   Science      Convo                        0.87
                                News+                        0.69
Llama 3.1          Convo        News+                        0.66
                                Science                      0.51
                   News+        Convo                        0.76
                                Science                      0.51

In [13]:
cross_performance.groupby(["train_domain", "test_domain"]).mean()

                          unieval_factuality  prometheus_factuality  \
train_domain test_domain
Convo        News+                      0.84                  -1.00
             Science                    0.80                   1.34
News+        Convo                      0.75                   1.91
             Science                    0.76                   1.08
Science      Convo                      0.63                   1.73
             News+                      0.74                  -1.00
zero-shot    Convo                      0.82                   3.00
             News+                      0.88                  -1.00
             Science                    0.88                  -1.00

                          prometheus_consistency  unieval_relevance  \
train_domain test_domain
Convo        News+                         -1.00               0.62
             Science                        1.33               0.71
News+        Convo                          1.99               0.71
             Science                        0.39               0.71
Science      Convo                          1.86               0.47
             News+                         -1.00               0.48
zero-shot    Convo                          3.26               0.94
             News+                         -1.00               0.92
             Science                       -1.00               0.91

                          prometheus_relevance  rouge_rouge1  rouge_rougeLsum  \
train_domain test_domain
Convo        News+                       -1.00          0.31             0.17
             Science                      1.54          0.24             0.14
News+        Convo                        2.37          0.21             0.13
             Science                      1.42          0.24             0.14
Science      Convo                        2.01          0.21             0.14
             News+                       -1.00          0.34             0.18
zero-shot    Convo                        3.43          0.22             0.15
             News+                       -1.00          0.40             0.21
             Science                     -1.00          0.25             0.16

                          moverscore  unieval_fluency  prometheus_fluency  \
train_domain test_domain
Convo        News+              0.08             0.84               -1.00
             Science            0.04             0.89                1.40
News+        Convo              0.01             0.74                2.21
             Science            0.05             0.83                0.38
Science      Convo             -0.00             0.70                1.99
             News+              0.09             0.71               -1.00
zero-shot    Convo              0.05             0.92                4.04
             News+              0.17             0.95               -1.00
             Science            0.08             0.93               -1.00

                          unieval_coherence  prometheus_coherence  \
train_domain test_domain
Convo        News+                     0.76                 -1.00
             Science                   0.80                  1.31
News+        Convo                     0.80                  2.19
             Science                   0.77                  0.38
Science      Convo                     0.55                  1.93
             News+                     0.57                 -1.00
zero-shot    Convo                     0.96                  3.95
             News+                     0.94                 -1.00
             Science                   0.97                 -1.00

                          compression_sentence  compression_token  \
train_domain test_domain
Convo        News+                        0.72               0.72
             Science                      0.68               0.69
News+        Convo                        0.73               0.59
             Science                      0.53               0.49
Science      Convo                        0.80               0.69
             News+                        0.66               0.66
zero-shot    Convo                        0.75               0.53
             News+                        0.66               0.61
             Science                      0.51               0.51

                          prometheus_coverage
train_domain test_domain
Convo        News+                      -1.00
             Science                    -1.00
News+        Convo                      -1.00
             Science                    -1.00
Science      Convo                      -1.00
             News+                      -1.00
zero-shot    Convo                      -1.00
             News+                      -1.00
             Science                    -1.00

In [14]:
# Limit to models where the model is trained and tested on different domains
def safe_divide(num, denom):
    if denom == 0:
        return 0.0
    return num / denom

def get_relative_performance_loss(row):
    key = [row.train_domain, row.model_type]
    if row.train_domain == "zero-shot":
        key[0] = row.test_domain
        key[1] = "ICL"
    original_performance = same_domain_performance_dict.get(
        tuple(key),
        {}
    )
    rel_performance = {
        "train_domain": row.train_domain,
        "test_domain": row.test_domain,
        "model_type": row.model_type
    }
    rel_performance.update({
        m: safe_divide(
            row[m] - original_performance.get(m, 0.0), 
            original_performance.get(m, 0.0)
        ) for m in wanted_metrics
    })
    return rel_performance

performance_diff = results_df[results_df.train_domain!=results_df.test_domain].apply(
    get_relative_performance_loss,
    axis="columns",
    result_type="expand"
)

In [15]:
diff = performance_diff.groupby(["model_type", "train_domain", "test_domain"]).mean(numeric_only=True)

print(diff.to_csv())

diff

model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,Convo,News+,0.1771797064344579,-1.4528985507246377,-1.4448398576512456,-0.27383792063492,-1.4098360655737705,-0.23466650469936362,-0.35414408709721795,-0.9184079769375271,-0.011042566259500378,-1.374251497005988,-0.03548471768299426,-1.4019292604501608,-0.16148944502507964,-0.06848520524538919,0.0
ConvoSumm,Convo,Science,0.05770943900300757,-0.12017130572010164,-0.1458887530631004,-0.09118964486419427,-0.09624787644121736,-0.2505590996643519,-0.33242180621523865,-0.71879346337971,-0.007043645972937263,-0.18787425149700607,0.017416681564018967,-0.17415271366737095,-0.16970475340646188,-0.06705714953136825,0.0
ConvoSumm,News+,Convo,-0.10119112668158631,-2.62,-2.6719999999999997,-0.04677361613763343,-3.084,-0.49511749497001206,-0.42502588750778586,-0.9611873921348378,-0.06774293495113722,-2.7880000000000003,-0.05459454567156976,-2.8040000000000003,0.4711350889239689,0.14761987185723432,0.0
ConvoSumm,News+,Science,-0.08897991977567374,-2.8185165702261967,0.0,-0.135608630947612,-3.183061546554445,-0.46334127128214286,-0.4113082755503178,-0.8129297912462232,0.09352712683613042,0.0,-0.1577741512923137,0.0,0.14596253565118608,0.016527187361875955,0.0
ConvoSumm,Science,Convo,-0.2329678596820304,-0.21873226238286478,-0.15313311036789296,-0.5298625376612793,-0.23156836996859842,-0.19243719697168563,-0.08705344921697522,-1.447919097811403,-0.1573839134413939,-0.10636168691922804,-0.34300392538606195,-0.15238566308243723,0.20437350127448534,0.07386222901489051,0.0
ConvoSumm,Science,News+,0.06762635842236231,-1.6362115127175367,-1.6357859531772574,-0.5090342062967588,-1.5426777048244362,-0.0068276687232641355,-0.07360807843201259,-0.3045281278351314,-0.13518756592480632,-1.6790564689063616,-0.26686691951177344,-1.6813620071684587,-0.04115208405795407,-0.042592297744852944,0.0
Llama 3.1,Convo,News+,0.05783216881569111,-1.3272251308900525,-1.311720698254364,-0.011471100094166463,-1.298329355608592,0.8372653927599791,0.39974696402227927,2.1366931771349047,0.016752252396173787,-1.2502502502502504,-0.0054220284868830215,-1.251004016064257,-0.12115713991595778,0.18037210327375755,0.0
Llama 3.1,Convo,Science,0.05717459340522567,-1.3272251308900525,-1.311720698254364,-0.027258186342084656,-1.298329355608592,0.1584869939250833,0.07921241163314614,0.5747003181431681,0.002362149440299078,-1.2502502502502504,0.029975567519439153,-1.251004016064257,-0.3235106547152985,-0.030604566170192936,0.0
Llama 3.1,News+,Convo,-0.0643081974261976,-4.064,-4.26,0.003705296919787795,-4.4079999999999995,-0.454485193922063,-0.2767458089813849,-0.6894369671035776,-0.020788512344868375,-5.056,0.006137926856819838,-4.9559999999999995,0.144654682652784,-0.13360290345203168,0.0
Llama 3.1,News+,Science,-0.0022763306288474954,0.0,0.0,-0.017092827426085727,0.0,-0.3683728626243056,-0.22754505554087012,-0.5001097616025743,-0.015128837710125175,0.0,0.036054623930027535,0.0,-0.22723578295000046,-0.17569450438255857,0.0
Llama 3.1,Science,Convo,-0.053625812867756306,-4.184,-4.343999999999999,0.03250273430880624,-4.4559999999999995,-0.1347298616557931,-0.052903214377855584,-0.3967616579387682,-0.003783499422637846,-5.004,-0.018285723129169255,-4.98,0.4660765401953044,0.047353716250127534,0.0
Llama 3.1,Science,News+,-0.003662982201938981,0.0,0.0,0.02144377716848231,0.0,0.5852795778982992,0.29755018738140054,0.9889992822486562,0.01362138900324176,0.0,-0.03208755467096175,0.0,0.2885850893487282,0.2173257054761451,0.0
Llama 3.1 (0-shot),zero-shot,Convo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Llama 3.1 (0-shot),zero-shot,News+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Llama 3.1 (0-shot),zero-shot,Science,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PRIMERA,Convo,News+,-0.003177802491987457,-1.69060773480663,-1.6329113924050633,0.03733528819254424,-1.5175983436853002,0.966144118090643,0.6589847145653308,-12.434690267347538,-0.06013843424316704,-1.744047619047619,0.017305864271756097,-1.769230769230769,-0.1583480851826541,-0.12221497449213373,0.0
PRIMERA,Convo,Science,0.016952999580997993,0.32526934064944013,0.2538370877419612,0.5295531703852323,0.2328697002667224,0.24045614374000054,0.1736320920481106,-5.998975875796463,0.22155407656623005,0.3608908844968813,0.07884821376064767,0.38752883097964635,-0.14665278873486057,-0.11281905163824427,0.0
PRIMERA,News+,Convo,0.00483522820539839,-2.448,-2.524,-0.023231920251507953,-2.976,-0.49202356881798015,-0.40930352097043693,-1.0686132210562655,0.06987969414615014,-2.292,0.042050093155990995,-2.268,0.20988186719187807,0.20820823954352208,0.0
PRIMERA,News+,Science,0.013999651492694436,-2.926880589163598,-2.958968963703314,0.45843634379184584,-3.3550762756443975,-0.36820885896502464,-0.2924494052231783,-0.5527257095438204,0.29040281004551755,-2.827459231983167,0.06400916248167476,-2.804313519200421,0.01395152280009098,0.005927919326494603,0.0
PRIMERA,Science,Convo,-0.024260125592043564,-0.28381654381654386,-0.22337813333333337,-0.34050770955191045,-0.18358839285714287,-0.19906088047862247,-0.1671097303427332,-1.178232896527151,-0.17926514708856858,-0.27340531177829097,-0.044803513111632894,-0.2916201117318436,0.1812598133234628,0.16885537620773225,0.0
PRIMERA,Science,News+,-0.025909721152092325,-1.518973518973519,-1.5069333333333335,-0.3235459298811576,-1.4243303571428572,0.5844652108511511,0.41840448544112024,1.2946686727002314,-0.23014690124268686,-1.5487875288683601,-0.06031161173966278,-1.558659217877095,-0.015783072603688927,-0.00972466189303115,0.0
SummN,Convo,News+,0.3428244678899245,-1.4078303425774878,-1.4019292604501608,-0.1504655767403794,-1.3597122302158273,-0.32629768076124477,-0.3589118585606633,-0.9271678010899085,-0.007455142093213017,-1.3448275862068966,0.16285331818586352,-1.3581661891117478,-0.07793061270144547,0.019513739480126472,0.0
SummN,Convo,Science,0.1979580398340926,0.012603480781558313,-0.03460862534695742,-0.07731320335563087,-0.07526897997646062,-0.3270568731776054,-0.3496923758383946,-0.7545861653830063,0.014819062938375416,-0.10199637023593469,0.22581054685428553,-0.1416069660215028,-0.07439815209894766,0.018176701637891556,0.0
SummN,News+,Convo,-0.07766684237340395,-2.496,-2.524,-0.05118428833270642,-3.0,-0.5140303197345713,-0.4502473106139044,-0.9683849334176705,-0.04777016760262596,-2.7199999999999998,-0.05264700686865518,-2.7199999999999998,0.5784640928941048,0.13179872486914096,0.0
SummN,News+,Science,-0.12267561309795848,-2.5854813256180957,-2.5928458705944237,-0.16551743885039782,-3.1467648605996845,-0.5138587963970701,-0.45468401818089,-0.8369935430532737,0.054985671626955064,-2.6754339821146766,-0.14420948739495335,-2.724355602314571,-0.04266462673678034,-0.20380351292991084,0.0
SummN,Science,Convo,-0.2914507760293737,-0.2278257111991358,-0.1499314821492968,-0.3721884864079792,-0.24782315521628503,-0.23154188648586202,-0.11611643670527128,-2.08514734691309,-0.06580564937927189,-0.07476600524148261,-0.21412863975758792,-0.1122957957957958,0.18068750761803773,0.01482584555928113,0.0
SummN,Science,News+,0.13655323107008746,-1.6845516744688513,-1.6855391272989544,-0.3119790705224816,-1.604643765903308,0.10017956129950777,0.025918901755844347,0.2829516082927046,0.05723343111562908,-1.7117184575065518,-0.08890993426260267,-1.7135885885885886,-0.041540406396458215,-0.011602725630869667,0.0

                                             unieval_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                      0.18
                                Science                    0.06
                   News+        Convo                     -0.10
                                Science                   -0.09
                   Science      Convo                     -0.23
                                News+                      0.07
Llama 3.1          Convo        News+                      0.06
                                Science                    0.06
                   News+        Convo                     -0.06
                                Science                   -0.00
                   Science      Convo                     -0.05
                                News+                     -0.00
Llama 3.1 (0-shot) zero-shot    Convo                      0.00
                                News+                      0.00
                                Science                    0.00
PRIMERA            Convo        News+                     -0.00
                                Science                    0.02
                   News+        Convo                      0.00
                                Science                    0.01
                   Science      Convo                     -0.02
                                News+                     -0.03
SummN              Convo        News+                      0.34
                                Science                    0.20
                   News+        Convo                     -0.08
                                Science                   -0.12
                   Science      Convo                     -0.29
                                News+                      0.14

                                             prometheus_factuality  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                        -1.45
                                Science                      -0.12
                   News+        Convo                        -2.62
                                Science                      -2.82
                   Science      Convo                        -0.22
                                News+                        -1.64
Llama 3.1          Convo        News+                        -1.33
                                Science                      -1.33
                   News+        Convo                        -4.06
                                Science                       0.00
                   Science      Convo                        -4.18
                                News+                         0.00
Llama 3.1 (0-shot) zero-shot    Convo                         0.00
                                News+                         0.00
                                Science                       0.00
PRIMERA            Convo        News+                        -1.69
                                Science                       0.33
                   News+        Convo                        -2.45
                                Science                      -2.93
                   Science      Convo                        -0.28
                                News+                        -1.52
SummN              Convo        News+                        -1.41
                                Science                       0.01
                   News+        Convo                        -2.50
                                Science                      -2.59
                   Science      Convo                        -0.23
                                News+                        -1.68

                                             prometheus_consistency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                         -1.44
                                Science                       -0.15
                   News+        Convo                         -2.67
                                Science                        0.00
                   Science      Convo                         -0.15
                                News+                         -1.64
Llama 3.1          Convo        News+                         -1.31
                                Science                       -1.31
                   News+        Convo                         -4.26
                                Science                        0.00
                   Science      Convo                         -4.34
                                News+                          0.00
Llama 3.1 (0-shot) zero-shot    Convo                          0.00
                                News+                          0.00
                                Science                        0.00
PRIMERA            Convo        News+                         -1.63
                                Science                        0.25
                   News+        Convo                         -2.52
                                Science                       -2.96
                   Science      Convo                         -0.22
                                News+                         -1.51
SummN              Convo        News+                         -1.40
                                Science                       -0.03
                   News+        Convo                         -2.52
                                Science                       -2.59
                   Science      Convo                         -0.15
                                News+                         -1.69

                                             unieval_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                    -0.27
                                Science                  -0.09
                   News+        Convo                    -0.05
                                Science                  -0.14
                   Science      Convo                    -0.53
                                News+                    -0.51
Llama 3.1          Convo        News+                    -0.01
                                Science                  -0.03
                   News+        Convo                     0.00
                                Science                  -0.02
                   Science      Convo                     0.03
                                News+                     0.02
Llama 3.1 (0-shot) zero-shot    Convo                     0.00
                                News+                     0.00
                                Science                   0.00
PRIMERA            Convo        News+                     0.04
                                Science                   0.53
                   News+        Convo                    -0.02
                                Science                   0.46
                   Science      Convo                    -0.34
                                News+                    -0.32
SummN              Convo        News+                    -0.15
                                Science                  -0.08
                   News+        Convo                    -0.05
                                Science                  -0.17
                   Science      Convo                    -0.37
                                News+                    -0.31

                                             prometheus_relevance  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -1.41
                                Science                     -0.10
                   News+        Convo                       -3.08
                                Science                     -3.18
                   Science      Convo                       -0.23
                                News+                       -1.54
Llama 3.1          Convo        News+                       -1.30
                                Science                     -1.30
                   News+        Convo                       -4.41
                                Science                      0.00
                   Science      Convo                       -4.46
                                News+                        0.00
Llama 3.1 (0-shot) zero-shot    Convo                        0.00
                                News+                        0.00
                                Science                      0.00
PRIMERA            Convo        News+                       -1.52
                                Science                      0.23
                   News+        Convo                       -2.98
                                Science                     -3.36
                   Science      Convo                       -0.18
                                News+                       -1.42
SummN              Convo        News+                       -1.36
                                Science                     -0.08
                   News+        Convo                       -3.00
                                Science                     -3.15
                   Science      Convo                       -0.25
                                News+                       -1.60

                                             rouge_rouge1  rouge_rougeLsum  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+               -0.23            -0.35
                                Science             -0.25            -0.33
                   News+        Convo               -0.50            -0.43
                                Science             -0.46            -0.41
                   Science      Convo               -0.19            -0.09
                                News+               -0.01            -0.07
Llama 3.1          Convo        News+                0.84             0.40
                                Science              0.16             0.08
                   News+        Convo               -0.45            -0.28
                                Science             -0.37            -0.23
                   Science      Convo               -0.13            -0.05
                                News+                0.59             0.30
Llama 3.1 (0-shot) zero-shot    Convo                0.00             0.00
                                News+                0.00             0.00
                                Science              0.00             0.00
PRIMERA            Convo        News+                0.97             0.66
                                Science              0.24             0.17
                   News+        Convo               -0.49            -0.41
                                Science             -0.37            -0.29
                   Science      Convo               -0.20            -0.17
                                News+                0.58             0.42
SummN              Convo        News+               -0.33            -0.36
                                Science             -0.33            -0.35
                   News+        Convo               -0.51            -0.45
                                Science             -0.51            -0.45
                   Science      Convo               -0.23            -0.12
                                News+                0.10             0.03

                                             moverscore  unieval_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+             -0.92            -0.01
                                Science           -0.72            -0.01
                   News+        Convo             -0.96            -0.07
                                Science           -0.81             0.09
                   Science      Convo             -1.45            -0.16
                                News+             -0.30            -0.14
Llama 3.1          Convo        News+              2.14             0.02
                                Science            0.57             0.00
                   News+        Convo             -0.69            -0.02
                                Science           -0.50            -0.02
                   Science      Convo             -0.40            -0.00
                                News+              0.99             0.01
Llama 3.1 (0-shot) zero-shot    Convo              0.00             0.00
                                News+              0.00             0.00
                                Science            0.00             0.00
PRIMERA            Convo        News+            -12.43            -0.06
                                Science           -6.00             0.22
                   News+        Convo             -1.07             0.07
                                Science           -0.55             0.29
                   Science      Convo             -1.18            -0.18
                                News+              1.29            -0.23
SummN              Convo        News+             -0.93            -0.01
                                Science           -0.75             0.01
                   News+        Convo             -0.97            -0.05
                                Science           -0.84             0.05
                   Science      Convo             -2.09            -0.07
                                News+              0.28             0.06

                                             prometheus_fluency  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                     -1.37
                                Science                   -0.19
                   News+        Convo                     -2.79
                                Science                    0.00
                   Science      Convo                     -0.11
                                News+                     -1.68
Llama 3.1          Convo        News+                     -1.25
                                Science                   -1.25
                   News+        Convo                     -5.06
                                Science                    0.00
                   Science      Convo                     -5.00
                                News+                      0.00
Llama 3.1 (0-shot) zero-shot    Convo                      0.00
                                News+                      0.00
                                Science                    0.00
PRIMERA            Convo        News+                     -1.74
                                Science                    0.36
                   News+        Convo                     -2.29
                                Science                   -2.83
                   Science      Convo                     -0.27
                                News+                     -1.55
SummN              Convo        News+                     -1.34
                                Science                   -0.10
                   News+        Convo                     -2.72
                                Science                   -2.68
                   Science      Convo                     -0.07
                                News+                     -1.71

                                             unieval_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                    -0.04
                                Science                   0.02
                   News+        Convo                    -0.05
                                Science                  -0.16
                   Science      Convo                    -0.34
                                News+                    -0.27
Llama 3.1          Convo        News+                    -0.01
                                Science                   0.03
                   News+        Convo                     0.01
                                Science                   0.04
                   Science      Convo                    -0.02
                                News+                    -0.03
Llama 3.1 (0-shot) zero-shot    Convo                     0.00
                                News+                     0.00
                                Science                   0.00
PRIMERA            Convo        News+                     0.02
                                Science                   0.08
                   News+        Convo                     0.04
                                Science                   0.06
                   Science      Convo                    -0.04
                                News+                    -0.06
SummN              Convo        News+                     0.16
                                Science                   0.23
                   News+        Convo                    -0.05
                                Science                  -0.14
                   Science      Convo                    -0.21
                                News+                    -0.09

                                             prometheus_coherence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -1.40
                                Science                     -0.17
                   News+        Convo                       -2.80
                                Science                      0.00
                   Science      Convo                       -0.15
                                News+                       -1.68
Llama 3.1          Convo        News+                       -1.25
                                Science                     -1.25
                   News+        Convo                       -4.96
                                Science                      0.00
                   Science      Convo                       -4.98
                                News+                        0.00
Llama 3.1 (0-shot) zero-shot    Convo                        0.00
                                News+                        0.00
                                Science                      0.00
PRIMERA            Convo        News+                       -1.77
                                Science                      0.39
                   News+        Convo                       -2.27
                                Science                     -2.80
                   Science      Convo                       -0.29
                                News+                       -1.56
SummN              Convo        News+                       -1.36
                                Science                     -0.14
                   News+        Convo                       -2.72
                                Science                     -2.72
                   Science      Convo                       -0.11
                                News+                       -1.71

                                             compression_sentence  \
model_type         train_domain test_domain
ConvoSumm          Convo        News+                       -0.16
                                Science                     -0.17
                   News+        Convo                        0.47
                                Science                      0.15
                   Science      Convo                        0.20
                                News+                       -0.04
Llama 3.1          Convo        News+                       -0.12
                                Science                     -0.32
                   News+        Convo                        0.14
                                Science                     -0.23

In [16]:
model_display_order = [
    "ConvoSumm",
    "PRIMERA",
    "SummN",
    "Llama 3.1",
    "Llama 3.1 (0-shot)"
]
diff_data = performance_diff.groupby(["model_type"]).mean(numeric_only=True).reindex(model_display_order)
print(diff_data.to_csv())
diff_data.T

model_type,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
ConvoSumm,-0.020103900379910444,-1.4777550336285563,-1.008607945709916,-0.26438442609039964,-1.5912319272270778,-0.27382487271847006,-0.28059359733659134,-0.8606276415574721,-0.04747891661894078,-1.0225906507214306,-0.14005126299678236,-1.0356382740614045,0.07485414056002411,0.009979105952065068,0.0
PRIMERA,-0.002926628326172088,-1.423834841018475,-1.432059122505514,0.056339873780841064,-1.5372872781771625,0.12196202740336125,0.0636931059197022,-3.323094882928501,0.01871434969724588,-1.3874681345300928,0.016183034803128975,-1.3840491311767469,0.014051542799038039,0.023038807842389968,0.0
SummN,0.030923751215561412,-1.398180928847002,-1.398142394306632,-0.18810801070159588,-1.572368831985261,-0.3021009992094743,-0.2839555163572132,-0.881554696927374,0.0010012011009747823,-1.4381237335509238,-0.018538533873941675,-1.4616688569720342,0.08710296709641847,-0.005181871169056731,0.0
Llama 3.1,-0.0014777601506372681,-1.8170750436300176,-1.8712402327514546,0.0003049490891232504,-1.910109785202864,0.10390734106353333,0.03655258068945255,0.35234739848030144,-0.0011608431063194616,-2.0934167500834167,0.0027288020032120836,-2.0730013386880857,0.037902122435926645,0.017524925165874502,0.0
Llama 3.1 (0-shot),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

model_type,ConvoSumm,PRIMERA,SummN,Llama 3.1,Llama 3.1 (0-shot)
unieval_factuality,-0.02,-0.00,0.03,-0.00,0.00
prometheus_factuality,-1.48,-1.42,-1.40,-1.82,0.00
prometheus_consistency,-1.01,-1.43,-1.40,-1.87,0.00
unieval_relevance,-0.26,0.06,-0.19,0.00,0.00
prometheus_relevance,-1.59,-1.54,-1.57,-1.91,0.00
rouge_rouge1,-0.27,0.12,-0.30,0.10,0.00
rouge_rougeLsum,-0.28,0.06,-0.28,0.04,0.00
moverscore,-0.86,-3.32,-0.88,0.35,0.00
unieval_fluency,-0.05,0.02,0.00,-0.00,0.00
prometheus_fluency,-1.02,-1.39,-1.44,-2.09,0.00
unieval_coherence,-0.14,0.02,-0.02,0.00,0.00
prometheus_coherence,-1.04,-1.38,-1.46,-2.07,0.00
compression_sentence,0.07,0.01,0.09,0.04,0.00
compression_token,0.01,0.02,-0.01,0.02,0.00
prometheus_coverage,0.00,0.00,0.00,0.00,0.00

In [17]:
performance_diff.groupby(["train_domain"]).mean(numeric_only=True)

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
train_domain,,,,,,,,,,,,,,,
Convo,0.11,-0.87,-0.88,-0.01,-0.85,0.13,-0.01,-2.38,0.02,-0.86,0.06,-0.87,-0.15,-0.02,0.00
News+,-0.05,-2.49,-2.19,0.00,-2.89,-0.46,-0.37,-0.80,0.04,-2.29,-0.03,-2.28,0.16,-0.00,0.00
Science,-0.05,-1.22,-1.21,-0.29,-1.21,0.06,0.03,-0.36,-0.09,-1.30,-0.13,-1.31,0.15,0.06,0.00
zero-shot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [18]:
diff_data = performance_diff.groupby(["train_domain", "test_domain"]).mean(numeric_only=True)
print(diff_data.to_csv(float_format='%.2f'))
diff_data

train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,News+,0.14,-1.47,-1.45,-0.10,-1.40,0.31,0.09,-3.04,-0.02,-1.43,0.03,-1.45,-0.13,0.00,0.00
Convo,Science,0.08,-0.28,-0.31,0.08,-0.31,-0.04,-0.11,-1.72,0.06,-0.29,0.09,-0.29,-0.18,-0.05,0.00
News+,Convo,-0.06,-2.91,-3.00,-0.03,-3.37,-0.49,-0.39,-0.92,-0.02,-3.21,-0.01,-3.19,0.35,0.09,0.00
News+,Science,-0.05,-2.08,-1.39,0.04,-2.42,-0.43,-0.35,-0.68,0.11,-1.38,-0.05,-1.38,-0.03,-0.09,0.00
Science,Convo,-0.15,-1.23,-1.22,-0.30,-1.28,-0.19,-0.11,-1.28,-0.10,-1.36,-0.16,-1.38,0.26,0.08,0.00
Science,News+,0.04,-1.21,-1.21,-0.28,-1.14,0.32,0.17,0.57,-0.07,-1.23,-0.11,-1.24,0.05,0.04,0.00
zero-shot,Convo,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
zero-shot,News+,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
zero-shot,Science,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

                          unieval_factuality  prometheus_factuality  \
train_domain test_domain
Convo        News+                      0.14                  -1.47
             Science                    0.08                  -0.28
News+        Convo                     -0.06                  -2.91
             Science                   -0.05                  -2.08
Science      Convo                     -0.15                  -1.23
             News+                      0.04                  -1.21
zero-shot    Convo                      0.00                   0.00
             News+                      0.00                   0.00
             Science                    0.00                   0.00

                          prometheus_consistency  unieval_relevance  \
train_domain test_domain
Convo        News+                         -1.45              -0.10
             Science                       -0.31               0.08
News+        Convo                         -3.00              -0.03
             Science                       -1.39               0.04
Science      Convo                         -1.22              -0.30
             News+                         -1.21              -0.28
zero-shot    Convo                          0.00               0.00
             News+                          0.00               0.00
             Science                        0.00               0.00

                          prometheus_relevance  rouge_rouge1  rouge_rougeLsum  \
train_domain test_domain
Convo        News+                       -1.40          0.31             0.09
             Science                     -0.31         -0.04            -0.11
News+        Convo                       -3.37         -0.49            -0.39
             Science                     -2.42         -0.43            -0.35
Science      Convo                       -1.28         -0.19            -0.11
             News+                       -1.14          0.32             0.17
zero-shot    Convo                        0.00          0.00             0.00
             News+                        0.00          0.00             0.00
             Science                      0.00          0.00             0.00

                          moverscore  unieval_fluency  prometheus_fluency  \
train_domain test_domain
Convo        News+             -3.04            -0.02               -1.43
             Science           -1.72             0.06               -0.29
News+        Convo             -0.92            -0.02               -3.21
             Science           -0.68             0.11               -1.38
Science      Convo             -1.28            -0.10               -1.36
             News+              0.57            -0.07               -1.23
zero-shot    Convo              0.00             0.00                0.00
             News+              0.00             0.00                0.00
             Science            0.00             0.00                0.00

                          unieval_coherence  prometheus_coherence  \
train_domain test_domain
Convo        News+                     0.03                 -1.45
             Science                   0.09                 -0.29
News+        Convo                    -0.01                 -3.19
             Science                  -0.05                 -1.38
Science      Convo                    -0.16                 -1.38
             News+                    -0.11                 -1.24
zero-shot    Convo                     0.00                  0.00
             News+                     0.00                  0.00
             Science                   0.00                  0.00

                          compression_sentence  compression_token  \
train_domain test_domain
Convo        News+                       -0.13               0.00
             Science                     -0.18              -0.05
News+        Convo                        0.35               0.09
             Science                     -0.03              -0.09
Science      Convo                        0.26               0.08
             News+                        0.05               0.04
zero-shot    Convo                        0.00               0.00
             News+                        0.00               0.00
             Science                      0.00               0.00

                          prometheus_coverage
train_domain test_domain
Convo        News+                       0.00
             Science                     0.00
News+        Convo                       0.00
             Science                     0.00
Science      Convo                       0.00
             News+                       0.00
zero-shot    Convo                       0.00
             News+                       0.00
             Science                     0.00

In [19]:
a = performance_diff.groupby(["train_domain"]).mean(numeric_only=True)
print(a.to_csv(float_format='%.2f'))
a

train_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,0.11,-0.87,-0.88,-0.01,-0.85,0.13,-0.01,-2.38,0.02,-0.86,0.06,-0.87,-0.15,-0.02,0.00
News+,-0.05,-2.49,-2.19,0.00,-2.89,-0.46,-0.37,-0.80,0.04,-2.29,-0.03,-2.28,0.16,-0.00,0.00
Science,-0.05,-1.22,-1.21,-0.29,-1.21,0.06,0.03,-0.36,-0.09,-1.30,-0.13,-1.31,0.15,0.06,0.00
zero-shot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
train_domain,,,,,,,,,,,,,,,
Convo,0.11,-0.87,-0.88,-0.01,-0.85,0.13,-0.01,-2.38,0.02,-0.86,0.06,-0.87,-0.15,-0.02,0.00
News+,-0.05,-2.49,-2.19,0.00,-2.89,-0.46,-0.37,-0.80,0.04,-2.29,-0.03,-2.28,0.16,-0.00,0.00
Science,-0.05,-1.22,-1.21,-0.29,-1.21,0.06,0.03,-0.36,-0.09,-1.30,-0.13,-1.31,0.15,0.06,0.00
zero-shot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [20]:
a = performance_diff.groupby(["test_domain"]).mean(numeric_only=True)
print(a.to_csv(float_format='%.2f'))
a

test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
Convo,-0.09,-1.84,-1.87,-0.15,-2.07,-0.30,-0.22,-0.98,-0.05,-2.03,-0.08,-2.03,0.27,0.07,0.00
News+,0.08,-1.19,-1.18,-0.17,-1.13,0.28,0.11,-1.10,-0.04,-1.18,-0.03,-1.19,-0.04,0.02,0.00
Science,0.01,-1.05,-0.75,0.05,-1.21,-0.21,-0.20,-1.07,0.07,-0.74,0.02,-0.75,-0.09,-0.06,0.00

,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
test_domain,,,,,,,,,,,,,,,
Convo,-0.09,-1.84,-1.87,-0.15,-2.07,-0.30,-0.22,-0.98,-0.05,-2.03,-0.08,-2.03,0.27,0.07,0.00
News+,0.08,-1.19,-1.18,-0.17,-1.13,0.28,0.11,-1.10,-0.04,-1.18,-0.03,-1.19,-0.04,0.02,0.00
Science,0.01,-1.05,-0.75,0.05,-1.21,-0.21,-0.20,-1.07,0.07,-0.74,0.02,-0.75,-0.09,-0.06,0.00

# Q: Evaluating the metrics

Theoretically, the metrics should all be very high on the ground truth datasets. Is that the case?

In [21]:
a = results_df[results_df.model_type=="ground_truth"]

print(a.to_csv(float_format='%.2f'))
a

,model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
0,ground_truth,Convo,Convo,0.71,3.03,3.13,0.99,3.26,-1.00,-1.00,1.00,0.90,3.28,0.73,3.48,0.90,0.85,-1
14,ground_truth,Science,Science,0.55,1.82,1.82,0.99,2.76,-1.00,-1.00,1.00,0.66,1.56,0.43,1.49,0.74,0.75,-1
28,ground_truth,News+,News+,0.70,-1.00,-1.00,0.98,-1.00,-1.00,-1.00,1.00,0.76,-1.00,0.75,-1.00,0.41,0.41,-1

,model_type,train_domain,test_domain,unieval_factuality,prometheus_factuality,prometheus_consistency,unieval_relevance,prometheus_relevance,rouge_rouge1,rouge_rougeLsum,moverscore,unieval_fluency,prometheus_fluency,unieval_coherence,prometheus_coherence,compression_sentence,compression_token,prometheus_coverage
0,ground_truth,Convo,Convo,0.71,3.03,3.13,0.99,3.26,-1.00,-1.00,1.00,0.90,3.28,0.73,3.48,0.90,0.85,-1
14,ground_truth,Science,Science,0.55,1.82,1.82,0.99,2.76,-1.00,-1.00,1.00,0.66,1.56,0.43,1.49,0.74,0.75,-1
28,ground_truth,News+,News+,0.70,-1.00,-1.00,0.98,-1.00,-1.00,-1.00,1.00,0.76,-1.00,0.75,-1.00,0.41,0.41,-1

# Checking Domain Performance Shift

In [22]:
df = results_df.copy()
# --- 2. Isolate In-Domain Baselines ---
# In-domain is where the training and testing domain are the same.
in_domain_mask = df['train_domain'] == df['test_domain']
in_domain_baselines = df[in_domain_mask].set_index(['model_type', 'train_domain'])

# Define identifier and metric columns
id_cols = ['model_type', 'train_domain', 'test_domain']
metric_cols = [col for col in df.columns if col not in id_cols]

# --- 3. Calculate Performance Difference for OOD cases ---
# Out-of-domain (OOD) is where training and testing domains differ.
ood_df = df[~in_domain_mask].copy()

# Exclude zero-shot models as they don't have a traditional "in-domain" baseline
ood_df = ood_df[ood_df['train_domain'] != 'zero-shot']
print("Note: 'Llama 3.1 (0-shot)' is excluded as it has no in-domain baseline.\n")

results_list = []
for index, ood_row in ood_df.iterrows():
    model = ood_row['model_type']
    train_domain = ood_row['train_domain']
    
    try:
        # Find the corresponding in-domain baseline performance
        baseline_row = in_domain_baselines.loc[(model, train_domain)]
        
        # Create a dictionary for the results
        diff_row = {
            'model_type': model,
            'train_domain': train_domain,
            'test_domain': ood_row['test_domain']
        }
        
        # Calculate the difference for each metric
        for metric in metric_cols:
            diff = ood_row[metric] - baseline_row[metric]
            diff_row[metric] = diff
            
        results_list.append(diff_row)

    except KeyError:
        print(f"Warning: Could not find in-domain baseline for model='{model}', train_domain='{train_domain}'. Skipping.")


# --- 4. Create and Display the Final DataFrame ---
diff_df = pd.DataFrame(results_list)

print("--- Performance Difference (Out-of-Domain vs. In-Domain) ---")
# Using to_string() to display all columns without truncation
a = diff_df.set_index(["model_type", "train_domain", "test_domain"]).sort_index()
a.loc["PRIMERA"].T

Note: 'Llama 3.1 (0-shot)' is excluded as it has no in-domain baseline.

--- Performance Difference (Out-of-Domain vs. In-Domain) ---

train_domain           Convo         News+         Science
test_domain            News+ Science Convo Science   Convo News+
unieval_factuality     -0.00    0.01  0.00    0.01   -0.02 -0.02
prometheus_factuality  -2.45    0.47  2.45    2.93   -0.55 -2.93
prometheus_consistency -2.58    0.40  2.52    2.96   -0.44 -2.97
unieval_relevance       0.02    0.21 -0.01    0.19   -0.21 -0.20
prometheus_relevance   -2.93    0.45  2.98    3.36   -0.43 -3.36
rouge_rouge1            0.18    0.05 -0.18   -0.14   -0.05  0.14
rouge_rougeLsum         0.07    0.02 -0.07   -0.05   -0.02  0.05
moverscore              0.14    0.07 -0.14   -0.07   -0.07  0.07
unieval_fluency        -0.04    0.14  0.04    0.18   -0.14 -0.18
prometheus_fluency     -2.34    0.49  2.29    2.83   -0.50 -2.82
unieval_coherence       0.01    0.05  0.03    0.04   -0.03 -0.04
prometheus_coherence   -2.30    0.50  2.27    2.80   -0.52 -2.79
compression_sentence   -0.12   -0.11  0.13    0.01    0.11 -0.01
compression_token      -0.07   -0.07  0.11    0.00    0.09 -0.01
prometheus_coverage     0.00    0.00  0.00    0.00    0.00  0.00

# Identifying why PRIMERA breaks the pattern

In [25]:
# --- 2. Isolate PRIMERA model results ---
primera_df = results_df[results_df['model_type'] == 'PRIMERA'].copy()

# --- 3. Define key metrics for analysis ---
metrics_to_analyze = [
    'unieval_relevance',
    'rouge_rougeLsum',
    "moverscore"
]

# --- 4. Group by training domain and analyze performance ---
for train_domain, group_df in primera_df.groupby('train_domain'):
    print(f"--- Analysis for PRIMERA trained on: {train_domain} ---")
    
    # Separate in-domain and out-of-domain (OOD) results
    in_domain_mask = group_df['test_domain'] == train_domain
    in_domain_row = group_df[in_domain_mask]
    ood_rows = group_df[~in_domain_mask]
    
    if in_domain_row.empty:
        print("  No in-domain results found for this training domain.\n")
        continue

    for metric in metrics_to_analyze:
        # Get the single in-domain score
        in_domain_score = in_domain_row[metric].iloc[0]
        
        # Get the series of out-of-domain scores
        ood_scores = ood_rows[metric]
        
        # Calculate the average of the OOD scores
        ood_average = ood_scores.mean()
        
        print(f"  Metric: {metric}")
        print(f"    In-Domain Score ({train_domain}): {in_domain_score:.2f}")
        
        # Display individual OOD scores
        ood_scores_list = [f"{score:.2f} ({test_dom})" for score, test_dom in zip(ood_scores, ood_rows['test_domain'])]
        print(f"    Out-of-Domain Scores: {', '.join(ood_scores_list)}")
        
        print(f"    Out-of-Domain Average: {ood_average:.2f}")
        print("-" * 20)
        
    print("\n" + "="*50 + "\n")

--- Analysis for PRIMERA trained on: Convo ---
  Metric: unieval_relevance
    In-Domain Score (Convo): 0.40
    Out-of-Domain Scores: 0.62 (Science), 0.42 (News+)
    Out-of-Domain Average: 0.52
--------------------
  Metric: rouge_rougeLsum
    In-Domain Score (Convo): 0.11
    Out-of-Domain Scores: 0.13 (Science), 0.18 (News+)
    Out-of-Domain Average: 0.16
--------------------
  Metric: moverscore
    In-Domain Score (Convo): -0.01
    Out-of-Domain Scores: 0.06 (Science), 0.13 (News+)
    Out-of-Domain Average: 0.09
--------------------

==================================================

--- Analysis for PRIMERA trained on: News+ ---
  Metric: unieval_relevance
    In-Domain Score (News+): 0.42
    Out-of-Domain Scores: 0.41 (Convo), 0.62 (Science)
    Out-of-Domain Average: 0.52
--------------------
  Metric: rouge_rougeLsum
    In-Domain Score (News+): 0.18
    Out-of-Domain Scores: 0.11 (Convo), 0.13 (Science)
    Out-of-Domain Average: 0.12
--------------------
  Metric: moverscore
    In-Domain Score (News+): 0.13
    Out-of-Domain Scores: -0.01 (Convo), 0.06 (Science)
    Out-of-Domain Average: 0.02
--------------------

==================================================

--- Analysis for PRIMERA trained on: Science ---
  Metric: unieval_relevance
    In-Domain Score (Science): 0.62
    Out-of-Domain Scores: 0.41 (Convo), 0.42 (News+)
    Out-of-Domain Average: 0.42
--------------------
  Metric: rouge_rougeLsum
    In-Domain Score (Science): 0.13
    Out-of-Domain Scores: 0.11 (Convo), 0.18 (News+)
    Out-of-Domain Average: 0.14
--------------------
  Metric: moverscore
    In-Domain Score (Science): 0.06
    Out-of-Domain Scores: -0.01 (Convo), 0.13 (News+)
    Out-of-Domain Average: 0.06
--------------------

==================================================

In [26]:
results_df.groupby(["model_type", "test_domain", "train_domain"])[metrics_to_analyze].mean(numeric_only=True)

                                             unieval_relevance  \
model_type         test_domain train_domain
ConvoSumm          Convo       Convo                      0.70
                               News+                      0.76
                               Science                    0.23
                   News+       Convo                      0.51
                               News+                      0.79
                               Science                    0.24
                   Science     Convo                      0.63
                               News+                      0.69
                               Science                    0.49
Llama 3.1          Convo       Convo                      0.93
                               News+                      0.93
                               Science                    0.94
                   News+       Convo                      0.92
                               News+                      0.92
                               Science                    0.93
                   Science     Convo                      0.91
                               News+                      0.91
                               Science                    0.91
Llama 3.1 (0-shot) Convo       zero-shot                  0.94
                   News+       zero-shot                  0.92
                   Science     zero-shot                  0.91
PRIMERA            Convo       Convo                      0.40
                               News+                      0.41
                               Science                    0.41
                   News+       Convo                      0.42
                               News+                      0.42
                               Science                    0.42
                   Science     Convo                      0.62
                               News+                      0.62
                               Science                    0.62
SummN              Convo       Convo                      0.72
                               News+                      0.73
                               Science                    0.31
                   News+       Convo                      0.61
                               News+                      0.77
                               Science                    0.34
                   Science     Convo                      0.67
                               News+                      0.64
                               Science                    0.49
ground_truth       Convo       Convo                      0.99
                   News+       News+                      0.98
                   Science     Science                    0.99

                                             rouge_rougeLsum  moverscore
model_type         test_domain train_domain
ConvoSumm          Convo       Convo                    0.21        0.06
                               News+                    0.13        0.01
                               Science                  0.15       -0.02
                   News+       Convo                    0.14        0.00
                               News+                    0.23        0.20
                               Science                  0.15        0.03
                   Science     Convo                    0.14        0.02
                               News+                    0.14        0.04
                               Science                  0.16        0.04
Llama 3.1          Convo       Convo                    0.15        0.05
                               News+                    0.15        0.05
                               Science                  0.15        0.05
                   News+       Convo                    0.21        0.17
                               News+                    0.21        0.17
                               Science                  0.21        0.17
                   Science     Convo                    0.16        0.09
                               News+                    0.16        0.09
                               Science                  0.16        0.09
Llama 3.1 (0-shot) Convo       zero-shot                0.15        0.05
                   News+       zero-shot                0.21        0.17
                   Science     zero-shot                0.16        0.08
PRIMERA            Convo       Convo                    0.11       -0.01
                               News+                    0.11       -0.01
                               Science                  0.11       -0.01
                   News+       Convo                    0.18        0.13
                               News+                    0.18        0.13
                               Science                  0.18        0.13
                   Science     Convo                    0.13        0.06
                               News+                    0.13        0.06
                               Science                  0.13        0.06
SummN              Convo       Convo                    0.21        0.09
                               News+                    0.12        0.01
                               Science                  0.14       -0.03
                   News+       Convo                    0.14        0.01
                               News+                    0.23        0.19
                               Science                  0.16        0.04
                   Science     Convo                    0.14        0.02
                               News+                    0.12        0.03
                               Science                  0.16        0.03
ground_truth       Convo       Convo                   -1.00        1.00
                   News+       News+                   -1.00        1.00
                   Science     Science                 -1.00        1.00